# ods_jky_allocate_di   tmp_adb: [0,2025-11-23]   tmp_odps:[20230701,20251123]    pro_odps:[20230701,20251123]  ok
# ods_jky_ass_business_refundlist_di    tmp_adb: [0,2025-11-24]     tmp_odps:[20230701,20251124]    pro_odps:[20230701,20251124]  ok
# ods_jky_customer_list_di  tmp_adb: [0,2025-11-24]      tmp_odps:[20230701,20251123]    pro_odps:[20230701,20251124]  ok
# ods_jky_erp_storage_goodsdocout_v2_di tmp_adb: [0,2025-11-24]   tmp_odps:[0,2025-11-24]    pro_odps: [0,20251124] ok
# ods_jky_purch_order_di    tmp_odps:[20241201,20251123]    pro_odps: [0,20251123]  ok
# ods_jky_qm_trades_fullinfo_di     tmp_adb: [0,2025-12-16]   tmp_odps:[0,20251216]    pro_odps: [0,20251216]   ok
# ods_jky_return_change_di      tmp_adb: [0,20251128]     tmp_odps:[20230701,20251128]    pro_odps: [0,20251128] ok

truncate table ods.tmp_qm_trades_fullinfo;
INSERT INTO ods.`tmp_qm_trades_fullinfo`
select checkTotal,
       tradeNo,
       otherFee,
       chargeCurrency,
       accountName,
       payType,
       payNo,
       sellerMemo,
       buyerMemo,
       appendMemo,
       tradeFrom,
       register,
       seller,
       auditor,
       reviewer,
       estimateWeight,
       packageWeight,
       tradeCount,
       goodsTypeCount,
       freezeReason,
       abnormalDescription,
       onlineTradeNo,
       goodslist,
       gmtCreate,
       gmtModified,
       stockoutNo,
       confirmTime,
       departName,
       lastShipTime,
       payStatus,
       chargeCurrencyCode,
       chargeExchangeRate,
       tradeStatus,
       grossProfit,
       estimateVolume,
       customerTypeName,
       customerGradeName,
       customerTags,
       customerCode,
       customerDiscount,
       specialReminding,
       blackList,
       tradeTime,
       country,
       `state`,
       city,
       district,
       town,
       zip,
       payTime,
       countryCode,
       cityCode,
       invoiceType,
       payerName,
       payerRegno,
       payerBankAccount,
       payerPhone,
       auditTime,
       payerAddress,
       invoiceNo,
       invoiceCode,
       invoiceStatus,
       payerBankName,
       preTypedetail,
       firstPayment,
       finalPayment,
       firstPaytime,
       finalPaytime,
       reviewTime,
       activationTime,
       customerTotalFee,
       customerDiscountFee,
       notifyPickTime,
       consignTime,
       orderNo,
       customerPostFee,
       shopId,
       shopName,
       customerPayment,
       companyName,
       `tradeOrderColumnExt-tradeId`                as tradeOrderColumnExt_tradeId,
       `tradeOrderColumnExt-customizeTradeColumn1`  as tradeOrderColumnExt_customizeTradeColumn1,
       `tradeOrderColumnExt-customizeTradeColumn2`  as tradeOrderColumnExt_customizeTradeColumn2,
       `tradeOrderColumnExt-customizeTradeColumn3`  as tradeOrderColumnExt_customizeTradeColumn3,
       `tradeOrderColumnExt-customizeTradeColumn4`  as tradeOrderColumnExt_customizeTradeColumn4,
       `tradeOrderColumnExt-customizeTradeColumn5`  as tradeOrderColumnExt_customizeTradeColumn5,
       `tradeOrderColumnExt-customizeTradeColumn6`  as tradeOrderColumnExt_customizeTradeColumn6,
       `tradeOrderColumnExt-customizeTradeColumn7`  as tradeOrderColumnExt_customizeTradeColumn7,
       `tradeOrderColumnExt-customizeTradeColumn8`  as tradeOrderColumnExt_customizeTradeColumn8,
       `tradeOrderColumnExt-customizeTradeColumn9`  as tradeOrderColumnExt_customizeTradeColumn9,
       `tradeOrderColumnExt-customizeTradeColumn10` as tradeOrderColumnExt_customizeTradeColumn10,
       isBillCheck,
       warehouseCode,
       warehouseName,
       logisticName,
       tradeId,
       billdate,
       logisticType,
       mainPostid,
       tradeType,
       totalFee,
       taxFee,
       receivedPostFee,
       discountFee,
       payment,
       couponFee,
       receivedTotal,
       postFee,
       isTableSwitch,
       completeTime,
       shopcode,
       signingTime,
       settleAuditTime,
       isDelete,
       localPayment,
       localExchangeRate,
       customerAccount,
       localCurrencyCode,
       platCompleteTime,
       buyerOpenUid,
       qq,
       tradeOrderRefundTime,
       assemblyGoodsDetail,
       apiType,
       logisticCode,
       agentShopName,
       tradeStatusExplain,
       flagIds,
       flagNames,
       sysFlagIds,
       shopTypeCode,
       sourceAfterNo,
       ticketCodeList,
       allCompassSourceContentType,
       customerName,
       invoiceAmount,
       realFee,
       finReceiptTime,
       extraLogisticNo,
       goodsDetail,
       tradeOrderPayList,
       goodsSerial,
       otherPaymentFees,
       tradeOrderGoodsColumnExts,
       tradeOrderAssemblyGoodsDtoList,
       packageDetail,
       pickUpTime
from jky.qm_trades_fullinfo;

truncate table ods.tmp_allocate;
insert into ods.tmp_allocate
select
    allocateId
    ,isAllocateDifferentCompany
    ,allocateNo
    ,outWarehouseId
    ,inWarehouseId
    ,outWarehouseCode
    ,intWarehouseCode
    ,outWarehouseName
    ,intWarehouseName
    ,allocateType
    ,allocatePrice
    ,applyUserId
    ,applyUserName
    ,applyDepartId
    ,applyDepartName
    ,applyDate
    ,operator
    ,operatorId
    ,auditUserId
    ,auditUserName
    ,auditDate
    ,status
    ,outStatus
    ,inStatus
    ,memo
    ,goodsCount
    ,skuCount
    ,totalAmount
    ,gmtCreate
    ,allocatePriceType
    ,flagData
    ,companyId
    ,companyName
    ,planOutdate
    ,planIndate
    ,isNegativeStock
    ,logisticNo
    ,reason
    ,gmtModified
    ,sourceNo
    ,`stockAllocateExpressInfo-id`
    ,`stockAllocateExpressInfo-relDataNo`
    ,`stockAllocateExpressInfo-sendCompanyName`
    ,`stockAllocateExpressInfo-send`
    ,`stockAllocateExpressInfo-sendTel`
    ,`stockAllocateExpressInfo-sendPhone`
    ,`stockAllocateExpressInfo-sendEmail`
    ,`stockAllocateExpressInfo-sendCountryName`
    ,`stockAllocateExpressInfo-sendProvinceName`
    ,`stockAllocateExpressInfo-sendCityName`
    ,`stockAllocateExpressInfo-sendTownName`
    ,`stockAllocateExpressInfo-sendStreetName`
    ,`stockAllocateExpressInfo-sendAddress`
    ,`stockAllocateExpressInfo-receiveCompanyName`
    ,`stockAllocateExpressInfo-receive`
    ,`stockAllocateExpressInfo-receiveTel`
    ,`stockAllocateExpressInfo-receivePhone`
    ,`stockAllocateExpressInfo-receiveEmail`
    ,`stockAllocateExpressInfo-receiveCountryName`
    ,`stockAllocateExpressInfo-receiveProvinceName`
    ,`stockAllocateExpressInfo-receiveCityName`
    ,`stockAllocateExpressInfo-receiveTownName`
    ,`stockAllocateExpressInfo-receiveStreetName`
    ,`stockAllocateExpressInfo-receiveAddress`
    ,stockAllocateDetailViews
from jky.allocate;

truncate table ods.tmp_ass_business_refundlist;
insert into ods.tmp_ass_business_refundlist
select
    flagIds
    ,`flagNames`
    ,`refundId`
    ,`refundNo`
    ,`tradeId`
    ,`tradeNo`
    ,`sourceTradeNo`
    ,`sourceRefundNo`
    ,`source`
    ,`sourceExplain`
    ,`sourceOrderId`
    ,`shopId`
    ,`shopName`
    ,`companyId`
    ,`companyName`
    ,`reasonDesc`
    ,`problemDesc`
    ,`refundStatus`
    ,`refundStatusExplain`
    ,`goodslist`
    ,`registerId`
    ,`registrant`
    ,`customerRemark`
    ,`serviceRemark`
    ,`appendMemo`
    ,`auditTime`
    ,`auditorId`
    ,`auditor`
    ,`responsiblePersonCode`
    ,`responsiblePersonDesc`
    ,`sendWarehouseId`
    ,`sendWarehouseName`
    ,`sourceDeliverTime`
    ,`tradeTime`
    ,`orderSummary`
    ,`passedTime`
    ,`printCount`
    ,`currentSegment`
    ,`negativeTradeNo`
    ,`gmtCreate`
    ,`payInfo-paymentNo`
    ,`payInfo-targetId`
    ,`payInfo-targetNo`
    ,`payInfo-returnTotal`
    ,`payInfo-payAccountId`
    ,`payInfo-payAccount`
    ,`payInfo-payStatus`
    ,`payInfo-payStatusExplain`
    ,`payInfo-discountFee`
    ,`payInfo-payAccounts`
    ,`payInfo-payTime`
    ,`payInfo-sourcePayTime`
    ,`payInfo-payDate`
    ,`payInfo-payee`
    ,`payInfo-customerAccountType`
    ,`payInfo-customerAccountTypeExplain`
    ,`payInfo-customerBankNo`
    ,`payInfo-customerBankName`
    ,`payInfo-customerBankAccount`
    ,`payInfo-refundType`
    ,`payInfo-refundTypeExplain`
    ,`payInfo-settlementCurrencyCode`
    ,`payInfo-settlementCurrency`
    ,`payInfo-payPersonId`
    ,`payInfo-payPerson`
    ,`payInfo-bankCode`
    ,`payInfo-bankName`
    ,`receiverInfo-customerId`
    ,`receiverInfo-customerName`
    ,`receiverInfo-customerAccount`
    ,`receiverInfo-zip`
    ,`receiverInfo-country`
    ,`receiverInfo-state`
    ,`receiverInfo-city`
    ,`receiverInfo-district`
    ,`receiverInfo-town`
    ,`receiverInfo-endCustomerAccount`
    ,`customColumnInfo-column1`
    ,`customColumnInfo-column2`
    ,`customColumnInfo-column3`
    ,`customColumnInfo-column4`
    ,`customColumnInfo-column5`
    ,`customColumnInfo-column6`
    ,`customColumnInfo-column7`
    ,`customColumnInfo-column8`
    ,`customColumnInfo-column9`
    ,`customColumnInfo-column10`
    ,`refundGoodsItems`
from jky.ass_business_refundlist;

truncate table ods.`tmp_customer_list`;
insert into ods.tmp_customer_list
select
    `customerId`
    ,`customerCode`
    ,`nickname`
    ,`alias`
    ,`vipLevel`
    ,`vipLevelName`
    ,`country`
    ,`state`
    ,`city`
    ,`district`
    ,`town`
    ,`zip`
    ,`gender`
    ,`age`
    ,`birthday`
    ,`email`
    ,`qq`
    ,`weiXin`
    ,`taxNumber`
    ,`customerManager`
    ,`customerManagerName`
    ,`refereeId`
    ,`referee`
    ,`debtAmountMax`
    ,`integralBalance`
    ,`debtAmount`
    ,`specialReminding`
    ,`customerType`
    ,`customerTypeName`
    ,`tagArr`
    ,`remark`
    ,`blackList`
    ,`noDisturb`
    ,`contacts`
    ,`preStorageBalance`
    ,`logisticType`
    ,`defaultDeliveryLogistics`
    ,`defaultDeliveryLogisticsName`
    ,`defaultSettlementMethod`
    ,`defaultSettlementMethodName`
    ,`defaultCollectionAccount`
    ,`defaultCollectionAccountName`
    ,`customerHasVipPassword`
    ,`gmtCreate`
    ,`id`
    ,`detailedAddress`
    ,`phone`
    ,`gmtModified`
    ,`enable`
    ,`customerCreateSource`
    ,`customerCreateSourceDesc`
    ,`invoice-taxNumber`
    ,`invoice-invoiceTitle`
    ,`invoice-openingBank`
    ,`invoice-phone`
    ,`invoice-accountNumber`
    ,`invoice-country`
    ,`invoice-state`
    ,`invoice-city`
    ,`invoice-district`
    ,`invoice-town`
    ,`invoice-detailedAddress`
    ,`invoice-invoiceType`
    ,`columnExt-customizeColumn1`
    ,`columnExt-customizeColumn2`
    ,`columnExt-customizeColumn3`
    ,`columnExt-customizeColumn4`
    ,`columnExt-customizeColumn5`
    ,`columnExt-customizeColumn6`
    ,`columnExt-customizeColumn7`
    ,`columnExt-customizeColumn8`
    ,`columnExt-customizeColumn9`
    ,`columnExt-customizeColumn10`
    ,`columnExt-customizeColumn11`
    ,`columnExt-customizeColumn12`
    ,`columnExt-customizeColumn13`
    ,`columnExt-customizeColumn14`
    ,`columnExt-customizeColumn15`
    ,`columnExt-customizeColumn16`
    ,`columnExt-customizeColumn17`
    ,`columnExt-customizeColumn18`
    ,`columnExt-customizeColumn19`
    ,`columnExt-customizeColumn20`
    ,`createChannelInfo-channelId`
    ,`createChannelInfo-channelName`
    ,`customerSourceArr`
    ,`receivablesAccountArr`
from jky.customer_list;

truncate table ods.`tmp_return_change`;
insert into ods.tmp_return_change
select
    `tradeAfterId`
    ,`returnChangeNo`
    ,`tradeAfterFrom`
    ,`tradeAfterStatus`
    ,`tradeId`
    ,`tradeNo`
    ,`sourceTradeNo`
    ,`sourceTradeAfterNo`
    ,`warehouseId`
    ,`warehouseCode`
    ,`warehouseName`
    ,`LogisticId`
    ,`logisticName`
    ,`sendWarehouseId`
    ,`sendWarehouseName`
    ,`mainPostid`
    ,`shopId`
    ,`shopName`
    ,`shopCode`
    ,`companyId`
    ,`companyName`
    ,`sourceShopId`
    ,`sourceShopName`
    ,`reasonDesc`
    ,`cancelReasonDesc`
    ,`rejectReasonDesc`
    ,`probleamDesc`
    ,`customerRemark`
    ,`serviceRemark`
    ,`auditTime`
    ,`deliveryTime`
    ,`consignTime`
    ,`goodslist`
    ,`flagIds`
    ,`flagNames`
    ,`registerId`
    ,`registrant`
    ,`responsiblePersonCode`
    ,`responsiblePersonDesc`
    ,`stockInNo`
    ,`deliveryNo`
    ,`deliveryPerson`
    ,`auditorId`
    ,`auditor`
    ,`sourceWarehouseId`
    ,`sourceWarehouseName`
    ,`tradeOrderSummary`
    ,`isFreeze`
    ,`freezeReason`
    ,`gmtCreate`
    ,`gmtModified`
    ,`sourceTradeStatus`
    ,`returnChangePay-tradeAfterId`
    ,`returnChangePay-returnAccounts`
    ,`returnChangePay-sendAccounts`
    ,`returnChangePay-receivePostFee`
    ,`returnChangePay-returnTotal`
    ,`returnChangePay-settlementCurrency`
    ,`returnChangePay-discountFee`
    ,`returnChangePay-payAccount`
    ,`returnChangePay-customerBankName`
    ,`returnChangePay-payStatus`
    ,`returnChangePay-payAccounts`
    ,`returnChangePay-payTime`
    ,`returnChangePay-payee`
    ,`returnChangePay-customerAccountType`
    ,`returnChangePay-customerBankAccount`
    ,`returnChangePay-resendType`
    ,`returnChangePay-settlementType`
    ,`returnChangePay-refundType`
    ,`returnChangePay-refundTypeCode`
    ,`returnChangePay-settlementPerson`
    ,`returnChangePay-settlementPersonId`
    ,`returnChangePay-settlementstring`
    ,`returnChangePay-gmtCreate`
    ,`returnChangePay-gmtModified`
    ,`returnChangePay-settlementCurrencyCode`
    ,`returnChangePay-payAccountId`
    ,`returnChangePay-paymentNo`
    ,`returnChangeReceiver-tradeAfterId`
    ,`returnChangeReceiver-customerId`
    ,`returnChangeReceiver-customerName`
    ,`returnChangeReceiver-customerAccount`
    ,`returnChangeReceiver-customerCode`
    ,`returnChangeReceiver-zip`
    ,`returnChangeReceiver-country`
    ,`returnChangeReceiver-state`
    ,`returnChangeReceiver-city`
    ,`returnChangeReceiver-district`
    ,`returnChangeReceiver-town`
    ,`returnChangeReceiver-gmtModified`
    ,`returnChangeReceiver-gmtCreate`
    ,`sendTradeNo`
    ,`returnTradeNo`
    ,`delete`
    ,`receiveStatus`
    ,`receiveStatusExplain`
    ,`applyTime`
    ,`deliveryCompleteRemark`
    ,`completeTime`
    ,`customColumnInfo-column1`
    ,`customColumnInfo-column2`
    ,`customColumnInfo-column3`
    ,`customColumnInfo-column4`
    ,`customColumnInfo-column5`
    ,`customColumnInfo-column6`
    ,`customColumnInfo-column7`
    ,`customColumnInfo-column8`
    ,`customColumnInfo-column9`
    ,`customColumnInfo-column10`
    ,`customColumnInfo-column11`
    ,`customColumnInfo-column12`
    ,`customColumnInfo-column13`
    ,`customColumnInfo-column14`
    ,`customColumnInfo-column15`
    ,`customColumnInfo-column16`
    ,`customColumnInfo-column17`
    ,`customColumnInfo-column18`
    ,`customColumnInfo-column19`
    ,`customColumnInfo-column20`
    ,`returnLogisticType`
    ,`returnLogisticTypeExplain`
    ,`sourceMainPostid`
    ,`sourceLogisticName`
    ,`returnChangeGoodsDetail`
    ,`tradeOrderAssemblyGoodsDtoList`
    ,`attachmentInfoList`
from jky.return_change;


select min(DATE_FORMAT(FROM_UNIXTIME(gmtCreate / 1000), '%Y%m%d')),min(DATE_FORMAT(gmtCreate, '%Y%m%d')) from jky.stock_out ;

desc ods.tmp_return_change;

select count(1) from ods.tmp_return_change;

select count(1) from jky.return_change ;


select gmtModified,* from jky.customer_list where gmtModified = '';




