#*********************************** 抖音平台 ***********************************
CREATE TABLE dy_product_constitute
(
    id           bigint       NOT NULL AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id      varchar(100) NOT NULL COMMENT '店铺id',
    biz_day      date COMMENT '日期',
    product_code varchar(50) COMMENT '商品编号',
    product_name varchar(50) COMMENT '商品名称',
    carrier_type varchar(100) COMMENT '载体类型',
    trans_amount decimal(10, 2) COMMENT '成交金额(元)',
    unit_price   decimal(10, 2) COMMENT '成交笔单价(元)',
    product_click_pay_rate double COMMENT '商品点击-支付转化率(次数)',
    created_by   varchar(100) NOT NULL COMMENT '插入人',
    created_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by   varchar(100) COMMENT '更新人',
    updated_at   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-商品构成';

CREATE TABLE dy_business_overview
(
    id                   bigint       NOT NULL AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) NOT NULL COMMENT '平台id，及店铺id，推广id',
    biz_day              date COMMENT '日期',
    trans_amount         decimal(10, 2) COMMENT '成交金额(元)',
    refund_amount        decimal(10, 2) COMMENT '退款金额(元)',
    trans_order_cnt      int COMMENT '成交订单数',
    trans_user_cnt       int COMMENT '成交人数',
    product_visit_num    int COMMENT '商品访客数',
    product_click_num    int COMMENT '商品点击人数',
    refund_order_cnt     int COMMENT '退款订单量',
    product_exposure_cnt int COMMENT '商品曝光次数',
    product_click_cnt    int COMMENT '商品点击次数',
    product_click_rate double COMMENT '商品点击率(次数)',
    product_click_pay_rate double COMMENT '商品点击-支付转化率(次数)',
    trans_user_price     decimal(10, 2) COMMENT '成交客单价(元)',
    trans_exposure_price decimal(10, 2) COMMENT '千次曝光成交金额(元)',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-经营概览';

CREATE TABLE dy_expert_analysis
(
    id                                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                           varchar(100) NOT NULL COMMENT '店铺id',
    expert_avatar                     varchar(200) COMMENT '达人头像',
    expert_nickname                   varchar(100) COMMENT '达人昵称',
    tiktok                            varchar(50) COMMENT '抖音号',
    trans_product_cnt                 int COMMENT '成交商品数',
    ecommerce_level                   int COMMENT '电商等级',
    fans_cnt                          int COMMENT '粉丝数',
    play_30d_rate double COMMENT '近30天电商开播频次',
    contribute_30d_rate double COMMENT '近30天电商投稿频次',
    trans_amount                      decimal(10, 2) COMMENT '成交金额(元)',
    trans_order_cnt                   int COMMENT '成交订单数',
    trans_deal_cnt                    int COMMENT '成交件数',
    trans_user_cnt                    int COMMENT '成交人数',
    predict_commission                decimal(10, 2) COMMENT '预估佣金支出',
    actual_commission_amount          decimal(10, 2) COMMENT '实际佣金支出',
    trans_new_user_cnt                int COMMENT '成交新用户数',
    trans_old_user_cnt                int COMMENT '成交老用户数',
    plant_grass_user_cnt              int COMMENT '种草人数',
    trans_new_user_amount             decimal(10, 2) COMMENT '新用户成交金额(元)',
    trans_old_user_amount             decimal(10, 2) COMMENT '老用户成交金额(元)',
    live_trans_amount                 decimal(10, 2) COMMENT '直播间成交金额(元)',
    live_trans_order_cnt              int COMMENT '直播间成交订单数',
    live_trans_user_cnt               int COMMENT '直播间成交人数',
    live_trans_grass_user_cnt         int COMMENT '直播间种草人数',
    short_video_trans_amount          decimal(10, 2) COMMENT '短视频成交金额(元)',
    short_video_trans_order_cnt       int COMMENT '短视频成交订单数',
    short_video__trans_user_cnt       int COMMENT '直播间成交人数',
    short_video__trans_grass_user_cnt int COMMENT '短视频种草人数',
    refund_amount                     decimal(10, 2) COMMENT '退款金额',
    refund_order_cnt                  int COMMENT '退款订单数',
    refund_user_cnt                   int COMMENT '退款人数',
    shipment_refund_amount            decimal(10, 2) COMMENT '发货前退款金额',
    shipment_refund_order_cnt         int COMMENT '发货前退款订单数',
    shipment_refund_user_cnt          int COMMENT '发货前退款人数',
    biz_day                           date COMMENT '日期',
    created_by                        varchar(100) NOT NULL COMMENT '插入人',
    created_at                        timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                        varchar(100) COMMENT '更新人',
    updated_at                        timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-达人分析';

CREATE TABLE dy_merchant_experience_score
(
    id                           bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                      varchar(100) NOT NULL COMMENT '店铺id',
    product_negative_review_rate varchar(100) COMMENT '商品差评率',
    product_quality_return_rate  varchar(100) COMMENT '商品品质退货率',
    order_delivery_duration      varchar(100) COMMENT '订单配送时长',
    payment_collect_24h_rate     varchar(100) COMMENT '24小时支付-揽收率',
    deliver_goods_feedback_rate  varchar(100) COMMENT '发货问题负向反馈率',
    after_sales_refusal_rate     varchar(100) COMMENT '售后拒绝率',
    platform_assistance_rate     varchar(100) COMMENT '平台求助率',
    im_dissatisfaction_rate      varchar(100) COMMENT 'IM不满意率',
    return_refund_duration       varchar(100) COMMENT '退货退款自主完结时长',
    refund_duration              varchar(100) COMMENT '仅退款自主完结时长',
    im_avg_respond_duration      varchar(100) COMMENT 'IM平均响应时长',
    shop_name                    varchar(100) COMMENT '店铺名称',
    biz_day                      date COMMENT '日期',
    created_by                   varchar(100) NOT NULL COMMENT '插入人',
    created_at                   timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                   varchar(100) COMMENT '更新人',
    updated_at                   timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-商家体验分';

CREATE TABLE dy_product_overview
(
    id                                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                               varchar(100) NOT NULL COMMENT '店铺id',
    biz_day                               date COMMENT '日期',
    product_image                         varchar(255) COMMENT '商品图片',
    product_title                         varchar(255) COMMENT '商品标题',
    product_code                          varchar(255) COMMENT '商品编号',
    trans_amount                          decimal(10, 2) COMMENT '成交金额',
    trans_order_cnt                       int COMMENT '成交订单数',
    trans_deal_cnt                        int COMMENT '成交件数',
    trans_user_cnt                        int COMMENT '成交人数',
    trans_customer_price                  int COMMENT '成交客单价',
    trans_exclude_refunds_amount          decimal(10, 2) COMMENT '成交金额（剔除退款）',
    trans_exclude_refunds_order_cnt       int COMMENT '成交订单数（剔除退款）',
    actual_settlement_amount              decimal(10, 2) COMMENT '实际结算金额',
    actual_commission_amount              decimal(10, 2) COMMENT '实际佣金支出',
    pre_sale_order_cnt                    int COMMENT '预售订单数',
    pre_sale_created_amount               decimal(10, 2) COMMENT '预售创建金额',
    refund_amount                         decimal(10, 2) COMMENT '退款金额',
    refund_order_cnt                      int COMMENT '退款订单数',
    refund_product_cnt                    int COMMENT '退款件数',
    refund_user_cnt                       int COMMENT '退款人数',
    trans_refund_amount                   decimal(10, 2) COMMENT '成交退款金额',
    trans_refund_order_cnt                int COMMENT '成交退款订单数',
    trans_refund_rate double COMMENT '成交退款率',
    before_shop_refund_rate double COMMENT '发货前成交退款率',
    after_shop_refund_rate double COMMENT '发货后成交退款率',
    quality_return_rate double COMMENT '品质退货率（滞后）',
    complaint_rate double COMMENT '投诉率（滞后）',
    negative_feedback_rate double COMMENT '差评率',
    negative_feedback_cnt                 int COMMENT '差评数',
    positive_feedback_rate double COMMENT '好评率',
    positive_feedback_cnt                 int COMMENT '好评数',
    feedback_cnt                          int COMMENT '评价数',
    order_negative_feedback_rate double COMMENT '订单差评率',
    product_exposure_cnt                  int COMMENT '商品曝光次数',
    product_click_cnt                     int COMMENT '商品点击次数',
    product_exposure_user_count           int COMMENT '商品曝光人数',
    product_click_num                     int COMMENT '商品点击人数',
    live_room_product_exposure_user_count int COMMENT '直播间商品曝光人数',
    live_room_product_click_user_count    int COMMENT '直播间商品点击人数',
    live_trans_amount                     decimal(10, 2) COMMENT '直播间成交金额',
    live_trans_order_cnt                  int COMMENT '直播间成交订单数',
    live_room_trans_product_cnt           int COMMENT '直播间成交件数',
    live_trans_user_cnt                   int COMMENT '直播间成交人数',
    live_room_trans_conversion_rate double COMMENT '直播间成交转化率',
    short_video_product_exposure_user_cnt int COMMENT '短视频商品曝光人数',
    short_video_product_click_user_cnt    int COMMENT '短视频商品点击人数',
    short_video_trans_amount              decimal(10, 2) COMMENT '短视频成交金额',
    short_video_trans_order_cnt           int COMMENT '短视频成交订单数',
    short_video_trans_cnt                 int COMMENT '短视频成交件数',
    short_video_trans_user_cnt            int COMMENT '短视频成交人数',
    short_video_pay_rate double COMMENT '短视频支付转化率',
    created_by                            varchar(100) NOT NULL COMMENT '插入人',
    created_at                            timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                            varchar(100) COMMENT '更新人',
    updated_at                            timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-商品概览';

CREATE TABLE dy_short_video_product
(
    id              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id         varchar(100) NOT NULL COMMENT '店铺id',
    video_title     varchar(255) COMMENT '视频标题',
    video_id        varchar(100) COMMENT '视频ID',
    play_link       varchar(100) COMMENT '播放链接',
    release_time    varchar(100) COMMENT '发布时间',
    expert_nickname varchar(100) COMMENT '达人昵称',
    expert_tiktok   varchar(100) COMMENT '达人抖音号',
    video_duration  varchar(100) COMMENT '视频时长',
    video_view_cnt double COMMENT '视频观看次数',
    trans_amount double COMMENT '成交金额(元)',
    trans_order_cnt double COMMENT '成交订单数',
    complete_rate   varchar(100) COMMENT '完播率',
    biz_day         date COMMENT '日期',
    product_id      varchar(100) COMMENT '商品id',
    product_name    varchar(100) COMMENT '商品名称',
    created_by      varchar(100) NOT NULL COMMENT '插入人',
    created_at      timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by      varchar(100) COMMENT '更新人',
    updated_at      timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-短视频商品数据';

CREATE TABLE dy_alliance_order
(
    id                                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                           varchar(100) NOT NULL COMMENT '店铺id',
    order_id                          varchar(100) COMMENT '订单id',
    product_id                        varchar(100) COMMENT '商品id',
    product_name                      varchar(100) COMMENT '商品名称',
    author_account                    varchar(100) COMMENT '作者账号',
    tiktok                            varchar(100) COMMENT '抖音/火山号',
    pay_amount double COMMENT '支付金额',
    commission_rate                   varchar(100) COMMENT '佣金率',
    predict_commission                decimal(10, 2) COMMENT '预估佣金支出',
    settlement_amount                 decimal(10, 2) COMMENT '结算金额',
    reality_commission                decimal(10, 2) COMMENT '实际佣金支出',
    order_status                      varchar(100) COMMENT '订单状态',
    settlement_timeout_reason         varchar(100) COMMENT '超时未结算原因',
    payment_time                      timestamp COMMENT '付款时间',
    receipt_time                      varchar(100) COMMENT '收货时间',
    order_settlement_time             varchar(100) COMMENT '订单结算时间',
    product_source                    varchar(100) COMMENT '商品来源',
    final_pay_time                    varchar(100) COMMENT '尾款支付时间',
    deposit_amount                    varchar(100) COMMENT '定金金额',
    shop_name                         varchar(100) COMMENT '店铺名称',
    product_cnt                       int COMMENT '商品数量',
    commission_invoice                varchar(100) COMMENT '佣金发票',
    frozen_rate                       varchar(100) COMMENT '冻结比例',
    is_tiered_commission              varchar(100) COMMENT '是否阶梯佣金',
    threshold_sale_cnt                varchar(100) COMMENT '门槛销量',
    base_commission_rate              varchar(100) COMMENT '基础佣金率',
    increased_commission_rate         varchar(100) COMMENT '升佣佣金率',
    estimated_bonus_commission_amount decimal(10, 2) COMMENT '预估奖励佣金支出',
    settled_bonus_commission_amount   decimal(10, 2) COMMENT '结算奖励佣金支出',
    tiered_plan_id                    varchar(100) COMMENT '阶梯计划ID',
    payment_subsidy                   decimal(10, 2) COMMENT '支付补贴',
    platform_subsidy                  decimal(10, 2) COMMENT '平台补贴',
    expert_subsidy                    decimal(10, 2) COMMENT '达人补贴',
    shipping_cost                     decimal(10, 2) COMMENT '运费',
    tax_fee                           decimal(10, 2) COMMENT '税费',
    shipping_subsidy                  decimal(10, 2) COMMENT '运费补贴',
    distribution_source               varchar(100) COMMENT '分销来源',
    marketing_activity_id             varchar(100) COMMENT '营销活动id',
    promotion_rate                    varchar(100) COMMENT '推广费率',
    promotion_service_fee double COMMENT '推广技术服务费',
    estimated_promotion_fee_expenditure double COMMENT '预估推广费支出',
    settled_promotion_fee_expenditure double COMMENT '结算推广费支出',
    plan_type                         varchar(100) COMMENT '计划类型',
    order_source                      varchar(100) COMMENT '订单来源',
    traffic_sub_source                varchar(100) COMMENT '流量细分来源',
    traffic_source                    varchar(100) COMMENT '流量来源',
    order_type                        varchar(100) COMMENT '订单类型',
    created_by                        varchar(100) NOT NULL COMMENT '插入人',
    created_at                        timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                        varchar(100) COMMENT '更新人',
    updated_at                        timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-联盟订单明细';

CREATE TABLE rpa_data.dy_finance_statement
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                         date COMMENT '日期',
    fund_pool_type                  varchar(100) COMMENT '资金池类型',
    total_balance_consumption       decimal(10, 2) COMMENT '余额总消耗(元)',
    non_grant_consumption           decimal(10, 2) COMMENT '非赠款消耗(元)',
    grant_consumption               decimal(10, 2) COMMENT '赠款消耗(元)',
    cashback_redemption_consumption decimal(10, 2) COMMENT '消返红包消耗(元)',
    shared_grant_consumption        decimal(10, 2) COMMENT '共享赠款消耗(元)',
    minus_redemption_consumption    decimal(10, 2) COMMENT '立减红包消耗(元)',
    total_deposit                   decimal(10, 2) COMMENT '总存入(元)',
    total_transfer_in               decimal(10, 2) COMMENT '总转入(元)',
    total_transfer_out              decimal(10, 2) COMMENT '总转出(元)',
    total_balance                   decimal(10, 2) COMMENT '总余额(元)',
    grant_balance                   decimal(10, 2) COMMENT '赠款余额(元)',
    non_grant_balance               decimal(10, 2) COMMENT '非赠款余额(元)',
    account                         varchar(100) COMMENT '账户',
    account_id                      varchar(100) COMMENT '账户ID',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-财务流水';

CREATE TABLE dy_promotion_global_tiktok
(
    id                        bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    tiktok                    varchar(100) COMMENT '抖音号',
    biz_day                   date COMMENT '日期',
    total_consumption         decimal(10, 2) COMMENT '整体消耗(元)',
    total_pay_roi             decimal(10, 2) COMMENT '整体支付ROI',
    total_trans_amount        decimal(10, 2) COMMENT '整体成交金额(元)',
    total_trans_order_cnt     int COMMENT '整体成交订单数',
    total_trans_order_cost    decimal(10, 2) COMMENT '整体成交订单成本(元)',
    total_smart_coupon_amount int COMMENT '整体成交智能优惠券金额(元)',
    account_id                varchar(100) COMMENT '账户ID',
    account_name              varchar(100) COMMENT '账户名称',
    created_by                varchar(100) NOT NULL COMMENT '插入人',
    created_at                timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                varchar(100) COMMENT '更新人',
    updated_at                timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-全域推广数据-抖音';

CREATE TABLE dy_promotion_global_product
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    product_id                      BIGINT COMMENT '商品ID',
    product_name                    VARCHAR(255) COMMENT '商品名称',
    biz_day                         DATE COMMENT '日期',
    total_display_cnt DOUBLE COMMENT '整体展示次数',
    total_click_cnt DOUBLE COMMENT '整体点击次数',
    total_click_rate                VARCHAR(50) COMMENT '整体点击率',
    total_conversion_rate           VARCHAR(50) COMMENT '整体转化率',
    total_cost                      decimal(10, 2) COMMENT '整体消耗',
    total_order_cnt                 BIGINT COMMENT '整体成交订单数',
    total_sale_amount               decimal(10, 2) COMMENT '整体成交金额',
    total_pay_roi DOUBLE COMMENT '整体支付ROI',
    total_order_cost                decimal(10, 2) COMMENT '整体成交订单成本',
    total_smart_coupon_amount       decimal(10, 2) COMMENT '整体成交智能优惠券金额',
    total_unfinished_presale_amount decimal(10, 2) COMMENT '整体未完结预售订单预估金额',
    account_id                      BIGINT COMMENT '账号ID',
    account_name                    VARCHAR(255) COMMENT '账号名称',
    data_page_link                  VARCHAR(255) COMMENT '数据页面链接',
    update_time                     TIMESTAMP COMMENT '更新时间',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-全域推广数据-商品';

CREATE TABLE dy_promotion_product_tiktok
(
    id                        bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    tiktok                    varchar(100) COMMENT '抖音号',
    tiktok_name               varchar(100) COMMENT '抖音号名称',
    biz_day                   date COMMENT '日期',
    cost                      decimal(10, 2) COMMENT '消耗(元)',
    display_cnt               int COMMENT '展示次数',
    click_through_rate double COMMENT '点击率(%)',
    click_cnt double COMMENT '点击次数',
    avg_cpm_amount            decimal(10, 2) COMMENT '平均千次展现费用(元)',
    direct_transaction_amount decimal(10, 2) COMMENT '直接成交金额(元)',
    direct_payment_roi        decimal(10, 2) COMMENT '直接支付ROI',
    direct_transaction_order_cnt double COMMENT '直接成交订单数',
    new_customer_first_order_cnt double COMMENT '店铺首单新客人数',
    new_customer_first_order_roi double COMMENT '店铺首单新客直接支付ROI',
    new_customer_30_days_roi double COMMENT '店铺首单新客30天累计支付ROI',
    account                   varchar(100) COMMENT '账户',
    account_id                varchar(100) COMMENT '账户ID',
    order_platform            varchar(100) COMMENT '下单平台',
    created_by                varchar(100) NOT NULL COMMENT '插入人',
    created_at                timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                varchar(100) COMMENT '更新人',
    updated_at                timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-商品推广-抖音';

CREATE TABLE dy_promotion_product_product
(
    id                        bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    product_id                varchar(100) COMMENT '商品id',
    product_name              varchar(100) COMMENT '商品名称',
    biz_day                   date COMMENT '日期',
    cost                      decimal(10, 2) COMMENT '消耗(元)',
    display_cnt               int COMMENT '展示次数',
    click_through_rate double COMMENT '点击率(%)',
    click_cnt double COMMENT '点击次数',
    avg_cpm_amount            decimal(10, 2) COMMENT '平均千次展现费用(元)',
    direct_transaction_amount decimal(10, 2) COMMENT '直接成交金额(元)',
    direct_payment_roi        decimal(10, 2) COMMENT '直接支付ROI',
    direct_transaction_order_cnt double COMMENT '直接成交订单数',
    new_customer_first_order_cnt double COMMENT '店铺首单新客人数',
    new_customer_first_order_roi double COMMENT '店铺首单新客直接支付ROI',
    new_customer_30_days_roi double COMMENT '店铺首单新客30天累计支付ROI',
    account                   varchar(100) COMMENT '账户',
    account_id                varchar(100) COMMENT '账户ID',
    order_platform            varchar(100) COMMENT '下单平台',
    trans_smart_coupon_amount varchar(100) COMMENT '成交智能优惠券金额',
    created_by                varchar(100) NOT NULL COMMENT '插入人',
    created_at                timestamp DEFAULT '2024-08-30 10:51:22.919' COMMENT '插入时间',
    updated_by                varchar(100) COMMENT '更新人',
    updated_at                timestamp DEFAULT '2024-08-30 10:51:22.919' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-商品推广-商品';

CREATE TABLE dy_promotion_living_tiktok
(
    id                           bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    tiktok                       varchar(100) COMMENT '抖音号',
    tiktok_name                  varchar(100) COMMENT '抖音号名称',
    biz_day                      date COMMENT '日期',
    cost                         decimal(10, 2) COMMENT '消耗(元)',
    display_cnt                  decimal(10, 2) COMMENT '展示次数',
    click_through_rate           decimal(10, 2) COMMENT '点击率(%)',
    click_cnt                    decimal(10, 2) COMMENT '点击次数',
    avg_cpm_amount               decimal(10, 2) COMMENT '平均千次展现费用(元)',
    total_pay_7d_roi             decimal(10, 2) COMMENT '7日总支付ROI',
    total_trans_7d_order_cnt     decimal(10, 2) COMMENT '7日总成交订单数',
    total_trans_7d_amount        decimal(10, 2) COMMENT '7日总成交金额(元)',
    direct_transaction_order_cnt decimal(10, 2) COMMENT '直接成交订单数',
    direct_transaction_amount    decimal(10, 2) COMMENT '直接成交金额(元)',
    direct_payment_roi           decimal(10, 2) COMMENT '直接支付ROI',
    new_customer_first_order_cnt decimal(10, 2) COMMENT '店铺首单新客人数',
    new_customer_first_order_roi decimal(10, 2) COMMENT '店铺首单新客直接支付ROI',
    new_customer_30_days_roi     decimal(10, 2) COMMENT '店铺首单新客30天累计支付ROI',
    account                      varchar(100) COMMENT '账户',
    account_id                   varchar(100) COMMENT '账户ID',
    order_platform               varchar(100) COMMENT '下单平台',
    created_by                   varchar(100) NOT NULL COMMENT '插入人',
    created_at                   timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                   varchar(100) COMMENT '更新人',
    updated_at                   timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-直播推广-抖音';

CREATE TABLE dy_promotion_fee_consumption
(
    id               bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    account          varchar(100) COMMENT '账户',
    consumption      decimal(10, 2) COMMENT '消耗',
    account_id       varchar(100) COMMENT '账户ID',
    biz_day          varchar(100) COMMENT '消耗日期',
    down_day         varchar(100) COMMENT '下载日期',
    created_by       varchar(100) NOT NULL COMMENT '插入人',
    created_at       timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by       varchar(100) COMMENT '更新人',
    updated_at       timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    consumption_type int COMMENT '消耗类型：1-标准推广,2-全域推广',
    PRIMARY KEY (id)
) COMMENT ='抖音-推广费消耗明细';

CREATE TABLE dy_reception_volume
(
    id                                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                           date COMMENT '日期',
    shop_id                           varchar(100) COMMENT '店铺id',
    shop_name                         varchar(100) COMMENT '店铺名称',
    customer_service_nickname         varchar(100) COMMENT '客服昵称',
    account_name                      varchar(100) COMMENT '账号名称',
    receive_manually_user_cnt double COMMENT '人工已接待人数',
    receive_manually_session_cnt double COMMENT '人工已接待会话量',
    cpd                               decimal(10, 2) COMMENT 'CPD',
    dissatisfaction_rate              varchar(100) COMMENT '不满意率',
    manual_response_3min_session_rate varchar(100) COMMENT '3分钟人工回复率 (会话)',
    manual_response_3min_rate         varchar(100) COMMENT '3分钟人工回复率',
    first_response_duration double COMMENT '首次响应时长（秒）',
    avg_response_duration double COMMENT '平均响应时长（秒）',
    new_avg_response_duration double COMMENT '新平均响应时长（秒）',
    satisfaction_rate                 varchar(100) COMMENT '满意率',
    customer_service_sales_amount     decimal(10, 2) COMMENT '客服销售额（元）',
    inquiry_user_cnt double COMMENT '询单人数',
    order_user_cnt double COMMENT '下单人数',
    pay_user_cnt double COMMENT '支付人数',
    inquiry_conversion_rate           varchar(100) COMMENT '询单转化率',
    warning_session_cnt double COMMENT '预警会话量',
    pc_online_duration double COMMENT 'PC在线时长（时）',
    pc_rest_duration double COMMENT 'PC小休时长（时）',
    pc_offline_duration double COMMENT 'PC离线时长（时）',
    created_by                        varchar(100) NOT NULL COMMENT '插入人',
    created_at                        timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                        varchar(100) COMMENT '更新人',
    updated_at                        timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-接待量';

CREATE TABLE rpa_data.dy_cid
(
    id                        bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    login_user_id             varchar(100) COMMENT '登录用户id',
    biz_day                   date COMMENT '日期',
    account_name              varchar(100) COMMENT '账号名称',
    account_id                varchar(100) COMMENT '账号id',
    account                   varchar(100) COMMENT '账号',
    business_platform         varchar(100) COMMENT '业务平台',
    agent_name                varchar(100) COMMENT '所属代理商名称',
    agent_id                  varchar(100) COMMENT '所属代理商ID',
    shared_grant_expenditure  decimal(10, 2) COMMENT '共享赠款支出',
    total_account_expenditure decimal(10, 2) COMMENT '账户总支出(¥)',
    cash_account_expenditure  decimal(10, 2) COMMENT '账户现金支出(¥)',
    grant_account_expenditure decimal(10, 2) COMMENT '账户赠款支出(¥)',
    total_account_deposit     decimal(10, 2) COMMENT '账户总存入(¥)',
    total_account_inflow      decimal(10, 2) COMMENT '账户总转入(¥)',
    total_account_outflow     decimal(10, 2) COMMENT '账户总转出(¥)',
    non_grant_balance         decimal(10, 2) COMMENT '非赠款余额(¥)',
    grant_balance             decimal(10, 2) COMMENT '赠款余额(¥)',
    total_balance             decimal(10, 2) COMMENT '总余额(¥)',
    frozen_amount             decimal(10, 2) COMMENT '冻结(¥)',
    created_by                varchar(100) NOT NULL COMMENT '插入人',
    created_at                timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                varchar(100) COMMENT '更新人',
    updated_at                timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='抖音-CID';



select '海豚智投-短视频-财务报表',
       'htzt_finance',
       COLUMN_NAME,
       DATA_TYPE,
       COLUMN_COMMENT,
       CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'htzt_finance';

