#*********************************** 京东平台 ***********************************
CREATE TABLE jd_jtk_bill
(
    id                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    platform_type     int COMMENT '1.京东自营 2：京东pop',
    shop_id           varchar(100) COMMENT '店铺id',
    shop_name         varchar(100) COMMENT '店铺名称',
    trans_id          varchar(255) COMMENT '流水单号',
    settlement_amount decimal(10, 2) COMMENT '结算金额',
    expense_date      date COMMENT '费用时间',
    status            varchar(255) COMMENT '状态',
    settlement_date   date COMMENT '结算时间',
    created_by        varchar(100) NOT NULL COMMENT '插入人',
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by        varchar(100) COMMENT '更新人',
    updated_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-京挑客-结算账单';

CREATE TABLE jd_jzt_bill
(
    id               bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    platform_type    int COMMENT '1.京东自营 2：京东pop',
    shop_id          varchar(100) COMMENT '店铺id',
    shop_name        varchar(100) COMMENT '店铺名称',
    trans_id         varchar(100) COMMENT '流水单号',
    account          varchar(100) COMMENT '账号',
    placement_date   date COMMENT '投放日期',
    trans_type       varchar(100) COMMENT '交易类型',
    expend_amount    decimal(10, 2) COMMENT '支出',
    settlement_date  date COMMENT '结算时间',
    remain_amount    decimal(10, 2) COMMENT '结余',
    invoicing_method varchar(255) COMMENT '开票方式',
    created_by       varchar(100) NOT NULL COMMENT '插入人',
    created_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by       varchar(100) COMMENT '更新人',
    updated_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-京准通-结算账单';

CREATE TABLE jd_autarky_product_list
(
    id               bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    day_type         int COMMENT '统计范围：1：:1天，15：15天',
    day_range        varchar(100) COMMENT '日期范围',
    price_range      varchar(100) COMMENT '价格区间',
    rank_num         bigint COMMENT '排名',
    product_id       varchar(100) COMMENT '商品编号',
    product_name     varchar(100) COMMENT '商品名称',
    brand            varchar(100) COMMENT '所属品牌',
    trans_amount_idx double COMMENT '成交金额指数',
    trans_volume_idx double COMMENT '成交件数指数',
    traffic_idx double COMMENT '流量指数',
    visit_idx double COMMENT '访客指数',
    trans_unit_price decimal(10, 2) COMMENT '成交客单价',
    trans_conversion_rate double COMMENT '成交转化率',
    add_cart_user_num double COMMENT '加购人数',
    follow_user_num double COMMENT '关注人数',
    search_click_idx double COMMENT '搜索点击指数',
    created_by       varchar(100) NOT NULL COMMENT '插入人',
    created_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by       varchar(100) COMMENT '更新人',
    updated_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-商品榜单';

CREATE TABLE jd_autarky_product_performance
(
    id                     bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                varchar(100) COMMENT '店铺id',
    biz_day                date COMMENT '日期',
    product_id             varchar(100) COMMENT '商品编号',
    product_name           varchar(100) COMMENT '商品名称',
    financial_sales_volume bigint COMMENT '财务销量',
    revenue                decimal(12, 4) COMMENT '收入',
    cost                   decimal(12, 4) COMMENT '成本',
    gross_profit           decimal(12, 4) COMMENT '毛利',
    coupon_deductions double COMMENT '优惠券抵减数',
    points_deductions double COMMENT '积分抵减数',
    promotion_deductions double COMMENT '满返满减额',
    inventory_turnover_days double COMMENT '库存周转天数',
    created_by             varchar(100) NOT NULL COMMENT '插入人',
    created_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by             varchar(100) COMMENT '更新人',
    updated_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-商品业绩';

CREATE TABLE jd_autarky_recharge
(
    id          bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id     varchar(100) COMMENT '店铺id',
    biz_day     date COMMENT '日期',
    shop_name   varchar(200) COMMENT '店铺',
    gift_amount decimal(12, 2) COMMENT '赠送金额',
    created_by  varchar(100) NOT NULL COMMENT '插入人',
    created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by  varchar(100) COMMENT '更新人',
    updated_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-充值数据';

CREATE TABLE jd_autarky_trade
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id               varchar(100) COMMENT '店铺id',
    biz_day               date COMMENT '日期',
    page_views            bigint COMMENT '浏览量',
    visit_cnt             bigint COMMENT '访客数',
    trans_user_num        bigint COMMENT '成交人数',
    trans_conversion_rate varchar(100) COMMENT '成交转化率',
    trans_order_cnt       bigint COMMENT '成交单量',
    trans_product_cnt     bigint COMMENT '成交商品件数',
    trans_amount          decimal(10, 2) COMMENT '成交金额',
    trans_unit_price      decimal(10, 2) COMMENT '成交客单价',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-交易概况';

CREATE TABLE jd_autarky_product
(
    id                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id           varchar(100) COMMENT '店铺id',
    shop_name         varchar(100) COMMENT '店铺名称',
    biz_day           date COMMENT '日期',
    product_name      varchar(100) COMMENT '商品名称',
    sku               bigint COMMENT 'SKU',
    brand             varchar(100) COMMENT '品牌',
    first_cate        varchar(100) COMMENT '一级类目',
    secondary_cate    varchar(100) COMMENT '二级类目',
    third_cate        varchar(100) COMMENT '三级类目',
    business_model    varchar(100) COMMENT '经营模式',
    page_view         bigint COMMENT '浏览量',
    visit_num         bigint COMMENT '访客数',
    avg_page_view     bigint COMMENT '人均浏览量',
    avg_stay_duration bigint COMMENT '平均停留时长',
    trans_user_num    bigint COMMENT '成交人数',
    trans_conversion_rate double COMMENT '成交转化率',
    trans_order_cnt   bigint COMMENT '成交单量',
    trans_product_cnt bigint COMMENT '成交商品件数',
    trans_amount      decimal(10, 0) COMMENT '成交金额',
    trans_unit_price  decimal(10, 2) COMMENT '成交客单价',
    cart_add_num      bigint COMMENT '加购人数',
    cart_conversion_rate double COMMENT '加购转化率',
    cart_product_cnt  bigint COMMENT '加购商品件数',
    created_by        varchar(100) NOT NULL COMMENT '插入人',
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by        varchar(100) COMMENT '更新人',
    updated_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-商品明细';

CREATE TABLE jd_autarky_product_stock
(
    id                            bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                       varchar(100) COMMENT '店铺id',
    biz_day                       date COMMENT '日期',
    product_name                  varchar(100) COMMENT '商品名称',
    sku                           varchar(100) COMMENT 'SKU',
    brand                         varchar(100) COMMENT '品牌',
    first_cate                    varchar(100) COMMENT '一级类目',
    secondary_cate                varchar(100) COMMENT '二级类目',
    third_cate                    varchar(100) COMMENT '三级类目',
    shop_name                     varchar(100) COMMENT '店铺名称',
    supplier_code                 varchar(100) COMMENT '供应商简码',
    supplier_name                 varchar(100) COMMENT '供应商名称',
    is_limited_sale               varchar(100) COMMENT '是否售完即止',
    is_factory_direct             varchar(100) COMMENT '是否厂直',
    nationwide_factory_stock      bigint COMMENT '全国厂直可用库存',
    is_shadow_stock               varchar(20) COMMENT '是否影分身',
    is_virtual_combo              varchar(20) COMMENT '是否虚拟组套',
    is_virtual_category           varchar(20) COMMENT '是否虚拟品类',
    listing_status                varchar(20) COMMENT '上下柜状态',
    listing_date                  date COMMENT '上柜时间',
    is_parallel_stock             varchar(20) COMMENT '是否平行库存',
    is_gift                       varchar(20) COMMENT '是否赠品',
    spu_code                      varchar(100) COMMENT 'SPU编码',
    barcode                       varchar(100) COMMENT '条形码',
    jd_price                      decimal(10, 2) COMMENT '京东价',
    nationwide_purchase_price     decimal(10, 2) COMMENT '全国采购价',
    warehouse_network_type        varchar(50) COMMENT '仓网类型',
    shelf_life                    bigint COMMENT '保质期',
    length                        varchar(50) COMMENT '长度',
    width                         bigint COMMENT '宽度',
    height                        bigint COMMENT '高度',
    weight                        bigint COMMENT '重量',
    nationwide_7day_sale_cnt      varchar(100) COMMENT '全国7日三级销量band',
    nationwide_28day_sale_cnt     varchar(100) COMMENT '全国28日三级销量band',
    rdc                           varchar(100) COMMENT 'RDC',
    distribution_center           varchar(100) COMMENT '配送中心',
    stock                         bigint COMMENT '库存件数',
    in_stock                      bigint COMMENT '现货库存',
    internal_in_transit_stock     bigint COMMENT '内配在途库存',
    internal_in                   bigint COMMENT '内配入',
    internal_out                  bigint COMMENT '内配出',
    locked_stock                  bigint COMMENT '已锁定',
    available_stock               bigint COMMENT '可用库存',
    pending_purchase_stock        bigint COMMENT '采购未到货',
    be_order_stock                bigint COMMENT '可订购库存',
    reserved_stock                bigint COMMENT '订单预定',
    vmi_stock                     bigint COMMENT 'VMI库存',
    unsellable_stock              bigint COMMENT '不可售',
    large_item_7d_cnt             bigint COMMENT '大件7天内待预占数量',
    large_item_8_14d_cnt          bigint COMMENT '大件8-14天待预占数量',
    large_item_15_21d_cnt         bigint COMMENT '大件15-21天待预占数量',
    large_item_22_28d_cnt         bigint COMMENT '大件22-28天待预占数量',
    large_item_28d_cnt            bigint COMMENT '大件28天以上待预占数量',
    last_1d_dispatch_cnt          bigint COMMENT '昨日出库商品件数',
    last_7d_dispatch_cnt          bigint COMMENT '近7日出库商品件数',
    last_14d_dispatch_cnt         bigint COMMENT '近14日出库商品件数',
    last_28d_dispatch_cnt         bigint COMMENT '近28日出库商品件数',
    last_30d_dispatch_cnt         bigint COMMENT '近30日出库商品件数',
    last_60d_dispatch_cnt         bigint COMMENT '近60日出库商品件数',
    last_90d_dispatch_cnt         bigint COMMENT '近90日出库商品件数',
    mtd_dispatch_cnt              bigint COMMENT '月至今出库商品件数',
    last_1d_receipt_cnt           bigint COMMENT '昨日收货地商品件数',
    last_7d_receipt_cnt           bigint COMMENT '近7日收货地商品件数',
    last_14d_receipt_cnt          bigint COMMENT '近14日收货地商品件数',
    last_28d_receipt_cnt          bigint COMMENT '近28日收货地商品件数',
    last_30d_receipt_cnt          bigint COMMENT '近30日收货地商品件数',
    last_60d_receipt_cnt          bigint COMMENT '近60日收货地商品件数',
    last_90d_receipt_cnt          bigint COMMENT '近90日收货地商品件数',
    mtd_receipt_cnt               bigint COMMENT '月至今收货地商品件数',
    last_1d_factory_dispatch_cnt  bigint COMMENT '昨日厂直出库商品件数',
    last_7d_factory_dispatch_cnt  bigint COMMENT '近7日厂直出库商品件数',
    last_14d_factory_dispatch_cnt bigint COMMENT '近14日厂直出库商品件数',
    last_28d_factory_dispatch_cnt bigint COMMENT '近28日厂直出库商品件数',
    last_30d_factory_dispatch_cnt bigint COMMENT '近30日厂直出库商品件数',
    last_60d_factory_dispatch_cnt bigint COMMENT '近60日厂直出库商品件数',
    last_90d_factory_dispatch_cnt bigint COMMENT '近90日厂直出库商品件数',
    mtd_factory_dispatch_cnt      bigint COMMENT '月至今厂直出库商品件数',
    last_1d_vmi_dispatch_cnt      bigint COMMENT '昨日VMI出库商品件数',
    last_7d_vmi_dispatch_cnt      bigint COMMENT '近7日VMI出库商品件数',
    last_14d_vmi_dispatch_cnt     bigint COMMENT '近14日VMI出库商品件数',
    last_28d_vmi_dispatch_cnt     bigint COMMENT '近28日VMI出库商品件数',
    last_30d_vmi_dispatch_cnt     bigint COMMENT '近30日VMI出库商品件数',
    last_60d_vmi_dispatch_cnt     bigint COMMENT '近60日VMI出库商品件数',
    last_90d_vmi_dispatch_cnt     bigint COMMENT '近90日VMI出库商品件数',
    mtd_vmi_dispatch_cnt          bigint COMMENT '月至今VMI出库商品件数',
    available_days_7d             bigint COMMENT '7日有货天数',
    available_days_14d            bigint COMMENT '14日有货天数',
    available_days_28d            bigint COMMENT '28日有货天数',
    available_days_30d            bigint COMMENT '30日有货天数',
    expected_sellable_days double COMMENT '预计可售天数',
    out_of_stock_pv               bigint COMMENT '无货pv',
    mtd_out_of_stock_pv           bigint COMMENT '月至今无货pv',
    in_stock_pv_rate double COMMENT 'PV现货率',
    mtd_in_stock_pv_rate double COMMENT '月至今pv现货率',
    pending_purchase_arrived      bigint COMMENT '采购未到货-已回告',
    pending_purchase_scheduled    bigint COMMENT '采购未到货-已预约',
    last_1d_purchase_in_cnt       bigint COMMENT '昨日采购入库件数',
    last_7d_purchase_in_cnt       bigint COMMENT '近7日采购入库件数',
    last_14d_purchase_in_cnt      bigint COMMENT '近14日采购入库件数',
    last_28d_purchase_in_cnt      bigint COMMENT '近28日采购入库件数',
    last_30d_purchase_in_cnt      bigint COMMENT '近30日采购入库件数',
    mtd_purchase_in_cnt           bigint COMMENT '月至今采购入库件数',
    last_1d_purchase_order_cnt    bigint COMMENT '昨日采购下单件数',
    last_7d_purchase_order_cnt    bigint COMMENT '近7日采购下单件数',
    last_14d_purchase_order_cnt   bigint COMMENT '近14日采购下单件数',
    last_28d_purchase_order_cnt   bigint COMMENT '近28日采购下单件数',
    last_30d_purchase_order_cnt   bigint COMMENT '近30日采购下单件数',
    mtd_purchase_order_cnt        bigint COMMENT '月至今采购下单件数',
    last_1d_return_supplier_cnt   bigint COMMENT '昨日退供应商件数',
    last_7d_return_supplier_cnt   bigint COMMENT '近7日退供应商件数',
    last_14d_return_supplier_cnt  bigint COMMENT '近14日退供应商件数',
    last_28d_return_supplier_cnt  bigint COMMENT '近28日退供应商件数',
    last_30d_return_supplier_cnt  bigint COMMENT '近30日退供应商件数',
    mtd_return_to_supplier_cnt    bigint COMMENT '月至今退供应商件数',
    created_by                    varchar(100) NOT NULL COMMENT '插入人',
    created_at                    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                    varchar(100) COMMENT '更新人',
    updated_at                    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-商品库存表';

CREATE TABLE jd_autarky_consumer_overview
(
    id                             bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                        varchar(100) COMMENT '店铺id',
    biz_day                        date COMMENT '日期',
    category                       varchar(100) COMMENT '类目',
    trans_new_customer_num         bigint COMMENT '新客成交人数',
    trans_old_customer_num         bigint COMMENT '老客成交人数',
    trans_new_customer_amount      decimal(10, 2) COMMENT '新客成交金额',
    trans_old_customer_amount      decimal(10, 2) COMMENT '老客成交金额',
    trans_new_customer_product_cnt bigint COMMENT '新客成交商品件数',
    trans_old_customer_product_cnt bigint COMMENT '老客成交商品件数',
    created_by                     varchar(100) NOT NULL COMMENT '插入人',
    created_at                     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                     varchar(100) COMMENT '更新人',
    updated_at                     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-消费者总览';

CREATE TABLE jd_autarky_return_order
(
    id                      bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                 varchar(100) COMMENT '店铺id',
    shop_name               varchar(100) COMMENT '店铺',
    product_code            varchar(100) COMMENT '商品编号',
    order_code              varchar(100) COMMENT '订单编号',
    order_date              date COMMENT '下单日期',
    completion_date         date COMMENT '完成日期',
    product_cnt             bigint COMMENT '商品数量',
    product_amount          decimal(10, 2) COMMENT '商品金额',
    commission_amount       decimal(10, 2) COMMENT '计佣金额',
    commission              decimal(10, 2) COMMENT '佣金',
    leader_service_fee      decimal(10, 2) COMMENT '团长服务费',
    jd_platform_service_fee decimal(10, 2) COMMENT '京东平台技术服务费',
    total_commission_amount decimal(10, 2) COMMENT '总佣金',
    return_cnt              bigint COMMENT '退货数量',
    refund_amount           decimal(10, 2) COMMENT '返款金额',
    refund_date             date COMMENT '返款日期',
    refund_reason           varchar(100) COMMENT '返款原因',
    plan_or_event           varchar(100) COMMENT '所属计划/活动',
    created_by              varchar(100) NOT NULL COMMENT '插入人',
    created_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by              varchar(100) COMMENT '更新人',
    updated_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-返款订单明细';

CREATE TABLE jd_jtk_product_order
(
    id                      bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                 varchar(100) COMMENT '店铺id',
    shop_name               varchar(100) COMMENT '店铺',
    product_code            varchar(100) COMMENT '商品编号',
    order_code              varchar(100) COMMENT '订单编号',
    order_date              date COMMENT '下单日期',
    order_status            varchar(100) COMMENT '订单状态',
    promoter_pin            varchar(100) COMMENT '推客PIN',
    commission_amount       decimal(10, 2) COMMENT '计佣金额',
    commission              decimal(10, 2) COMMENT '佣金',
    total_commission        decimal(10, 2) COMMENT '总佣金',
    completion_date         varchar(100) COMMENT '完成日期',
    is_valid                varchar(100) COMMENT '是否有效',
    product_quantity        bigint COMMENT '商品数量',
    roi                     decimal(10, 2) COMMENT 'ROI',
    plan_or_event           varchar(100) COMMENT '所属计划/活动',
    jd_platform_service_fee decimal(10, 2) COMMENT '京东平台技术服务费',
    created_by              varchar(100) NOT NULL COMMENT '插入人',
    created_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by              varchar(100) COMMENT '更新人',
    updated_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-京挑客-下单订单明细';

CREATE TABLE jd_autarky_jzt_promotion
(
    id                 bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id            varchar(100) COMMENT '店铺id',
    shop_name          varchar(100) COMMENT '店铺',
    biz_day            date COMMENT '日期',
    product_line       varchar(100) COMMENT '产品线',
    tracking_sku_id    varchar(100) COMMENT '跟单SKU ID',
    total_amount       decimal(10, 2) COMMENT '总费用',
    total_order_amount decimal(10, 2) COMMENT '总订单金额',
    created_by         varchar(100) NOT NULL COMMENT '插入人',
    created_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by         varchar(100) COMMENT '更新人',
    updated_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-京准通-推广费';

CREATE TABLE jd_autarky_product_key_idx
(
    id              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day         date COMMENT '日期',
    sku_id          varchar(255) COMMENT 'SKU ID',
    product_name    varchar(255) COMMENT '商品名称',
    visit_idx double COMMENT '访客指数',
    trans_quantity_idx double COMMENT '成交件数指数',
    trans_amount_idx double COMMENT '成交金额指数',
    add_cart_num    bigint COMMENT '加购人数',
    follow_num      bigint COMMENT '关注人数',
    trans_avg_price decimal(10, 2) COMMENT '成交客单价',
    created_by      varchar(100) NOT NULL COMMENT '插入人',
    created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by      varchar(100) COMMENT '更新人',
    updated_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-商品对比-关键指标';

CREATE TABLE jd_autarky_flow
(
    id                            bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                       date COMMENT '日期',
    secondary_source              varchar(100) COMMENT '二级来源',
    third_source                  varchar(100) COMMENT '三级来源',
    product_visit_idx             varchar(100) COMMENT '本品访客指数',
    product_visit_rate            varchar(100) COMMENT '本品访客数占比',
    product_customer_idx          varchar(100) COMMENT '本品成交客户指数',
    product_trans_amount_idx      varchar(100) COMMENT '本品成交金额指数',
    product_trans_amount_rate     varchar(100) COMMENT '本品成交金额占比',
    competitor1_visit_idx         varchar(100) COMMENT '竞品1访客指数',
    competitor1_visit_rate        varchar(100) COMMENT '竞品1访客数占比',
    competitor1_customer_idx      varchar(100) COMMENT '竞品1成交客户指数',
    competitor1_trans_amount_idx  varchar(100) COMMENT '竞品1成交金额指数',
    competitor1_trans_amount_rate varchar(100) COMMENT '竞品1成交金额占比',
    competitor2_visit_idx         varchar(100) COMMENT '竞品2访客指数',
    competitor2_visit_rate        varchar(100) COMMENT '竞品2访客数占比',
    competitor2_customer_idx      varchar(100) COMMENT '竞品2成交客户指数',
    competitor2_trans_amount_idx  varchar(100) COMMENT '竞品2成交金额指数',
    competitor2_trans_amount_rate varchar(100) COMMENT '竞品2成交金额占比',
    own_sku                       varchar(100) COMMENT '本店 SKU',
    competitor_sku                varchar(100) COMMENT '竞品 SKU',
    created_by                    varchar(100) NOT NULL COMMENT '插入人',
    created_at                    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                    varchar(100) COMMENT '更新人',
    updated_at                    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-自营-商品对比-流量来源';

CREATE TABLE jd_pop_core_idx
(
    id               bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day          date COMMENT '日期',
    shop_id          varchar(100) COMMENT '店铺id',
    shop_name        varchar(100) COMMENT '店铺名称',
    product_name     varchar(100) COMMENT '商品名称',
    trans_cnt        bigint COMMENT '成交单量',
    visit_idx        bigint COMMENT '访客指数',
    trans_amount_idx bigint COMMENT '成交金额指数',
    search_visit_idx bigint COMMENT '搜索访客指数',
    follow_cnt       bigint COMMENT '关注人数',
    add_cart_idx     bigint COMMENT '加购指数',
    own_sku          bigint COMMENT '本店 SKU',
    competitor_sku   bigint COMMENT '竞品 SKU',
    created_by       varchar(100) NOT NULL COMMENT '插入人',
    created_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by       varchar(100) COMMENT '更新人',
    updated_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-POP-竞品对比-核心指标';

CREATE TABLE jd_pop_entry_source
(
    id                           bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                      date COMMENT '日期',
    first_source                 varchar(100) COMMENT '一级来源',
    secondary_source             varchar(100) COMMENT '二级来源',
    tertiary_source              varchar(100) COMMENT '三级来源',
    product_visit_cnt double COMMENT '本店商品访客数',
    product_visit_rate           varchar(100) COMMENT '本店商品访客数占比',
    product_trans_amount_idx     varchar(100) COMMENT '本店商品成交金额指数',
    competitor1_visit_cnt        varchar(100) COMMENT '竞品1访客数',
    competitor1_visit_rate       varchar(100) COMMENT '竞品1访客数占比',
    competitor1_trans_amount_idx varchar(100) COMMENT '竞品1成交金额指数',
    competitor2_visit_cnt        varchar(100) COMMENT '竞品2访客数',
    competitor2_visit_rate       varchar(100) COMMENT '竞品2访客数占比',
    competitor2_trans_amount_idx varchar(100) COMMENT '竞品2成交金额指数',
    own_sku                      bigint COMMENT '本店 SKU',
    competitor_sku               bigint COMMENT '竞品 SKU',
    created_by                   varchar(100) NOT NULL COMMENT '插入人',
    created_at                   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                   varchar(100) COMMENT '更新人',
    updated_at                   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-POP-竞品对比-入店来源';

CREATE TABLE jd_pop_outbound
(
    id                                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                               date COMMENT '日期',
    warehouse_name                        varchar(100) COMMENT '仓库',
    sku                                   varchar(100) COMMENT 'SKU',
    merchant_item_id                      varchar(100) COMMENT '商家商品标识',
    product_name                          varchar(100) COMMENT '商品名称',
    initial_inventory                     bigint COMMENT '期初库存',
    final_inventory                       bigint COMMENT '期末库存',
    initial_transfer_in_transit_inventory bigint COMMENT '期初调拨在途库存',
    final_transfer_in_transit_inventory   bigint COMMENT '期末调拨在途库存',
    total_inbound                         bigint COMMENT '总入库',
    total_outbound                        bigint COMMENT '总出库',
    vmi_adjustment                        bigint COMMENT 'VMI调整',
    other_adjustment                      bigint COMMENT '其他调整',
    purchase_inbound                      bigint COMMENT '采购入库',
    return_inbound                        bigint COMMENT '退货入库',
    transfer_inbound                      bigint COMMENT '调拨入库',
    inventory_gain                        bigint COMMENT '盘盈',
    warehouse_move_in                     bigint COMMENT '搬仓入库',
    spare_parts_to_main_inventory         bigint COMMENT '备件库入大库',
    finished_goods_inbound                bigint COMMENT '加工单成品入库',
    raw_material_rollback_inbound         bigint COMMENT '加工单原料回滚入库',
    owner_adjustment_inbound              bigint COMMENT '货主调整单入库',
    unboxing_inbound                      bigint COMMENT '拆箱单入库',
    sales_outbound                        bigint COMMENT '销售出库',
    return_supplier_outbound              bigint COMMENT '退供出库',
    transfer_outbound                     bigint COMMENT '调拨出库',
    inventory_loss                        bigint COMMENT '盘亏',
    warehouse_move_out                    bigint COMMENT '搬仓出库',
    spare_parts_from_main_inventory       bigint COMMENT '大库出备件库',
    raw_material_deduction_outbound       bigint COMMENT '加工单原料扣减出库',
    consumables_outbound                  bigint COMMENT '耗材出库',
    owner_adjustment_outbound             bigint COMMENT '货主调整单出库',
    unboxing_outbound                     bigint COMMENT '拆箱单出库',
    created_by                            varchar(100) NOT NULL COMMENT '插入人',
    created_at                            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                            varchar(100) COMMENT '更新人',
    updated_at                            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-POP-出库明细表';

CREATE TABLE jd_pop_stock
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day               date COMMENT '日期',
    sequence_number       bigint COMMENT '序号',
    warehouse_name        varchar(100) COMMENT '仓库名称',
    warehouse_code        bigint COMMENT '仓库编码',
    division_product_code varchar(100) COMMENT '事业部商品编码',
    division_product_name varchar(100) COMMENT '事业部商品名称',
    merchant_product_code varchar(100) COMMENT '商家商品编码',
    merchant_product_id   varchar(255) COMMENT '商家商品标识',
    stock_status          varchar(100) COMMENT '库存状态',
    product_grade_code    bigint COMMENT '商品等级编码',
    stock_type            varchar(100) COMMENT '库存类型',
    total_stock           bigint COMMENT '总库存',
    available_stock       bigint COMMENT '可用库存',
    division_code         varchar(100) COMMENT '事业部编码',
    division_name         varchar(100) COMMENT '事业部名称',
    unit_of_measurement   varchar(50) COMMENT '计量单位',
    style_number          varchar(50) COMMENT '款号',
    color                 varchar(50) COMMENT '颜色',
    size                  varchar(50) COMMENT '尺寸',
    season                varchar(50) COMMENT '季节',
    year                  varchar(50) COMMENT '年份',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-POP-库存表';


CREATE TABLE rpa_data.jd_jm_product
(
    id         bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id    varchar COMMENT '店铺id',
    shop_name  varchar COMMENT '店铺名称',
    product_id varchar COMMENT '商品编码',
    good_no    varchar COMMENT '货号',
    good_name  varchar COMMENT '商品名称',
    bar_code   varchar COMMENT '条形码',
    created_by varchar   NOT NULL COMMENT '插入人',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by varchar COMMENT '更新人',
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='京东-京麦-商品详情';


CREATE TABLE rpa_data.jd_performance_product
(
    id              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id         VARCHAR COMMENT '店铺ID',
    shop_name       VARCHAR COMMENT '店铺名称',
    biz_day         DATE COMMENT '销售日期',
    product_name    VARCHAR COMMENT '商品名称',
    sku             BIGINT COMMENT '商品SKU编码',
    brand           VARCHAR COMMENT '品牌',
    category_level1 VARCHAR COMMENT '一级类目',
    category_level2 VARCHAR COMMENT '二级类目',
    category_level3 VARCHAR COMMENT '三级类目',
    supplier_code   VARCHAR COMMENT '供应商简码',
    sales_quantity  DECIMAL(10, 2) COMMENT '财务销量',
    created_by      varchar COMMENT '插入人',
    created_at      timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by      varchar COMMENT '更新人',
    updated_at      timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='京东-业绩-商品明细报表';


select '海豚智投-短视频-财务报表',
       'htzt_finance',
       COLUMN_NAME,
       DATA_TYPE,
       COLUMN_COMMENT,
       CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'htzt_finance';

