#*********************************** 快手 ***********************************
CREATE TABLE ks_aftersales_bulk_export
(
    id                         bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                    varchar(100) COMMENT '店铺id',
    order_no                   bigint       NOT NULL COMMENT '订单编号',
    order_status               varchar(50) COMMENT '订单状态',
    order_create_time          datetime COMMENT '订单创建时间',
    actual_payment             varchar(50) COMMENT '实付款',
    shipping_fee               varchar(50) COMMENT '快递费',
    merchant_receipt           varchar(50) COMMENT '商家实收金额',
    product_id                 bigint COMMENT '商品ID',
    product_name               varchar(255) COMMENT '商品名称',
    buyer_id                   bigint COMMENT '买家ID',
    buyer_nick                 varchar(255) COMMENT '买家昵称',
    aftersales_no              bigint COMMENT '售后单号',
    aftersales_status          varchar(50) COMMENT '售后状态',
    aftersales_request_time    datetime COMMENT '售后申请时间',
    aftersales_type            varchar(50) COMMENT '售后类型',
    aftersales_reason          varchar(255) COMMENT '售后原因',
    request_description        varchar(500) COMMENT '申请描述',
    refund_amount              varchar(50) COMMENT '退款金额',
    return_shipping_no         varchar(50) COMMENT '退货物流单号',
    aftersales_completion_time datetime COMMENT '售后完结时间',
    is_atom_processed          varchar(50) COMMENT '是否ATOM处理',
    created_by                 varchar(100) NOT NULL COMMENT '插入人',
    created_at                 timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                 varchar(100) COMMENT '更新人',
    updated_at                 timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='快手售后单批量导出';

CREATE TABLE ks_est_commission
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id               varchar(100) COMMENT '店铺id',
    biz_day               date COMMENT '日期',
    page_views            int COMMENT 'PV (页面浏览量)',
    unique_visitors       int COMMENT 'UV (独立访客数)',
    payment_count         int COMMENT '支付笔数',
    payment_gmv           decimal(15, 2) COMMENT '支付GMV',
    commission_rate       decimal(5, 2) COMMENT '佣金比例',
    estimated_commission  decimal(10, 2) COMMENT '预估佣金',
    technical_service_fee decimal(10, 2) COMMENT '技术服务费',
    product_id            bigint COMMENT '商品ID',
    product_name          varchar(255) COMMENT '商品名称',
    influencer_id         bigint COMMENT '达人ID',
    influencer_nickname   varchar(100) COMMENT '达人昵称',
    plan_type             varchar(50) COMMENT '计划类型',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='快手预估佣金';

CREATE TABLE ks_e_niu_agent_summary_total_cost
(
    id         bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day    date COMMENT '日期',
    agent_id   int COMMENT '代理商ID(店铺ID)',
    account_id bigint COMMENT '账号ID',
    agent_name varchar(255) COMMENT '代理商名称',
    total_cost decimal(10, 3) COMMENT '总花费',
    created_by varchar(100) NOT NULL COMMENT '插入人',
    created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by varchar(100) COMMENT '更新人',
    updated_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='营销总览-磁力金牛-账户明细';

CREATE TABLE ks_e_niu_financial_transactions
(
    id                        bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                   date COMMENT '日期',
    account_ks_id             bigint COMMENT '账户快手ID',
    ad_account_id             bigint COMMENT '广告主账户ID(店铺ID)',
    campaign_cost             decimal(10, 3) COMMENT '计划花费',
    recharge_cost             decimal(10, 3) COMMENT '充值花费',
    frame_return_cost         decimal(10, 3) COMMENT '框返花费',
    incentive_cost            decimal(10, 3) COMMENT '激励花费',
    ecomm_cost                decimal(10, 3) COMMENT '电商花费',
    recharge_transfer_in      decimal(10, 3) COMMENT '充值转入',
    frame_return_transfer_in  decimal(10, 3) COMMENT '框返转入',
    incentive_transfer_in     decimal(10, 3) COMMENT '激励转入',
    ecomm_transfer_in         decimal(10, 3) COMMENT '电商转入',
    total_transfer_in         decimal(10, 3) COMMENT '总转入',
    recharge_transfer_out     decimal(10, 3) COMMENT '充值转出',
    frame_return_transfer_out decimal(10, 3) COMMENT '框返转出',
    incentive_transfer_out    decimal(10, 3) COMMENT '激励转出',
    ecomm_transfer_out        decimal(10, 3) COMMENT '电商转出',
    total_transfer_out        decimal(10, 3) COMMENT '总转出',
    order_payment             decimal(10, 3) COMMENT '订单支付',
    order_refund              decimal(10, 3) COMMENT '订单退款',
    brand_payment             decimal(10, 3) COMMENT '品牌支付',
    brand_refund              decimal(10, 3) COMMENT '品牌退款',
    end_of_day_balance        decimal(10, 3) COMMENT '日终结余',
    created_by                varchar(100) NOT NULL COMMENT '插入人',
    created_at                timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                varchar(100) COMMENT '更新人',
    updated_at                timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='磁力金牛-财务流水';

CREATE TABLE ks_mkt_ovw_e_niu_acc_details
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) COMMENT '店铺id',
    ad_account           int COMMENT '广告账号',
    promotion_type       varchar(50) COMMENT '推广类型',
    cost                 decimal(10, 2) COMMENT '花费',
    direct_gmv           decimal(15, 2) COMMENT '直接GMV',
    daily_gmv            decimal(15, 2) COMMENT '当日累计GMV',
    post_1_day_gmv       decimal(15, 2) COMMENT '投后1日累计GMV',
    post_3_days_gmv      decimal(15, 2) COMMENT '投后3日累计GMV',
    post_7_days_gmv      decimal(15, 2) COMMENT '投后7日累计GMV',
    post_15_days_gmv     decimal(15, 2) COMMENT '投后15日累计GMV',
    post_30_days_gmv     decimal(15, 2) COMMENT '投后30日累计GMV',
    direct_roi           decimal(5, 2) COMMENT '直接ROI',
    daily_roi            decimal(5, 2) COMMENT '当日累计ROI',
    post_1_day_roi       decimal(5, 2) COMMENT '投后1日累计ROI',
    post_3_days_roi      decimal(5, 2) COMMENT '投后3日累计ROI',
    post_7_days_roi      decimal(5, 2) COMMENT '投后7日累计ROI',
    post_15_days_roi     decimal(5, 2) COMMENT '投后15日累计ROI',
    post_30_days_roi     decimal(5, 2) COMMENT '投后30日累计ROI',
    direct_orders        int COMMENT '直接成交订单量',
    daily_orders         int COMMENT '当日累计成交订单量',
    post_1_day_orders    int COMMENT '投后1日累计成交订单量',
    post_3_days_orders   int COMMENT '投后3日累计成交订单量',
    post_7_days_orders   int COMMENT '投后7日累计成交订单量',
    post_15_days_orders  int COMMENT '投后15日累计成交订单量',
    post_30_days_orders  int COMMENT '投后30日累计成交订单量',
    cover_impressions    int COMMENT '封面曝光数',
    cover_clicks         int COMMENT '封面点击数',
    impressions          int COMMENT '曝光数',
    plays                int COMMENT '播放数',
    new_followers        int COMMENT '涨粉数',
    live_room_entries    int COMMENT '直播间进人',
    creative_impressions int COMMENT '素材曝光数',
    biz_day              date         NOT NULL COMMENT '日期',
    shop_name            varchar(255) COMMENT '店铺',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='营销总览-磁力金牛-账户明细';

CREATE TABLE ks_operating_data
(
    id                       bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                  varchar(100) COMMENT '店铺id',
    shop_name                varchar(255) COMMENT '店铺',
    biz_day                  date COMMENT '日期',
    product_views            int COMMENT '商品浏览量',
    product_visitors         int COMMENT '商品访客数',
    total_orderers           int COMMENT '累计下单人数',
    total_orders             int COMMENT '累计下单订单数',
    total_order_amount       decimal(10, 2) COMMENT '累计下单金额',
    total_buyers             int COMMENT '累计成交人数',
    total_sales_orders       int COMMENT '累计成交订单数',
    total_sales_amount       decimal(10, 2) COMMENT '累计成交金额',
    paid_items               int COMMENT '支付件数',
    self_build_self_sell     decimal(10, 2) COMMENT '自建商品自卖',
    self_build_distributed   decimal(10, 2) COMMENT '自建商品被分销',
    fast_distribution        int COMMENT '快分销（原好物联盟）商品',
    third_party_products     int COMMENT '第三方商品',
    refund_amount            decimal(10, 2) COMMENT '退款金额（元）',
    refund_order_count       bigint COMMENT '退款订单数',
    refund_goods_amount      decimal(10, 2) COMMENT '退货退款金额',
    refund_goods_order_count bigint COMMENT '退货退款订单数',
    real_cost                decimal(10, 2) COMMENT '花费(非全站推广)',
    real_cost_full           varchar(20) COMMENT '花费(全站推广)',
    created_by               varchar(100) NOT NULL COMMENT '插入人',
    created_at               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by               varchar(100) COMMENT '更新人',
    updated_at               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    pay_order_amount_all     decimal(10, 2) COMMENT '全店累计成交金额',
    PRIMARY KEY (id)
) COMMENT ='快手-经营数据';

CREATE TABLE ks_order_bulk_export
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id               varchar(100) COMMENT '店铺id',
    order_no              bigint COMMENT '订单号',
    order_create_time     datetime COMMENT '订单创建时间',
    order_pay_time        datetime COMMENT '订单支付时间',
    presale_deposit_time  varchar(50) COMMENT '预售定金支付时间',
    order_status          varchar(50) COMMENT '订单状态',
    actual_payment        varchar(50) COMMENT '实付款',
    shipping_fee          varchar(50) COMMENT '快递费',
    channel               varchar(50) COMMENT '渠道',
    pay_method            varchar(50) COMMENT '支付方式',
    quantity              int COMMENT '成交数量',
    buyer_message         varchar(500) COMMENT '买家留言',
    account_type          varchar(50) COMMENT '账号类型',
    account_details       varchar(500) COMMENT '账号明细',
    order_notes           varchar(500) COMMENT '订单备注',
    refund                varchar(50) COMMENT '退货退款',
    activity_order        varchar(50) COMMENT '活动订单',
    presale_delivery_time datetime COMMENT '预售/承诺发货时间',
    product_name          varchar(255) COMMENT '商品名称',
    product_id            bigint COMMENT '商品ID',
    product_spec          varchar(255) COMMENT '商品规格',
    sku_code              varchar(255) COMMENT 'SKU编码',
    unit_price            varchar(50) COMMENT '商品单价',
    cps_influencer_id     bigint COMMENT 'CPS达人ID',
    cps_influencer_nick   varchar(255) COMMENT 'CPS达人昵称',
    est_promotion_comm    decimal(10, 2) COMMENT '预估推广佣金',
    est_promoter_rate     varchar(50) COMMENT '预估推广者分佣比例',
    recipient_name        varchar(255) COMMENT '收货人姓名',
    recipient_phone       varchar(20) COMMENT '收货人电话',
    recipient_province    varchar(100) COMMENT '收货地址-省',
    recipient_city        varchar(100) COMMENT '收货地址-市',
    recipient_district    varchar(100) COMMENT '收货地址-区',
    recipient_street      varchar(255) COMMENT '收货地址-街道',
    recipient_address     varchar(100) COMMENT '收货地址',
    shipping_company      varchar(100) COMMENT '快递公司',
    tracking_no           varchar(255) COMMENT '快递单号',
    logistics_info        varchar(50) COMMENT '物流信息',
    real_name             varchar(255) COMMENT '实名姓名',
    id_number             varchar(20) COMMENT '身份证号',
    store_id              varchar(20) COMMENT '门店ID',
    store_name            varchar(255) COMMENT '门店名称',
    store_address         varchar(255) COMMENT '门店地址',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='快手订单批量导出';

CREATE TABLE ks_short_video_prod_report
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) COMMENT '店铺id',
    product_id           bigint COMMENT '商品ID',
    product_name         varchar(255) COMMENT '商品名称',
    product_image_url    varchar(512) COMMENT '商品主图',
    spend                decimal(10, 2) COMMENT '花费(元)',
    impressions double COMMENT '曝光数',
    cpm                  decimal(10, 2) COMMENT '平均千次广告曝光花费',
    product_visits double COMMENT '商品访问数',
    gmv                  decimal(15, 2) COMMENT 'GMV（总交易额）',
    roi                  decimal(5, 2) COMMENT 'ROI（投资回报率）',
    orders_paid double COMMENT '订单支付数',
    order_cost           decimal(10, 2) COMMENT '商品订单成本',
    aov                  decimal(10, 2) COMMENT '单均价',
    daily_cumulative_gmv decimal(15, 2) COMMENT '当日累计GMV',
    t0_roi               decimal(10, 6) COMMENT 't0Roi',
    daily_cumulative_orders double NOT NULL COMMENT '当日累计订单数',
    biz_day              date COMMENT '日期',
    account_id           bigint       NOT NULL COMMENT '账户ID',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='短视频推广-商品报表';



select '海豚智投-短视频-财务报表',
       'htzt_finance',
       COLUMN_NAME,
       DATA_TYPE,
       COLUMN_COMMENT,
       CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'htzt_finance';

