#*********************************** 其它 ***********************************

CREATE TABLE mx_ai_inventory_marketing_order
(
    id                        bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                   varchar(100) COMMENT '店铺id',
    settlement_subject        varchar(50) COMMENT '结算科目',
    payment_type              varchar(50) COMMENT '收付类型',
    activity_number           bigint COMMENT '活动编号',
    activity_name             varchar(255) COMMENT '活动名称',
    ad_order_number           varchar(50) COMMENT 'AD单号',
    secondary_order_number    varchar(50) COMMENT '二级订单号',
    tertiary_order_number     varchar(50) COMMENT '三级订单号',
    product_name              varchar(100) COMMENT '商品名称',
    product_quantity          int COMMENT '商品件数',
    product_number            bigint COMMENT '商品编号',
    barcode                   varchar(50) COMMENT '条码',
    item_number               varchar(50) COMMENT '款号',
    settlement_amount         decimal(10, 2) COMMENT '结算金额',
    sales_price               decimal(10, 2) COMMENT '销售价格',
    marketing_promotition_fee decimal(10, 2) COMMENT '市场推广费',
    actual_payment            decimal(10, 2) COMMENT '实付金额',
    operating_sale_fee        decimal(10, 2) COMMENT '营销费用',
    high_commission_fee       decimal(10, 2) COMMENT '高佣费用',
    low_price_fee             decimal(10, 2) COMMENT '低价费用',
    coupon_fee                decimal(10, 2) COMMENT '优惠券费用',
    transaction_time          datetime COMMENT '业务发生时间',
    is_settled                varchar(50) COMMENT '是否出账',
    expected_settle_time      datetime COMMENT '预计出账时间',
    recon_no                  varchar(255) COMMENT '对账单号',
    billing_date              date COMMENT '账单日',
    created_by                varchar(100) NOT NULL COMMENT '插入人',
    created_at                timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                varchar(100) COMMENT '更新人',
    updated_at                timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='爱库存营销费用&订单货款';

CREATE TABLE mx_funds_account_transactions
(
    id                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id           varchar(100) COMMENT '店铺id',
    source_order_no   varchar(50) COMMENT '来源单号',
    transaction_type  varchar(50) COMMENT '交易类型',
    settlement_amount decimal(10, 2) COMMENT '结算金额(元)',
    settlement_date   datetime COMMENT '结算日期',
    created_by        varchar(100) NOT NULL COMMENT '插入人',
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by        varchar(100) COMMENT '更新人',
    updated_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='梦饷家-资金-账户收支';

CREATE TABLE rpa_data.rdy_order_info
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                         VARCHAR COMMENT '店铺ID',
    shop_name                      VARCHAR(200) COMMENT '店铺名称',
    order_id                        VARCHAR(50) COMMENT '订单号',
    product_name                    VARCHAR(255) COMMENT '商品名称',
    product_id                      VARCHAR(50) COMMENT '商品id',
    spec_info                       VARCHAR(500) COMMENT '规格信息',
    product_quantity                INT COMMENT '商品数量',
    product_tags                    VARCHAR(500) COMMENT '商品标签',
    external_shipping_code          VARCHAR(100) COMMENT '外部发货编码',
    actual_receipt                  DECIMAL(10, 2) COMMENT '实收款',
    single_product_payment          DECIMAL(10, 2) COMMENT '单商品实付金额',
    actual_payment                  DECIMAL(10, 2) COMMENT '实付金额',
    shipping_fee                    DECIMAL(10, 2) COMMENT '运费',
    tech_service_fee                DECIMAL(10, 2) COMMENT '技术服务费',
    order_status                    VARCHAR(50) COMMENT '订单状态',
    order_time                      DATETIME COMMENT '下单时间',
    payment_time                    DATETIME COMMENT '付款时间',
    shipping_time                   DATETIME COMMENT '发货时间',
    order_channel                   VARCHAR(100) COMMENT '出单渠道',
    live_stream_type                VARCHAR(100) COMMENT '带货类型',
    influencer_nickname             VARCHAR(200) COMMENT '达人昵称',
    video_account_id                VARCHAR(100) COMMENT '视频号id',
    influencer_tags                 VARCHAR(500) COMMENT '达人标签',
    estimated_commission            DECIMAL(10, 2) COMMENT '预估佣金/元',
    actual_commission               DECIMAL(10, 2) COMMENT '实际佣金/元',
    team_leader_id                  VARCHAR(50) COMMENT '团长ID',
    team_leader_name                VARCHAR(200) COMMENT '团长名称',
    estimated_service_fee           DECIMAL(10, 2) COMMENT '预估服务费/元',
    settled_service_fee             DECIMAL(10, 2) COMMENT '结算服务费/元',
    attribution_type                VARCHAR(100) COMMENT '归属类型',
    attribution_time                DATETIME COMMENT '归属时间',
    attribution_influencer_operator VARCHAR(200) COMMENT '归属达人运营',
    employee_bonus_base             DECIMAL(10, 2) COMMENT '员工提成基数/元',
    employee_bonus_rate             DECIMAL(5, 2) COMMENT '员工提成比例/%',
    employee_bonus                  DECIMAL(10, 2) COMMENT '员工提成/元',
    department                      VARCHAR(200) COMMENT '归属部门',
    department_bonus_base           DECIMAL(10, 2) COMMENT '部门提成基数/元',
    management_bonus_rate           DECIMAL(5, 2) COMMENT '管理提成比例/%',
    management_bonus                DECIMAL(10, 2) COMMENT '管理提成/元',
    created_by                      varchar COMMENT '插入人',
    created_at                      timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar COMMENT '更新人',
    updated_at                      timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='热度云-订单-视频号-订单查询';

CREATE TABLE rpa_data.htzt_finance
(
    id                         bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                    VARCHAR COMMENT '店铺ID',
    stat_date                  DATE COMMENT '日期',
    plan_count                 INT COMMENT '计划数',
    approved_plan_count        INT COMMENT '过审计划数',
    real_occupied_funds        DECIMAL(15, 2) COMMENT '真实占用资金',
    total_consumption          DECIMAL(15, 2) COMMENT '累计消耗金额',
    order_count                INT COMMENT '成交订单数',
    order_amount               DECIMAL(15, 2) COMMENT '成交金额（元）',
    order_roi                  DECIMAL(8, 4) COMMENT '成交ROI',
    compensation_roi           DECIMAL(8, 4) COMMENT '赔付ROI',
    wechat_beans_payment       DECIMAL(15, 2) COMMENT '微信豆支付金额',
    wechat_beans_refund        DECIMAL(15, 2) COMMENT '退回微信豆金额',
    wechat_beans_consumption   DECIMAL(15, 2) COMMENT '消耗微信豆金额',
    coupon_deduction_amount    DECIMAL(15, 2) COMMENT '优惠券抵扣金额',
    coupon_refund_amount       DECIMAL(15, 2) COMMENT '退回优惠券金额',
    coupon_consumption_amount  DECIMAL(15, 2) COMMENT '消耗优惠券金额',
    compensation_coupon_amount DECIMAL(15, 2) COMMENT '赔付优惠券金额',
    view_count                 INT COMMENT '浏览数',
    like_count                 INT COMMENT '点赞数',
    comment_count              INT COMMENT '评论数',
    share_count                INT COMMENT '转发数',
    follow_count               INT COMMENT '关注数',
    product_click_count        INT COMMENT '商品点击数',
    conversion_cost            DECIMAL(10, 4) COMMENT '转换成本',
    click_cost                 DECIMAL(10, 4) COMMENT '点击成本',
    click_rate                 DECIMAL(8, 4) COMMENT '点击率',
    click_conversion_rate      DECIMAL(8, 4) COMMENT '点击成交率',
    cpm                        DECIMAL(10, 4) COMMENT '千次展现成本',
    follow_cost                DECIMAL(10, 4) COMMENT '关注成本',
    live_booking_count         INT COMMENT '直播预约人数',
    live_booking_cost          DECIMAL(10, 4) COMMENT '直播预约成本',
    created_by                 varchar COMMENT '插入人',
    created_at                 timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                 varchar COMMENT '更新人',
    updated_at                 timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='海豚智投-短视频-财务报表';



select '海豚智投-短视频-财务报表',
       'htzt_finance',
       COLUMN_NAME,
       DATA_TYPE,
       COLUMN_COMMENT,
       CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'htzt_finance';

