#
*********************************** 淘宝平台 ***********************************
CREATE TABLE tb_gh_product_promotion
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    main_order_id        VARCHAR COMMENT '淘宝主订单号',
    sub_order_id         VARCHAR UNIQUE COMMENT '淘宝子订单号',
    product_name         VARCHAR COMMENT '商品名称',
    product_id           VARCHAR COMMENT '商品ID',
    influencer_name      VARCHAR COMMENT '达人昵称',
    content_id           VARCHAR COMMENT '内容ID',
    order_create_time    DATETIME COMMENT '订单创建时间',
    order_pay_time       DATETIME COMMENT '订单支付时间',
    order_complete_time  DATETIME COMMENT '订单完结时间',
    order_status         VARCHAR COMMENT '订单状态',
    commission_amount    DECIMAL(10, 2) COMMENT '计佣金额',
    refund_amount        DECIMAL(10, 2) COMMENT '订单退款金额',
    estimated_commission DECIMAL(10, 2) COMMENT '预估佣金',
    group_leader_id      VARCHAR COMMENT '团长id',
    service_rate         DECIMAL(5, 2) COMMENT '服务费率(%)',
    service_fee          DECIMAL(10, 2) COMMENT '服务费金额',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-光合商品佣金推广';


CREATE TABLE tb_master_scenarios
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                         varchar(100) COMMENT '店铺id',
    biz_day                         DATE COMMENT '日期',
    scene_id                        BIGINT COMMENT '场景ID',
    scene_name                      VARCHAR(255) COMMENT '场景名字',
    original_secondary_scene_id     BIGINT COMMENT '原二级场景ID',
    original_secondary_scene_name   VARCHAR(255) COMMENT '原二级场景名字',
    plan_id                         BIGINT COMMENT '计划ID',
    plan_name                       VARCHAR(255) COMMENT '计划名字',
    subject_id                      BIGINT COMMENT '主体ID',
    subject_type                    VARCHAR(255) COMMENT '主体类型',
    subject_name                    VARCHAR(255) COMMENT '主体名称',
    impressions                     INT COMMENT '展现量',
    clicks                          INT COMMENT '点击量',
    cost                            DECIMAL(10, 2) COMMENT '花费',
    click_rate                      DECIMAL(5, 2) COMMENT '点击率',
    avg_click_cost                  DECIMAL(10, 2) COMMENT '平均点击花费',
    cpm                             DECIMAL(10, 2) COMMENT '千次展现花费',
    total_pre_sale_amount           DECIMAL(10, 2) COMMENT '总预售成交金额',
    total_pre_sale_orders           INT COMMENT '总预售成交笔数',
    direct_pre_sale_amount          DECIMAL(10, 2) COMMENT '直接预售成交金额',
    direct_pre_sale_orders          INT COMMENT '直接预售成交笔数',
    indirect_pre_sale_amount        DECIMAL(10, 2) COMMENT '间接预售成交金额',
    indirect_pre_sale_orders        INT COMMENT '间接预售成交笔数',
    direct_sale_amount              DECIMAL(10, 2) COMMENT '直接成交金额',
    indirect_sale_amount            DECIMAL(10, 2) COMMENT '间接成交金额',
    total_sale_amount               DECIMAL(10, 2) COMMENT '总成交金额',
    total_sale_orders               INT COMMENT '总成交笔数',
    direct_sale_orders              INT COMMENT '直接成交笔数',
    indirect_sale_orders            INT COMMENT '间接成交笔数',
    conversion_rate                 DECIMAL(5, 2) COMMENT '点击转化率',
    roi                             DECIMAL(5, 2) COMMENT '投入产出比',
    total_transaction_cost          DECIMAL(10, 2) COMMENT '总成交成本',
    total_cart_additions            INT COMMENT '总购物车数',
    direct_cart_additions           INT COMMENT '直接购物车数',
    indirect_cart_additions         INT COMMENT '间接购物车数',
    cart_rate                       DECIMAL(5, 2) COMMENT '加购率',
    favorite_products               INT COMMENT '收藏宝贝数',
    favorite_stores                 INT COMMENT '收藏店铺数',
    store_favorite_cost             DECIMAL(10, 2) COMMENT '店铺收藏成本',
    total_favorites_and_cart        INT COMMENT '总收藏加购数',
    total_favorites_and_cart_cost   DECIMAL(10, 2) COMMENT '总收藏加购成本',
    product_favorites_and_cart      INT COMMENT '宝贝收藏加购数',
    product_favorites_and_cart_cost DECIMAL(10, 2) COMMENT '宝贝收藏加购成本',
    total_favorites                 INT COMMENT '总收藏数',
    product_favorite_cost           DECIMAL(10, 2) COMMENT '宝贝收藏成本',
    product_favorite_rate           DECIMAL(5, 2) COMMENT '宝贝收藏率',
    cart_cost                       DECIMAL(10, 2) COMMENT '加购成本',
    placed_orders                   INT COMMENT '拍下订单笔数',
    placed_order_amount             DECIMAL(10, 2) COMMENT '拍下订单金额',
    direct_favorite_products        INT COMMENT '直接收藏宝贝数',
    indirect_favorite_products      INT COMMENT '间接收藏宝贝数',
    coupon_claims                   INT COMMENT '优惠券领取量',
    shopping_gold_recharges         INT COMMENT '购物金充值笔数',
    shopping_gold_amount            DECIMAL(10, 2) COMMENT '购物金充值金额',
    ww_consultations                INT COMMENT '旺旺咨询量',
    guided_visits                   INT COMMENT '引导访问量',
    guided_visitors                 INT COMMENT '引导访问人数',
    guided_potential_customers      INT COMMENT '引导访问潜客数',
    guided_potential_customer_rate  DECIMAL(5, 2) COMMENT '引导访问潜客占比',
    membership_rate                 DECIMAL(5, 2) COMMENT '入会率',
    membership_count                INT COMMENT '入会量',
    guided_visit_rate               DECIMAL(5, 2) COMMENT '引导访问率',
    deep_visits                     INT COMMENT '深度访问量',
    avg_page_views                  DECIMAL(5, 2) COMMENT '平均访问页面数',
    new_customers                   INT COMMENT '成交新客数',
    new_customer_rate               DECIMAL(5, 2) COMMENT '成交新客占比',
    first_purchase_members          INT COMMENT '会员首购人数',
    member_transaction_amount       DECIMAL(10, 2) COMMENT '会员成交金额',
    member_transaction_orders       INT COMMENT '会员成交笔数',
    total_buyers                    INT COMMENT '成交人数',
    avg_orders_per_buyer            DECIMAL(5, 2) COMMENT '人均成交笔数',
    avg_transaction_amount          DECIMAL(10, 2) COMMENT '人均成交金额',
    organic_conversion_amount       DECIMAL(10, 2) COMMENT '自然流量转化金额',
    organic_impressions             INT COMMENT '自然流量曝光量',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-主体数据明细';

CREATE TABLE tb_plan_scenarios
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                         varchar(100) COMMENT '店铺id',
    biz_day                         DATE COMMENT '日期',
    scene_id                        BIGINT COMMENT '场景ID',
    scene_name                      VARCHAR(255) COMMENT '场景名字',
    original_secondary_scene_id     BIGINT COMMENT '原二级场景ID',
    original_secondary_scene_name   VARCHAR(255) COMMENT '原二级场景名字',
    plan_id                         BIGINT COMMENT '计划ID',
    plan_name                       VARCHAR(255) COMMENT '计划名字',
    impressions                     INT COMMENT '展现量',
    clicks                          INT COMMENT '点击量',
    cost                            DECIMAL(10, 2) COMMENT '花费',
    click_rate                      DECIMAL(5, 2) COMMENT '点击率',
    avg_click_cost                  DECIMAL(10, 2) COMMENT '平均点击花费',
    cpm                             DECIMAL(10, 2) COMMENT '千次展现花费',
    total_pre_sale_amount           DECIMAL(10, 2) COMMENT '总预售成交金额',
    total_pre_sale_orders           INT COMMENT '总预售成交笔数',
    direct_pre_sale_amount          DECIMAL(10, 2) COMMENT '直接预售成交金额',
    direct_pre_sale_orders          INT COMMENT '直接预售成交笔数',
    indirect_pre_sale_amount        DECIMAL(10, 2) COMMENT '间接预售成交金额',
    indirect_pre_sale_orders        INT COMMENT '间接预售成交笔数',
    direct_sale_amount              DECIMAL(10, 2) COMMENT '直接成交金额',
    indirect_sale_amount            DECIMAL(10, 2) COMMENT '间接成交金额',
    total_sale_amount               DECIMAL(10, 2) COMMENT '总成交金额',
    total_sale_orders               INT COMMENT '总成交笔数',
    direct_sale_orders              INT COMMENT '直接成交笔数',
    indirect_sale_orders            INT COMMENT '间接成交笔数',
    conversion_rate                 DECIMAL(5, 2) COMMENT '点击转化率',
    roi                             DECIMAL(5, 2) COMMENT '投入产出比',
    total_transaction_cost          DECIMAL(10, 2) COMMENT '总成交成本',
    total_cart_additions            INT COMMENT '总购物车数',
    direct_cart_additions           INT COMMENT '直接购物车数',
    indirect_cart_additions         INT COMMENT '间接购物车数',
    cart_rate                       DECIMAL(5, 2) COMMENT '加购率',
    favorite_products               INT COMMENT '收藏宝贝数',
    favorite_stores                 INT COMMENT '收藏店铺数',
    store_favorite_cost             DECIMAL(10, 2) COMMENT '店铺收藏成本',
    total_favorites_and_cart        INT COMMENT '总收藏加购数',
    total_favorites_and_cart_cost   DECIMAL(10, 2) COMMENT '总收藏加购成本',
    product_favorites_and_cart      INT COMMENT '宝贝收藏加购数',
    product_favorites_and_cart_cost DECIMAL(10, 2) COMMENT '宝贝收藏加购成本',
    total_favorites                 INT COMMENT '总收藏数',
    product_favorite_cost           DECIMAL(10, 2) COMMENT '宝贝收藏成本',
    product_favorite_rate           DECIMAL(5, 2) COMMENT '宝贝收藏率',
    cart_cost                       DECIMAL(10, 2) COMMENT '加购成本',
    placed_orders                   INT COMMENT '拍下订单笔数',
    placed_order_amount             DECIMAL(10, 2) COMMENT '拍下订单金额',
    direct_favorite_products        INT COMMENT '直接收藏宝贝数',
    indirect_favorite_products      INT COMMENT '间接收藏宝贝数',
    coupon_claims                   INT COMMENT '优惠券领取量',
    shopping_gold_recharges         INT COMMENT '购物金充值笔数',
    shopping_gold_amount            DECIMAL(10, 2) COMMENT '购物金充值金额',
    ww_consultations                INT COMMENT '旺旺咨询量',
    guided_visits                   INT COMMENT '引导访问量',
    guided_visitors                 INT COMMENT '引导访问人数',
    guided_potential_customers      INT COMMENT '引导访问潜客数',
    guided_potential_customer_rate  DECIMAL(5, 2) COMMENT '引导访问潜客占比',
    membership_rate                 DECIMAL(5, 2) COMMENT '入会率',
    membership_count                INT COMMENT '入会量',
    guided_visit_rate               DECIMAL(5, 2) COMMENT '引导访问率',
    deep_visits                     INT COMMENT '深度访问量',
    avg_page_views                  DECIMAL(5, 2) COMMENT '平均访问页面数',
    new_customers                   INT COMMENT '成交新客数',
    new_customer_rate               DECIMAL(5, 2) COMMENT '成交新客占比',
    first_purchase_members          INT COMMENT '会员首购人数',
    member_transaction_amount       DECIMAL(10, 2) COMMENT '会员成交金额',
    member_transaction_orders       INT COMMENT '会员成交笔数',
    total_buyers                    INT COMMENT '成交人数',
    avg_orders_per_buyer            DECIMAL(5, 2) COMMENT '人均成交笔数',
    avg_transaction_amount          DECIMAL(10, 2) COMMENT '人均成交金额',
    organic_conversion_amount       DECIMAL(10, 2) COMMENT '自然流量转化金额',
    organic_impressions             INT COMMENT '自然流量曝光量',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-计划数据明细';

CREATE TABLE tb_product_analysis
(
    id                                 bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                            varchar(100) COMMENT '店铺id',
    biz_day                            DATE COMMENT '日期',
    product_id                         VARCHAR COMMENT '商品ID',
    title                              VARCHAR(255) COMMENT '商品标题',
    product_link                       VARCHAR(500) COMMENT '商品链接',
    commission_paid                    DECIMAL(10, 2) COMMENT '付款佣金支出(元)',
    commission_rate                    VARCHAR(500) COMMENT '付款佣金率',
    payment_amount                     DECIMAL(10, 2) COMMENT '付款金额(元)',
    payment_orders                     INT COMMENT '付款笔数',
    discount_rate                      VARCHAR(500) COMMENT '商品折扣率',
    store_visits                       INT COMMENT '进店量',
    favorites                          INT COMMENT '收藏宝贝量',
    cart_additions                     INT COMMENT '添加购物车量',
    pre_sale_orders                    INT COMMENT '预售定金笔数',
    pre_sale_deposit                   DECIMAL(10, 2) COMMENT '预售定金金额(元)',
    estimated_tail_payment             DECIMAL(10, 2) COMMENT '预估预售尾款金额(元)',
    estimated_total_pre_sale           DECIMAL(10, 2) COMMENT '预估预售整单金额(元)',
    service_fee_paid                   DECIMAL(10, 2) COMMENT '付款服务费支出(元)',
    total_expense                      DECIMAL(10, 2) COMMENT '付款支出费用(元)',
    per_unit_expense                   DECIMAL(10, 2) COMMENT '单件商品付款支出费用(元)',
    service_fee_rate                   VARCHAR(500) COMMENT '付款服务费率',
    settlement_commission              DECIMAL(10, 2) COMMENT '结算佣金支出(元)',
    settlement_service_fee             DECIMAL(10, 2) COMMENT '结算服务费支出(元)',
    settlement_total_expense           DECIMAL(10, 2) COMMENT '结算支出费用(元)',
    estimated_pre_sale_commission      DECIMAL(10, 2) COMMENT '预估预售整单佣金',
    settlement_service_fee_rate        VARCHAR(500) COMMENT '结算服务费率',
    settlement_commission_rate         VARCHAR(500) COMMENT '结算佣金率',
    estimated_pre_sale_commission_rate VARCHAR(500) COMMENT '预估预售整单佣金率',
    store_visitors                     INT COMMENT '进店人数',
    avg_coupon_value                   DECIMAL(10, 2) COMMENT '平均优惠券面额(元)',
    paying_customers                   INT COMMENT '付款人数',
    payment_items                      INT COMMENT '付款件数',
    confirmed_revenue                  DECIMAL(10, 2) COMMENT '确认收货金额(元)',
    payment_conversion_rate            VARCHAR(500) COMMENT '付款转化率',
    confirmed_orders                   INT COMMENT '确认收货笔数',
    settlement_customers               INT COMMENT '结算人数',
    confirmed_receivers                INT COMMENT '确认收货人数',
    settlement_amount                  DECIMAL(10, 2) COMMENT '结算金额(元)',
    settlement_orders                  INT COMMENT '结算笔数',
    created_by                         varchar(100) NOT NULL COMMENT '插入人',
    created_at                         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                         varchar(100) COMMENT '更新人',
    updated_at                         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-商品分析表';



CREATE TABLE tb_trans_log
(
    id              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id         varchar(100) COMMENT '店铺id',
    operate_time    TIMESTAMP COMMENT '操作时间',
    trans_amount    decimal(10, 2) COMMENT '交易金额(元)',
    account_type    VARCHAR(100) COMMENT '账户类型',
    fund_type       VARCHAR(100) COMMENT '资金类型',
    trans_type      VARCHAR(100) COMMENT '流水类型',
    account_balance decimal(10, 2) COMMENT '帐户余额(元)',
    operate_remark  VARCHAR(100) COMMENT '操作备注',
    contract_name   VARCHAR(100) COMMENT '合同名称',
    created_by      varchar(100) NOT NULL COMMENT '插入人',
    created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by      varchar(100) COMMENT '更新人',
    updated_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-交易流水表';

CREATE TABLE tb_cold_product
(
    id                     bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                date COMMENT '日期',
    shop_id                varchar(100) COMMENT '店铺id',
    product_name           VARCHAR(100) COMMENT '商品名称',
    product_id             VARCHAR(100) COMMENT '商品ID',
    status                 VARCHAR(100) COMMENT '状态',
    temperature_chain_flag VARCHAR(50) COMMENT '常温冷链标识',
    created_by             varchar(100) NOT NULL COMMENT '插入人',
    created_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by             varchar(100) COMMENT '更新人',
    updated_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-冷链产品';

CREATE TABLE tb_unpaid_order
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id               varchar(100) COMMENT '店铺id',
    main_order_id         VARCHAR(100) COMMENT '淘宝主订单号',
    sub_order_id          VARCHAR(100) COMMENT '淘宝子订单号',
    product_name          VARCHAR(100) COMMENT '商品名称',
    product_id            VARCHAR(100) COMMENT '商品ID',
    expert_nickname       VARCHAR(100) COMMENT '达人昵称',
    service_provider_name VARCHAR(100) COMMENT '服务商名称',
    create_time           TIMESTAMP COMMENT '订单创建时间',
    pay_time              TIMESTAMP COMMENT '订单支付时间',
    complete_time         VARCHAR(100) COMMENT '订单完结时间',
    status                VARCHAR(100) COMMENT '订单状态',
    actual_pay_amount     decimal(10, 2) COMMENT '订单实付金额',
    refund_amount         decimal(10, 2) COMMENT '订单退款金额',
    commission_amount     decimal(10, 2) COMMENT '订单计佣金额',
    estimated_commission  decimal(10, 2) COMMENT '预估佣金',
    remark                VARCHAR(100) COMMENT '备注',
    record_time           TIMESTAMP COMMENT '时间',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-未出账订单';

CREATE TABLE tb_core_idx
(
    id                  bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day             date COMMENT '日期',
    shop_id             varchar(100) COMMENT '店铺id',
    product_name        VARCHAR(100) COMMENT '商品名称',
    product_id          VARCHAR(100) COMMENT '商品ID',
    cate                VARCHAR(100) COMMENT '类别',
    trans_amount        decimal(10, 2) COMMENT '交易金额',
    visit_num           BIGINT COMMENT '访客数',
    search_num          BIGINT COMMENT '搜索人数',
    collect_num         BIGINT COMMENT '收藏人数',
    cart_num            BIGINT COMMENT '加购人数',
    pay_conversion_rate VARCHAR(100) COMMENT '支付转化率',
    pay_user_num        BIGINT COMMENT '支付买家数',
    pay_item_cnt        BIGINT COMMENT '支付件数',
    search_ratio        VARCHAR(100) COMMENT '搜索占比',
    collect_rate        VARCHAR(100) COMMENT '收藏率',
    cart_rate           VARCHAR(100) COMMENT '加购率',
    avg_customer_price  decimal(10, 2) COMMENT '客单价',
    uv_value            DOUBLE COMMENT 'UV价值',
    created_by          varchar(100) NOT NULL COMMENT '插入人',
    created_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by          varchar(100) COMMENT '更新人',
    updated_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-生意参谋-关键指标';

CREATE TABLE tb_entry_source
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day               date COMMENT '日期',
    shop_id               varchar(100) COMMENT '店铺id',
    product_name          VARCHAR(100) COMMENT '商品名称',
    product_id            VARCHAR(100) COMMENT '商品ID',
    cate                  VARCHAR(100) COMMENT '类别',
    traffic_source        VARCHAR(100) COMMENT '流量来源',
    first_source          VARCHAR(100) COMMENT '一级来源',
    secondary_source      VARCHAR(100) COMMENT '二级来源',
    visit_num             BIGINT COMMENT '访客数',
    order_user_num        BIGINT COMMENT '下单买家数',
    order_conversion_rate VARCHAR(100) COMMENT '下单转化率',
    pay_user_num          BIGINT COMMENT '支付买家数',
    pay_conversion_rate   VARCHAR(100) COMMENT '支付转化率',
    trans_amount          decimal(10, 2) COMMENT '交易金额',
    uv_value              DOUBLE COMMENT 'UV价值',
    avg_customer_price    decimal(10, 2) COMMENT '客单价',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-入店来源';

CREATE TABLE tb_cate_shop_gold
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day               date COMMENT '日期',
    shop_id               varchar(100) COMMENT '店铺id',
    cate_name             VARCHAR(100) COMMENT '类目',
    pay_amount            decimal(10, 2) COMMENT '支付金额',
    pay_amount_percentage VARCHAR(100) COMMENT '支付金额占比',
    success_refund_amount decimal(10, 2) COMMENT '成功退款金额',
    pay_conversion_rate   VARCHAR(100) COMMENT '支付转化率',
    product_visit_num     BIGINT COMMENT '商品访客数',
    action                VARCHAR(100) COMMENT '操作',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-品类购物金';

CREATE TABLE tb_tm_operate_window
(
    id                                     bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                                date COMMENT '日期',
    shop_id                                varchar(100) COMMENT '店铺id',
    sale_amount                            decimal(10, 2) COMMENT '销售金额',
    avg_customer_price                     decimal(10, 2) COMMENT '客单价',
    uv                                     BIGINT COMMENT 'UV',
    pay_conversion_rate                    VARCHAR(100) COMMENT '支付转化率',
    promotion_cost                         decimal(10, 2) COMMENT '推广费用',
    sale_cnt                               BIGINT COMMENT '销售件数',
    order_cnt                              BIGINT COMMENT '订单数',
    pending_order_cnt                      BIGINT COMMENT '待发货订单数',
    active_product_cnt                     BIGINT COMMENT '出售中的宝贝数',
    refund_rate                            VARCHAR(100) COMMENT '退款率',
    customer_inquiry_cnt                   BIGINT COMMENT '客服询单数',
    customer_service_amount                decimal(10, 2) COMMENT '客服销售额',
    ai_customer_service_conversion_rate    VARCHAR(100) COMMENT 'AI客服支付转化率',
    human_customer_service_conversion_rate VARCHAR(100) COMMENT '人工客服支付转化率',
    refund_amount                          decimal(10, 2) COMMENT '退款金额',
    affiliate_commission                   VARCHAR(100) COMMENT '淘宝客佣金',
    keyword_promotion_cost                 VARCHAR(100) COMMENT '关键词推广花费',
    precise_audience_promotion_cost        VARCHAR(100) COMMENT '精准人群推广花费',
    smart_scenario_promotion_cost          VARCHAR(100) COMMENT '智能场景花费',
    created_by                             varchar(100) NOT NULL COMMENT '插入人',
    created_at                             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                             varchar(100) COMMENT '更新人',
    updated_at                             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-天猫运营视窗(废弃)';

CREATE TABLE tb_operate_window
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                         date COMMENT '日期',
    shop_id                         varchar(100) COMMENT '店铺id',
    pay_amount                      DOUBLE COMMENT '支付金额',
    visit_cnt                       BIGINT COMMENT '访客数',
    pay_conversion_rate             VARCHAR(100) COMMENT '支付转化率',
    avg_customer_price              decimal(10, 2) COMMENT '客单价',
    suc_refund_amount               decimal(10, 2) COMMENT '成功退款金额',
    direct_traffic_cost             decimal(10, 2) COMMENT '直通车花费',
    gravity_cube_cost               decimal(10, 2) COMMENT '引力魔方花费',
    wxt_cost                        decimal(10, 2) COMMENT '万相台花费',
    affiliate_commission            decimal(10, 2) COMMENT '淘宝客佣金',
    pay_customer_num                BIGINT COMMENT '支付买家数',
    old_customer_repurchase_rate    VARCHAR(100) COMMENT '老客复购率',
    pay_old_customer_num            BIGINT COMMENT '支付老买家数',
    old_customer_pay_amount         decimal(10, 2) COMMENT '老买家支付金额',
    pay_suborder_cnt                BIGINT COMMENT '支付子订单数',
    pay_item_cnt                    BIGINT COMMENT '支付件数',
    cart_user_num                   BIGINT COMMENT '加购人数',
    cart_item_cnt                   BIGINT COMMENT '加购件数',
    product_collect_num             BIGINT COMMENT '商品收藏人数',
    page_view                       BIGINT COMMENT '浏览量',
    keyword_promotion_cost          VARCHAR(100) COMMENT '关键词推广花费',
    precise_audience_promotion_cost VARCHAR(100) COMMENT '精准人群推广花费',
    smart_scenario_promotion_cost   VARCHAR(100) COMMENT '智能场景花费',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-运营视窗表';

CREATE TABLE tb_account_fee
(
    id                  bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id             varchar(100) COMMENT '店铺id',
    record_time         TIMESTAMP COMMENT '记账时间',
    trans_date          DATE COMMENT '交易日期',
    income_expense_type VARCHAR(100) COMMENT '收支类型',
    trans_type          VARCHAR(100) COMMENT '交易类型',
    trans_amount        decimal(10, 2) COMMENT '操作金额(元)',
    after_amount        decimal(10, 2) COMMENT '操作后余额(元)',
    remark              VARCHAR(100) COMMENT '备注',
    created_by          varchar(100) NOT NULL COMMENT '插入人',
    created_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by          varchar(100) COMMENT '更新人',
    updated_at          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-账户明细';

CREATE TABLE tb_cps_order
(
    id                          bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                     varchar(100) COMMENT '店铺id',
    confirmation_time           TIMESTAMP COMMENT '确认收货时间',
    account_expense_time        TIMESTAMP COMMENT '账户支出时间',
    affiliate_settlement_time   TIMESTAMP COMMENT '淘客结算时间',
    create_time                 TIMESTAMP COMMENT '创建时间',
    plan_name                   VARCHAR(100) COMMENT '计划名称',
    product_id                  BIGINT COMMENT '商品ID',
    product_name                VARCHAR(100) COMMENT '商品名称',
    actual_trans_price          decimal(10, 2) COMMENT '实际成交价格',
    trans_product_quantity      BIGINT COMMENT '成交商品数',
    commission_rate             VARCHAR(100) COMMENT '佣金比例',
    commission                  decimal(10, 2) COMMENT '佣金',
    service_fee_rate            VARCHAR(100) COMMENT '服务费率',
    service_fee_amount          decimal(10, 2) COMMENT '服务费金额',
    parent_order_id             BIGINT COMMENT '淘宝父订单编号',
    sub_order_id                BIGINT COMMENT '淘宝子订单编号',
    source_or_nickname          VARCHAR(100) COMMENT '来源或淘客昵称',
    leader_name                 VARCHAR(100) COMMENT '团长名称',
    is_presale_unpaid_pay_order VARCHAR(50) COMMENT '是否预售未付尾款订单',
    remark                      VARCHAR(100) COMMENT '备注',
    created_by                  varchar(100) NOT NULL COMMENT '插入人',
    created_at                  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                  varchar(100) COMMENT '更新人',
    updated_at                  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-cps订单明细';

CREATE TABLE tb_cps_account_fee
(
    id             bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day        date COMMENT '日期',
    shop_id        varchar(100) COMMENT '店铺id',
    expense_type   VARCHAR(100)   NOT NULL COMMENT '类型',
    expense_amount decimal(10, 2) NOT NULL COMMENT '支出金额',
    created_by     varchar(100)   NOT NULL COMMENT '插入人',
    created_at     timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by     varchar(100) COMMENT '更新人',
    updated_at     timestamp      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-cps账户明细';

CREATE TABLE tb_living_sale
(
    id                     bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                date COMMENT '日期',
    shop_id                varchar(100) COMMENT '店铺id',
    product_id             VARCHAR(100) COMMENT '商品ID',
    product_name           VARCHAR(100) COMMENT '商品名称',
    clicks                 INT COMMENT '点击数',
    click_conversion_rate  VARCHAR(100) COMMENT '点击转化率',
    pay_order_cnt          BIGINT COMMENT '付款笔数',
    pay_amount             decimal(10, 2) COMMENT '付款金额',
    pay_commission         decimal(10, 2) COMMENT '付款佣金支出',
    pay_commission_rate    VARCHAR(100) COMMENT '付款佣金率',
    confirmed_order_cnt    BIGINT COMMENT '确认收货笔数',
    confirmed_amount       decimal(10, 2) COMMENT '确认收货金额',
    settle_order_cnt       BIGINT COMMENT '结算笔数',
    settle_amount          decimal(10, 2) COMMENT '结算金额',
    settle_commission      decimal(10, 2) COMMENT '结算佣金支出',
    settle_commission_rate VARCHAR(100) COMMENT '结算佣金率',
    created_by             varchar(100) NOT NULL COMMENT '插入人',
    created_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by             varchar(100) COMMENT '更新人',
    updated_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-客达播';

CREATE TABLE tb_tm_living_sale
(
    id                     bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                varchar(100) COMMENT '店铺id',
    living_title           VARCHAR(100) COMMENT '直播标题',
    living_start_time      TIMESTAMP COMMENT '开播时间',
    session_id             BIGINT COMMENT '场次ID',
    substitute_anchor_name VARCHAR(100) COMMENT '代播主播名称',
    product_id             BIGINT COMMENT '商品ID',
    product_title          VARCHAR(100) COMMENT '商品标题',
    product_first_cate     VARCHAR(100) COMMENT '商品一级类目',
    parent_order_id        VARCHAR(100) COMMENT '父订单',
    sub_order_id           VARCHAR(100) COMMENT '子订单',
    order_time             TIMESTAMP COMMENT '下单时间',
    pay_time               TIMESTAMP COMMENT '支付时间',
    pay_amount             decimal(10, 2) COMMENT '支付金额',
    confirm_time           VARCHAR(100) COMMENT '确认收货时间',
    confirm_amount         VARCHAR(100) COMMENT '确认收货金额',
    refund_amount          VARCHAR(100) COMMENT '退款金额',
    refund_success_time    VARCHAR(100) COMMENT '退款成功时间',
    substitute_id          VARCHAR(100) COMMENT '代播ID',
    created_by             varchar(100) NOT NULL COMMENT '插入人',
    created_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by             varchar(100) COMMENT '更新人',
    updated_at             timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-直播订单表现表';

CREATE TABLE tb_promotion_report
(
    id                            bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                       date COMMENT '日期',
    shop_id                       varchar(100) COMMENT '店铺id',
    scene_id                      BIGINT COMMENT '场景ID',
    scene_name                    VARCHAR(100) COMMENT '场景名字',
    campaign_id                   BIGINT COMMENT '计划ID',
    campaign_name                 VARCHAR(100) COMMENT '计划名字',
    unit_id                       BIGINT COMMENT '单元ID',
    unit_name                     VARCHAR(100) COMMENT '单元名字',
    subject_id                    BIGINT COMMENT '主体ID',
    subject_type                  VARCHAR(100) COMMENT '主体类型',
    subject_name                  VARCHAR(100) COMMENT '主体名称',
    impressions                   BIGINT COMMENT '展现量',
    clicks                        BIGINT COMMENT '点击量',
    cost                          decimal(10, 2) COMMENT '花费',
    click_rate                    DOUBLE COMMENT '点击率',
    avg_click_cost                VARCHAR(100) COMMENT '平均点击花费',
    thousand_impression_cost      decimal(10, 2) COMMENT '千次展现花费',
    total_presale_amount          decimal(10, 2) COMMENT '总预售成交金额',
    total_presale_order_cnt       BIGINT COMMENT '总预售成交笔数',
    direct_presale_amount         decimal(10, 2) COMMENT '直接预售成交金额',
    direct_presale_order_cnt      BIGINT COMMENT '直接预售成交笔数',
    indirect_presale_amount       decimal(10, 2) COMMENT '间接预售成交金额',
    indirect_presale_order_cnt    BIGINT COMMENT '间接预售成交笔数',
    direct_sale_amount            decimal(10, 2) COMMENT '直接成交金额',
    indirect_sale_amount          decimal(10, 2) COMMENT '间接成交金额',
    total_sale_amount             decimal(10, 2) COMMENT '总成交金额',
    total_sale_order_cnt          BIGINT COMMENT '总成交笔数',
    direct_sale_order_cnt         BIGINT COMMENT '直接成交笔数',
    indirect_sale_order_cnt       BIGINT COMMENT '间接成交笔数',
    click_conversion_rate         VARCHAR(100) COMMENT '点击转化率',
    return_on_investment          VARCHAR(100) COMMENT '投入产出比',
    total_sale_cost               VARCHAR(100) COMMENT '总成交成本',
    total_cart_item_cnt           BIGINT COMMENT '总购物车数',
    direct_cart_item_cnt          BIGINT COMMENT '直接购物车数',
    indirect_cart_item_cnt        BIGINT COMMENT '间接购物车数',
    cart_rate                     VARCHAR(100) COMMENT '加购率',
    favorite_product_cnt          BIGINT COMMENT '收藏宝贝数',
    favorite_store_cnt            BIGINT COMMENT '收藏店铺数',
    store_favorite_cost           VARCHAR(100) COMMENT '店铺收藏成本',
    total_favorite_cart_cnt       BIGINT COMMENT '总收藏加购数',
    total_favorite_cart_cost      VARCHAR(100) COMMENT '总收藏加购成本',
    product_favorite_cart_cnt     BIGINT COMMENT '宝贝收藏加购数',
    product_favorite_cart_cost    VARCHAR(100) COMMENT '宝贝收藏加购成本',
    total_favorite_cnt            BIGINT COMMENT '总收藏数',
    product_favorite_cost         VARCHAR(100) COMMENT '宝贝收藏成本',
    product_favorite_rate         VARCHAR(100) COMMENT '宝贝收藏率',
    cart_cost                     VARCHAR(100) COMMENT '加购成本',
    placed_order_cnt              BIGINT COMMENT '拍下订单笔数',
    placed_order_amount           decimal(10, 2) COMMENT '拍下订单金额',
    direct_product_favorite_cnt   BIGINT COMMENT '直接收藏宝贝数',
    indirect_product_favorite_cnt BIGINT COMMENT '间接收藏宝贝数',
    coupon_redemption_cnt         BIGINT COMMENT '优惠券领取量',
    deposit_trans_cnt             BIGINT COMMENT '购物金充值笔数',
    deposit_amount                decimal(10, 2) COMMENT '购物金充值金额',
    ww_inquiried_cnt              BIGINT COMMENT '旺旺咨询量',
    guided_visit_cnt              BIGINT COMMENT '引导访问量',
    guided_visitor_num            BIGINT COMMENT '引导访问人数',
    guided_lead_num               BIGINT COMMENT '引导访问潜客数',
    guided_leads_ratio            VARCHAR(100) COMMENT '引导访问潜客占比',
    membership_rate               VARCHAR(100) COMMENT '入会率',
    membership_cnt                BIGINT COMMENT '入会量',
    guided_visit_rate             DOUBLE COMMENT '引导访问率',
    deep_visit_cnt                BIGINT COMMENT '深度访问量',
    avg_pages_per_visit           VARCHAR(100) COMMENT '平均访问页面数',
    new_customer_num              BIGINT COMMENT '成交新客数',
    new_customer_ratio            VARCHAR(100) COMMENT '成交新客占比',
    first_time_member_num         BIGINT COMMENT '会员首购人数',
    member_sale_amount            decimal(10, 2) COMMENT '会员成交金额',
    member_sale_order_cnt         BIGINT COMMENT '会员成交笔数',
    total_customer_num            BIGINT COMMENT '成交人数',
    avg_customer_sale_cnt         VARCHAR(100) COMMENT '人均成交笔数',
    avg_customer_sale_amount      VARCHAR(100) COMMENT '人均成交金额',
    new_exposure_customer_num     BIGINT COMMENT '曝光新客数',
    new_visit_num                 BIGINT COMMENT '进店新客数',
    new_cart_customer_num         BIGINT COMMENT '加购新客数',
    new_favorite_customer_num     BIGINT COMMENT '收藏新客数',
    new_customer_sale_amount      decimal(10, 2) COMMENT '新客支付金额',
    new_customer_click_rate       DOUBLE COMMENT '新客点击率',
    new_customer_conversion_rate  VARCHAR(100) COMMENT '新客成交转化率',
    organic_sale_amount           decimal(10, 2) COMMENT '自然流量转化金额',
    organic_exposure_cnt          BIGINT COMMENT '自然流量曝光量',
    created_by                    varchar(100) NOT NULL COMMENT '插入人',
    created_at                    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                    varchar(100) COMMENT '更新人',
    updated_at                    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-单元报表';

CREATE TABLE tb_account_report
(
    id                             bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                        date COMMENT '日期',
    shop_id                        varchar(100) COMMENT '店铺id',
    scene_id                       BIGINT COMMENT '场景ID',
    scene_name                     VARCHAR(100) COMMENT '场景名字',
    impression_cnt                 BIGINT COMMENT '展现量',
    click_cnt                      BIGINT COMMENT '点击量',
    cost                           decimal(10, 2) COMMENT '花费',
    click_rate                     DOUBLE COMMENT '点击率',
    avg_click_cost                 decimal(10, 2) COMMENT '平均点击花费',
    thousand_impression_cost       decimal(10, 2) COMMENT '千次展现花费',
    total_presale_amount           decimal(10, 2) COMMENT '总预售成交金额',
    total_presale_order_cnt        BIGINT COMMENT '总预售成交笔数',
    direct_presale_amount          decimal(10, 2) COMMENT '直接预售成交金额',
    direct_presale_order_cnt       BIGINT COMMENT '直接预售成交笔数',
    indirect_presale_amount        decimal(10, 2) COMMENT '间接预售成交金额',
    indirect_presale_order_cnt     BIGINT COMMENT '间接预售成交笔数',
    direct_sale_amount             decimal(10, 2) COMMENT '直接成交金额',
    indirect_sale_amount           decimal(10, 2) COMMENT '间接成交金额',
    total_sale_amount              decimal(10, 2) COMMENT '总成交金额',
    total_sale_order_cnt           BIGINT COMMENT '总成交笔数',
    direct_sale_order_cnt          BIGINT COMMENT '直接成交笔数',
    indirect_sale_order_cnt        BIGINT COMMENT '间接成交笔数',
    click_conversion_rate          DOUBLE COMMENT '点击转化率',
    return_on_investment           DOUBLE COMMENT '投入产出比',
    total_sales_cost               decimal(10, 2) COMMENT '总成交成本',
    total_cart_item_cnt            BIGINT COMMENT '总购物车数',
    direct_cart_item_cnt           BIGINT COMMENT '直接购物车数',
    indirect_cart_item_cnt         BIGINT COMMENT '间接购物车数',
    cart_rate                      DOUBLE COMMENT '加购率',
    favorite_product_cnt           BIGINT COMMENT '收藏宝贝数',
    favorite_store_cnt             BIGINT COMMENT '收藏店铺数',
    store_favorite_cost            VARCHAR(100) COMMENT '店铺收藏成本',
    total_favorite_cart_item_cnt   BIGINT COMMENT '总收藏加购数',
    total_favorite_cart_cost       decimal(10, 2) COMMENT '总收藏加购成本',
    product_favorite_cart_item_cnt BIGINT COMMENT '宝贝收藏加购数',
    product_favorite_cart_cost     decimal(10, 2) COMMENT '宝贝收藏加购成本',
    total_favorite_cnt             BIGINT COMMENT '总收藏数',
    product_favorite_cost          VARCHAR(100) COMMENT '宝贝收藏成本',
    product_favorite_rate          DOUBLE COMMENT '宝贝收藏率',
    cart_cost                      decimal(10, 2) COMMENT '加购成本',
    placed_order_cnt               BIGINT COMMENT '拍下订单笔数',
    placed_order_amount            decimal(10, 2) COMMENT '拍下订单金额',
    direct_product_favorite_cnt    BIGINT COMMENT '直接收藏宝贝数',
    indirect_product_favorite_cnt  BIGINT COMMENT '间接收藏宝贝数',
    coupon_redemption_cnt          BIGINT COMMENT '优惠券领取量',
    deposit_trans_cnt              BIGINT COMMENT '购物金充值笔数',
    deposit_amount                 decimal(10, 2) COMMENT '购物金充值金额',
    ww_inquiried_cnt               BIGINT COMMENT '旺旺咨询量',
    guided_visit_cnt               BIGINT COMMENT '引导访问量',
    guided_visit_num               BIGINT COMMENT '引导访问人数',
    guided_lead_num                BIGINT COMMENT '引导访问潜客数',
    guided_lead_ratio              DOUBLE COMMENT '引导访问潜客占比',
    membership_rate                DOUBLE COMMENT '入会率',
    membership_cnt                 BIGINT COMMENT '入会量',
    guided_visit_rate              DOUBLE COMMENT '引导访问率',
    deep_visit_cnt                 BIGINT COMMENT '深度访问量',
    avg_page_visit_cnt             BIGINT COMMENT '平均访问页面数',
    new_customer_num               BIGINT COMMENT '成交新客数',
    new_customer_ratio             DOUBLE COMMENT '成交新客占比',
    first_time_member_num          BIGINT COMMENT '会员首购人数',
    member_sale_amount             decimal(10, 2) COMMENT '会员成交金额',
    member_sale_order_cnt          BIGINT COMMENT '会员成交笔数',
    total_customer_num             BIGINT COMMENT '成交人数',
    avg_customer_sale_cnt          BIGINT COMMENT '人均成交笔数',
    avg_customer_sale_amount       decimal(10, 2) COMMENT '人均成交金额',
    organic_sale_amount            decimal(10, 2) COMMENT '自然流量转化金额',
    organic_exposure_cnt           BIGINT COMMENT '自然流量曝光量',
    created_by                     varchar(100) NOT NULL COMMENT '插入人',
    created_at                     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                     varchar(100) COMMENT '更新人',
    updated_at                     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-账户报表';

CREATE TABLE tb_coupon_usage
(
    id             bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day        date COMMENT '记账日期',
    shop_id        varchar(100) COMMENT '店铺id',
    shop_name      VARCHAR(100) COMMENT '店铺',
    coupon_name    VARCHAR(100) COMMENT '优惠券名称',
    coupon_type    VARCHAR(100) COMMENT '券类型',
    usage_method   VARCHAR(100) COMMENT '使用方式',
    operate_amount decimal(10, 2) COMMENT '操作金额(元)',
    remark         VARCHAR(500) COMMENT '备注',
    created_by     varchar(100) NOT NULL COMMENT '插入人',
    created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by     varchar(100) COMMENT '更新人',
    updated_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-账户明细-优惠券花费明细';

CREATE TABLE tb_special_trans
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) COMMENT '店铺id',
    shop_name            VARCHAR(100) COMMENT '店铺',
    account_time         TIMESTAMP COMMENT '记账时间',
    special_fund_id      BIGINT COMMENT '专款ID',
    income_expense_type  VARCHAR(100) COMMENT '收支类型',
    trans_type           VARCHAR(100) COMMENT '交易类型',
    special_fund_type    VARCHAR(100) COMMENT '专款类型',
    operate_amount       decimal(10, 2) COMMENT '操作金额(元)',
    market_fund_amount   decimal(10, 2) COMMENT '营销专款（元）',
    cash_fund_amount     decimal(10, 2) COMMENT '现金专款（元）',
    after_operate_amount decimal(10, 2) COMMENT '操作后余额(元)',
    remark               VARCHAR(500) COMMENT '备注',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-账户明细-专款现金交易明细';

CREATE TABLE tb_service_metrics
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                         varchar(100) COMMENT '店铺id',
    biz_day                         date COMMENT '日期',
    service_metric                  VARCHAR(255) COMMENT '服务指标',
    metric_performance              VARCHAR(255) COMMENT '指标表现',
    comparison_with_previous_period VARCHAR(100) COMMENT '环比',
    industry_average                VARCHAR(100) COMMENT '同行同层均值',
    industry_excellent              VARCHAR(100) COMMENT '同行同层优秀',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-售后服务指标体系';

CREATE TABLE tb_assessment
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) COMMENT '店铺id',
    biz_day              date COMMENT '日期',
    assessment_dimension VARCHAR(255) COMMENT '考核维度',
    assessment_score     DOUBLE COMMENT '考核得分',
    experience_metric    VARCHAR(255) COMMENT '体验指标',
    metric_score         VARCHAR(100) COMMENT '指标得分',
    metric_value         VARCHAR(100) COMMENT '指标值',
    standard             VARCHAR(255) COMMENT '2分/3分/4分/5分标准',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-考核详情';

CREATE TABLE tb_experience_score
(
    id               bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id          varchar(100) COMMENT '店铺id',
    biz_day          date COMMENT '日期',
    experience_score DOUBLE COMMENT '店铺综合体验分',
    created_by       varchar(100) NOT NULL COMMENT '插入人',
    created_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by       varchar(100) COMMENT '更新人',
    updated_at       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-店铺综合体验分';

CREATE TABLE tb_ww_satisfaction
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) COMMENT '店铺id',
    biz_day              date COMMENT '日期',
    service_satisfaction VARCHAR(255) COMMENT '服务满意度',
    industry_excellent   VARCHAR(255) COMMENT '同行同层优秀',
    team_standard        VARCHAR(255) COMMENT '团队标准',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-旺旺满意度';

CREATE TABLE tb_cdl_product_statistics
(
    id                           bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                      varchar(100) COMMENT '店铺id',
    shop_name                    varchar(100) COMMENT '店铺名称',
    biz_day                      date COMMENT '日期',
    product_id                   BIGINT COMMENT '商品ID',
    product_name                 VARCHAR(255) COMMENT '商品名称',
    main_product_id              BIGINT COMMENT '主商品ID',
    product_type                 VARCHAR(100) COMMENT '商品类型',
    product_code                 VARCHAR(100) COMMENT '货号',
    product_status               VARCHAR(100) COMMENT '商品状态',
    product_tag                  VARCHAR(255) COMMENT '商品标签',
    product_visit_num            BIGINT COMMENT '商品访客数',
    product_view_cnt             BIGINT COMMENT '商品浏览量',
    avg_stay_time                DOUBLE COMMENT '平均停留时长',
    bounce_rate                  VARCHAR(50) COMMENT '商品详情页跳出率',
    product_favorite_num         BIGINT COMMENT '商品收藏人数',
    product_cart_cnt             BIGINT COMMENT '商品加购件数',
    product_cart_num             BIGINT COMMENT '商品加购人数',
    order_buy_num                BIGINT COMMENT '下单买家数',
    order_buy_cnt                BIGINT COMMENT '下单件数',
    order_amount                 decimal(10, 2) COMMENT '下单金额',
    order_conversion_rate        VARCHAR(50) COMMENT '下单转化率',
    pay_num                      BIGINT COMMENT '支付买家数',
    pay_cnt                      BIGINT COMMENT '支付件数',
    pay_amount                   decimal(10, 2) COMMENT '支付金额',
    product_pay_conversion_rate  VARCHAR(50) COMMENT '商品支付转化率',
    new_user_pay_num             BIGINT COMMENT '支付新买家数',
    old_user_pay_num             BIGINT COMMENT '支付老买家数',
    old_user_pay_amount          decimal(10, 2) COMMENT '老买家支付金额',
    jhs_pay_amount               decimal(10, 2) COMMENT '聚划算支付金额',
    visit_avg_value              DOUBLE COMMENT '访客平均价值',
    refund_amount                DOUBLE COMMENT '成功退款金额',
    competitiveness_score        VARCHAR(50) COMMENT '竞争力评分',
    annual_pay_amount            decimal(10, 2) COMMENT '年累计支付金额',
    monthly_pay_amount           decimal(10, 2) COMMENT '月累计支付金额',
    monthly_pay_quantity         BIGINT COMMENT '月累计支付件数',
    search_guide_conversion_rate VARCHAR(50) COMMENT '搜索引导支付转化率',
    search_guide_visit_num       BIGINT COMMENT '搜索引导访客数',
    search_guide_pay_num         BIGINT COMMENT '搜索引导支付买家数',
    structured_conversion_rate   VARCHAR(50) COMMENT '结构化详情引导转化率',
    structured_trans_ratio       VARCHAR(50) COMMENT '结构化详情引导成交占比',
    data_page_link               VARCHAR(255) COMMENT '数据页面链接',
    update_time                  TIMESTAMP COMMENT '更新时间',
    created_by                   varchar(100) NOT NULL COMMENT '插入人',
    created_at                   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                   varchar(100) COMMENT '更新人',
    updated_at                   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-馋哆啦商品排行';

CREATE TABLE tb_settle_overview
(
    id                 bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id            varchar(100) COMMENT '店铺id',
    biz_day            date COMMENT '日期',
    settle_amount      DOUBLE COMMENT '结算金额',
    commission_expense DOUBLE COMMENT '结算佣金支出',
    directed_plan_name VARCHAR(255) COMMENT '定向计划名称',
    created_by         varchar(100) NOT NULL COMMENT '插入人',
    created_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by         varchar(100) COMMENT '更新人',
    updated_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-定向计划报表-概览数据';

CREATE TABLE rpa_data.tb_qn_financial_records
(
    id                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id           varchar(100) COMMENT '店铺id',
    entry_time        DATETIME COMMENT '入账时间',
    payment_serial_no VARCHAR(64) COMMENT '支付流水号',
    taobao_order_no   VARCHAR(64) COMMENT '淘宝订单编号',
    entry_type        VARCHAR(32) COMMENT '入账类型',
    income_amount     DECIMAL(15, 2) DEFAULT 0.00 COMMENT '收入金额（元）',
    expense_amount    DECIMAL(15, 2) DEFAULT 0.00 COMMENT '支出金额（元）',
    business_desc     VARCHAR(500) COMMENT '业务描述',
    remarks           VARCHAR(1000) COMMENT '备注',
    created_by        varchar(100) COMMENT '插入人',
    created_at        timestamp      DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by        varchar(100) COMMENT '更新人',
    updated_at        timestamp      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-千牛-财务-资金管理-聚合结算账户-收支明细';

CREATE TABLE rpa_data.tb_sycm_product_performance
(
    id                      INT AUTO_INCREMENT COMMENT '主键ID',
    shop_id                 varchar(100) COMMENT '店铺id',
    biz_day                 DATE COMMENT '统计日期',
    product_id              BIGINT COMMENT '商品id',
    ju_id                   BIGINT COMMENT 'juId',
    product_title           VARCHAR(500) COMMENT '商品标题',
    product_image           VARCHAR(1000) COMMENT '商品图片',
    first_category_id       varchar COMMENT '一级类目ID',
    second_category_id      varchar COMMENT '二级类目ID',
    leaf_category_id        varchar COMMENT '叶子类目ID',
    group_type              VARCHAR(50) COMMENT '团型',
    activity_name           VARCHAR(200) COMMENT '活动名称',
    product_ipv             INT COMMENT '商品ipv',
    product_uv              INT COMMENT '商品访客数',
    payment_amount          varchar COMMENT '支付金额',
    burst_factor            DECIMAL(10, 4) COMMENT '爆发系数',
    payment_buyers          varchar(255) COMMENT '支付买家数',
    sub_orders              varchar COMMENT '子订单数',
    transaction_quantity    varchar COMMENT '成交件数',
    payment_conversion_rate varchar COMMENT '支付转化率',
    avg_order_value         varchar COMMENT '客单价',
    created_by              varchar(100) COMMENT '插入人',
    created_at              timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by              varchar(100) COMMENT '更新人',
    updated_at              timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-生意参谋-业务专区-聚划算数据中心-商品明细';

CREATE TABLE rpa_data.tb_sycm_product_sales_stats
(
    id                   INT AUTO_INCREMENT COMMENT '主键ID',
    shop_id              BIGINT COMMENT '店铺id',
    biz_day              DATE COMMENT '日期',
    first_category_id    VARCHAR(50) COMMENT '一级类目id',
    first_category_name  VARCHAR(100) COMMENT '一级类目',
    second_category_id   VARCHAR(50) COMMENT '二级类目id',
    second_category_name VARCHAR(100) COMMENT '二级类目',
    leaf_category_id     VARCHAR(50) COMMENT '叶子类目id',
    leaf_category_name   VARCHAR(100) COMMENT '叶子类目',
    product_id           BIGINT COMMENT '商品ID',
    product_name         VARCHAR(500) COMMENT '商品名称',
    is_semi_managed      TINYINT COMMENT '是否半托管',
    product_ipv          INT COMMENT '商品IPV',
    product_ipv_uv       INT COMMENT '商品IPVUV',
    gmv                  DECIMAL(10, 2) COMMENT '成交GMV',
    paid_users           INT COMMENT '成交用户数',
    paid_orders          INT COMMENT '成交订单量',
    paid_items           INT COMMENT '成交商品件数',
    created_by           varchar(100) COMMENT '插入人',
    created_at           timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='淘宝-生意参谋-品类-百亿补贴(新)-商品汇总';

CREATE TABLE rpa_data.tb_qn_fund_flow_records
(
    id                 INT AUTO_INCREMENT COMMENT '主键ID',
    shop_id            BIGINT COMMENT '店铺id',
    biz_day            DATE COMMENT '日期',
    transaction_time   DATETIME COMMENT '时间',
    transaction_reason VARCHAR(200) COMMENT '原因',
    amount             DECIMAL(15, 2) COMMENT '金额(元)',
    from_account       VARCHAR(100) COMMENT '来源账户',
    to_account         VARCHAR(100) COMMENT '去向账户',
    remarks            VARCHAR(500) COMMENT '备注',
    business_desc      VARCHAR(500) COMMENT '业务描述',
    business_order_no  VARCHAR(100) COMMENT '业务订单号',
    order_penalty_id   VARCHAR(100) COMMENT '订单ID/处罚ID',
    fund_composition   VARCHAR(300) COMMENT '资金组成',
    created_by         varchar(100) COMMENT '插入人',
    created_at         timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by         varchar(100) COMMENT '更新人',
    updated_at         timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='资金流水记录表';



CREATE TABLE financial_billing_details
(
    id                       INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    account_period           VARCHAR(20) COMMENT '账期（格式：YYYY-MM）',
    fund_direction           VARCHAR(10) COMMENT '资金方向：收入/支出',
    bill_category            VARCHAR(50) COMMENT '账单大类',
    business_main_category   VARCHAR(50) COMMENT '业务大类',
    business_sub_category    VARCHAR(50) COMMENT '业务小类',
    expense_item             VARCHAR(100) COMMENT '支出项目',
    main_order_no            VARCHAR(100) COMMENT '交易主订单号',
    sub_order_no             VARCHAR(100) COMMENT '交易子订单号',
    order_date               DATE COMMENT '订单日期',
    product_name             VARCHAR(500) COMMENT '商品名称',
    quantity                 INT COMMENT '数量',
    unit_price               DECIMAL(15, 4) .0000 COMMENT '单价',
    transaction_amount       DECIMAL(15, 2) .00 COMMENT '扣费交易金额',
    commission_rate          DECIMAL(8, 4) .0000 COMMENT '佣金率',
    expense_amount           DECIMAL(15, 2) .00 COMMENT '支出金额（元）',
    deduction_date           DATE COMMENT '扣费日期',
    alipay_merchant_order_no VARCHAR(100) COMMENT '支付宝商户订单号',
    application_id           VARCHAR(100) COMMENT '报名ID',
    payment_channel_desc     VARCHAR(200) COMMENT '收/付渠道描述',
    deduction_amount         DECIMAL(15, 2) .00 COMMENT '扣费金额（元）',
    refund_amount            DECIMAL(15, 2) .00 COMMENT '退款金额（元）',
    confirm_receipt_date     DATE COMMENT '确认收货日期'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='财务账单明细表';



select '淘宝-生意参谋-品类-百亿补贴(新)-商品汇总',
       'tb_sycm_product_sales_stats',
       COLUMN_NAME,
       DATA_TYPE,
       COLUMN_COMMENT,
       CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'tb_sycm_product_sales_stats';


select *
from rpa_data.rdy_order_info order by  order_time desc ;

