#*********************************** 天猫平台 ***********************************
CREATE TABLE tm_inventory_performance
(
    id                                  bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day                             date COMMENT '日期',
    shop_id                             varchar(100) COMMENT '店铺id',
    product                             varchar(100) COMMENT '商品',
    product_name                        varchar(100) COMMENT '商品名称',
    product_id                          bigint COMMENT '商品 ID',
    sku_id                              bigint COMMENT 'SKU ID',
    goods_name                          varchar(100) COMMENT '货品名称',
    goods_id                            bigint COMMENT '货品 ID',
    barcode                             varchar(100) COMMENT '条形码',
    logical_warehouse_code              varchar(100) COMMENT '逻辑仓编码',
    warehouse_role_name                 varchar(100) COMMENT '仓角色名称',
    physical_warehouse_name             varchar(100) COMMENT '物理仓名称',
    physical_warehouse_code             varchar(100) COMMENT '物理仓编码',
    brand_name                          varchar(100) COMMENT '品牌名称',
    cate_name                           varchar(100) COMMENT '类目名称',
    goods_status                        varchar(100) COMMENT '货品状态',
    unsold_28d_cnt                      bigint COMMENT '28天不动销件数',
    purchase_in_transit_cnt             bigint COMMENT '采购在途库存件数',
    transfer_in_transit_cnt             bigint COMMENT '调拨在途库存件数',
    high_age_inventory_cnt              bigint COMMENT '高库龄件数',
    high_age_high_turnover_inventory_cnt double COMMENT '高库龄且高周转库存件数',
    high_age_high_turnover_inventory_ratio double COMMENT '高库龄且高周转库存件数占比',
    high_turnover_cnt double COMMENT '高周转件数',
    supplier_defective_due_to_delivery  bigint COMMENT '供应商到货原因导致残次',
    saleable_inventory_days double COMMENT '库存可售天数',
    inventory_turnover_days double COMMENT '库存周转天数',
    future_28d_sales_plan_inventory double COMMENT '未来28天销量计划库存件数',
    expiry_warning_cnt                  bigint COMMENT '效期预警件数',
    defective_inventory_cnt             bigint COMMENT '在库残品库存件数',
    defective_inventory_ratio double COMMENT '在库残品库存件数占比',
    non_locked_good_inventory_cnt       bigint COMMENT '在库良品非锁定库存件数',
    non_sales_locked_good_inventory_cnt bigint COMMENT '在库良品非销售锁定库存件数',
    good_inventory_cnt                  bigint COMMENT '在库良品库存件数',
    total_inventory_cnt                 bigint COMMENT '在库总库存件数',
    turnover_impact_value double COMMENT '周转影响值',
    avg_28d_daily_sales_out_inventory double COMMENT '最近28天日均销售出库库存件数',
    last_1d_sales_out_cnt               bigint COMMENT '最近1天出库件数',
    last_7d_sales_out_cnt               bigint COMMENT '最近7天出库件数',
    last_14d_sales_out_cnt              bigint COMMENT '最近14天出库件数',
    last_30d_sales_out_cnt              bigint COMMENT '最近30天出库件数',
    high_age_warning_cnt                bigint COMMENT '高库龄预警件数',
    created_by                          varchar(100) NOT NULL COMMENT '插入人',
    created_at                          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                          varchar(100) COMMENT '更新人',
    updated_at                          timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-供应链-库存分析';

CREATE TABLE tm_core_idx
(
    id                 bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day            date COMMENT '日期',
    shop_id            varchar(100) COMMENT '店铺id',
    analysis_dimension varchar(100) COMMENT '分析维度',
    empty_value        varchar(100) COMMENT '空值',
    own_product        varchar(100) COMMENT '本店商品',
    own_value double COMMENT '本店数值',
    competitor_product varchar(100) COMMENT '竞品',
    competitor_value double COMMENT '竞品数值',
    own_sku            bigint COMMENT '本店SKU',
    competitor_sku     bigint COMMENT '竞品SKU',
    created_by         varchar(100) NOT NULL COMMENT '插入人',
    created_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by         varchar(100) COMMENT '更新人',
    updated_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-竞品-核心指标';

CREATE TABLE tm_flow
(
    id         bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    biz_day    date COMMENT '日期',
    shop_id    varchar(100) COMMENT '店铺id',
    channel    varchar(100) COMMENT '通道',
    shop_traffic_heat double COMMENT '本店访问热度',
    shop_traffic_popularity double COMMENT '本店访问人气',
    competitor_traffic_heat double COMMENT '竞品访问热度',
    competitor_traffic_popularity double COMMENT '竞品访问人气',
    own_sku double COMMENT '本店SKU',
    competitor_sku double COMMENT '竞品SKU',
    created_by varchar(100) NOT NULL COMMENT '插入人',
    created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by varchar(100) COMMENT '更新人',
    updated_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-竞品-流量分析';

CREATE TABLE tm_actual_inventory
(
    id                               bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                          varchar(100) COMMENT '店铺id',
    shop_name                        varchar(100) COMMENT '店铺名称',
    biz_day                          date COMMENT '日期',
    product_name                     varchar(100) COMMENT '货品名称',
    product_id                       bigint COMMENT '货品ID',
    product_code                     varchar(100) COMMENT '货品编码',
    barcode                          varchar(100) COMMENT '条形码',
    supply_chain_owner_name          varchar(100) COMMENT '供应链货主名称',
    supply_chain_owner_id            bigint COMMENT '供应链货主ID',
    brand_name                       varchar(100) COMMENT '商品品牌名称',
    warehouse_name                   varchar(100) COMMENT '仓库名称',
    warehouse_code                   varchar(100) COMMENT '仓库CODE',
    warehouse_type                   varchar(100) COMMENT '仓类型',
    warehouse_role                   varchar(100) COMMENT '仓角色',
    supplier_name                    varchar(100) COMMENT '供应商名称',
    supplier_id                      bigint COMMENT '供应商ID',
    supplier_code                    bigint COMMENT '供应商编码',
    actual_inventory                 bigint COMMENT '实仓库存',
    available_good_stock             bigint COMMENT '良品可用',
    occupied_good_stock              bigint COMMENT '良品占用',
    available_defective_stock        bigint COMMENT '残品可用',
    occupied_defective_stock         bigint COMMENT '残品占用',
    pending_good_stock               bigint COMMENT '收货待上架良品',
    pending_defective_stock          bigint COMMENT '收货待上架残品',
    pending_transfer_good_stock      bigint COMMENT '收货待调拨良品',
    pending_transfer_defective_stock bigint COMMENT '收货待调拨残品',
    purchase_in_transit              bigint COMMENT '采购在途',
    transfer_in_transit              bigint COMMENT '调拨在途',
    sales_in_transit                 bigint COMMENT '销售在途',
    sales_return_in_transit          bigint COMMENT '销退在途',
    transfer_difference              bigint COMMENT '调拨差异',
    sales_return_difference          bigint COMMENT '销退差异',
    item_name                        varchar(100) COMMENT '商品名称',
    associated_item_id_sku           varchar(100) COMMENT '关联商品ID-SKUID',
    industry                         varchar(100) COMMENT '行业',
    first_cate                       varchar(100) COMMENT '一级类目',
    first_cate_id                    bigint COMMENT '一级类目ID',
    secondary_cate                   varchar(100) COMMENT '二级类目',
    secondary_cate_id                bigint COMMENT '二级类目ID',
    third_cate                       varchar(100) COMMENT '三级类目',
    third_cate_id                    bigint COMMENT '三级类目ID',
    four_cate                        varchar(100) COMMENT '四级类目',
    four_cate_id                     bigint COMMENT '四级类目ID',
    created_by                       varchar(100) NOT NULL COMMENT '插入人',
    created_at                       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                       varchar(100) COMMENT '更新人',
    updated_at                       timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-库存-实时库存';

CREATE TABLE tm_inventory_trans
(
    id                                bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                           varchar(100) COMMENT '店铺id',
    shop_name                         varchar(100) COMMENT '店铺名称',
    biz_day                           date COMMENT '日期',
    product_id                        bigint COMMENT '商品id',
    product_name                      varchar(100) COMMENT '商品名称',
    item_id                           bigint COMMENT '货品id',
    warehouse_name                    varchar(100) COMMENT '仓库名称',
    item_code                         varchar(100) COMMENT '货品编码',
    sku_id                            bigint COMMENT 'skuId',
    warehouse_code                    varchar(100) COMMENT '仓库编码',
    brand_name                        varchar(100) COMMENT '品牌名称',
    initial_stock double COMMENT '当日(在架+收货暂存)期初库存',
    initial_good_stock double COMMENT '当日期初在架良品库存',
    initial_defective_stock double COMMENT '当日期初在架残次库存',
    initial_receiving_good_stock double COMMENT '当日期初收货暂存良品库存',
    initial_receiving_defective_stock bigint COMMENT '当日期初收货暂存残次库存',
    final_stock double COMMENT '当日(在架+收货暂存)期末库存',
    final_good_stock double COMMENT '当日期末在架良品库存',
    final_defective_stock double COMMENT '当日期末架残次库存',
    final_receiving_good_stock double COMMENT '当日期末收货暂存良品库存',
    final_receiving_defective_stock   bigint COMMENT '当日期末收货暂存残次库存',
    purchase_inbound_total            bigint COMMENT '采购入库总数',
    trans_outbound_total double COMMENT '交易出库总数',
    b2b_trans_outbound_total          bigint COMMENT 'b2b交易出库总数',
    return_inbound_good_total double COMMENT '退货入库良品总数',
    return_inbound_defective_total double COMMENT '退货入库残次总数',
    transfer_outbound_total double COMMENT '调拨出库总数',
    final_transfer_in_transit_stock double COMMENT '期末调拨在途库存',
    transfer_inbound_total double COMMENT '调拨入库总数',
    inventory_check_outbound_total double COMMENT '盘点出库总数',
    inventory_check_inbound_total double COMMENT '盘点入库总数',
    warehouse_return_outbound_total double COMMENT '退仓出库总数',
    adjustment_inbound_total double COMMENT '调整入库总数',
    adjustment_outbound_total double COMMENT '调整出库总数',
    replacement_inbound_total         bigint COMMENT '汰换/代转经入库总数',
    replacement_outbound_total        bigint COMMENT '汰换/代转经出库总数',
    scrapped_outbound_total           bigint COMMENT '报废出库总数',
    created_by                        varchar(100) NOT NULL COMMENT '插入人',
    created_at                        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                        varchar(100) COMMENT '更新人',
    updated_at                        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-库存进销存台账';

CREATE TABLE tm_promotion_fee
(
    id                   bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id              varchar(100) COMMENT '店铺id',
    shop_name            varchar(100) COMMENT '店铺名称',
    accounting_time      timestamp COMMENT '记账时间',
    trans_date           date COMMENT '交易日期',
    income_expense_type  varchar(100) COMMENT '收支类型',
    trans_type           varchar(100) COMMENT '交易类型',
    operate_amount       decimal(10, 2) COMMENT '操作金额(元)',
    after_operate_amount decimal(10, 2) COMMENT '操作后余额(元)',
    platform             varchar(100) COMMENT '平台',
    update_time          timestamp COMMENT '更新日期',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-猫超推广费';

CREATE TABLE tm_account_fee
(
    id                   bigint AUTO_INCREMENT COMMENT '编号',
    record_id            bigint COMMENT '记录编号',
    shop_id              varchar(100) COMMENT '店铺id',
    shop_name            varchar(100) COMMENT '店铺名称',
    external_business_id varchar(100) COMMENT '外部业务ID',
    fund_details         decimal(10, 2) COMMENT '资金明细',
    type                 varchar(100) COMMENT '类型',
    source               varchar(100) COMMENT '明细来源',
    trans_time           timestamp COMMENT '时间',
    created_by           varchar(100) NOT NULL COMMENT '插入人',
    created_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by           varchar(100) COMMENT '更新人',
    updated_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-账户明细';

CREATE TABLE tm_promotion_report
(
    id                         bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                    varchar(100) COMMENT '店铺id',
    shop_name                  varchar(100) COMMENT '店铺名称',
    biz_day                    date COMMENT '日期',
    plan_id                    bigint COMMENT '计划ID',
    plan_name                  varchar(100) COMMENT '计划名称',
    promotion_type             varchar(100) COMMENT '推广类型',
    unit_id                    bigint COMMENT '单元ID',
    unit_name                  varchar(100) COMMENT '单元名称',
    product_id                 bigint COMMENT '商品ID',
    show_cnt                   bigint COMMENT '展现量',
    click_cnt                  bigint COMMENT '点击量',
    cost                       decimal(10, 2) COMMENT '花费',
    click_rate double COMMENT '点击率',
    avg_click_cost             decimal(10, 2) COMMENT '平均点击花费',
    per_mille_cost             decimal(10, 2) COMMENT '千次展现花费',
    total_favorite_cnt double COMMENT '总收藏数',
    product_favorite_cnt double COMMENT '宝贝收藏数',
    shop_favorite_cnt double COMMENT '店铺收藏数',
    total_cart_cnt double COMMENT '总购物车数',
    direct_cart_cnt double COMMENT '直接购物车数',
    indirect_cart_cnt double COMMENT '间接购物车数',
    cart_cost                  decimal(10, 2) COMMENT '加购成本',
    product_favorite_cost      decimal(10, 2) COMMENT '宝贝收藏成本',
    product_favorite_conversion_rate double COMMENT '宝贝收藏转化率',
    cart_rate double COMMENT '加购率',
    total_presale_amount       decimal(10, 2) COMMENT '总预售成交金额',
    total_presale_order_cnt double COMMENT '总预售成交笔数',
    direct_presale_amount      decimal(10, 2) COMMENT '直接预售成交金额',
    direct_presale_order_cnt double COMMENT '直接预售成交笔数',
    indirect_presale_amount    decimal(10, 2) COMMENT '间接预售成交金额',
    indirect_presale_order_cnt double COMMENT '间接预售成交笔数',
    total_sales_amount         decimal(10, 2) COMMENT '总成交金额',
    direct_sales_amount        decimal(10, 2) COMMENT '直接成交金额',
    indirect_sales_amount      decimal(10, 2) COMMENT '间接成交金额',
    total_sales_order_cnt double COMMENT '总成交笔数',
    direct_sales_order_cnt double COMMENT '直接成交笔数',
    indirect_sales_order_cnt double COMMENT '间接成交笔数',
    return_on_investment double COMMENT '投入产出比',
    conversion_rate double COMMENT '点击转化率',
    direct_conversion_rate double COMMENT '直接点击转化率',
    recharge_order_cnt double COMMENT '购物金充值笔数',
    recharge_amount            decimal(10, 2) COMMENT '购物金充值金额',
    organic_exposure double COMMENT '自然流量曝光',
    organic_conversion_amount  decimal(10, 2) COMMENT '自然流量转化金额',
    total_favorite_cart_cnt double COMMENT '总收藏加购数',
    total_favorite_cart_cost   decimal(10, 2) COMMENT '总收藏加购成本',
    product_favorite_cart_cnt double COMMENT '宝贝收藏加购数',
    product_favorite_cart_cost decimal(10, 2) COMMENT '宝贝收藏加购成本',
    created_by                 varchar(100) NOT NULL COMMENT '插入人',
    created_at                 timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                 varchar(100) COMMENT '更新人',
    updated_at                 timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-直通车-单元报表-单元列表';

CREATE TABLE tm_promotion_performance
(
    id                    bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id               varchar(100) COMMENT '店铺id',
    shop_name             varchar(100) COMMENT '店铺名称',
    product_id            varchar(100) COMMENT '商品ID',
    supplier_code         varchar(100) COMMENT '供应商code',
    brand_name            varchar(100) COMMENT '品牌名称',
    promotion_date        date COMMENT '推广时间',
    campaign_id           varchar(100) COMMENT '活动ID',
    leader_name           varchar(100) COMMENT '团长名称',
    click_cnt             bigint COMMENT '点击数',
    trans_cnt             bigint COMMENT '成交笔数',
    trans_amount          decimal(10, 2) COMMENT '成交金额',
    click_conversion_rate double COMMENT '点击转化率',
    estimated_commission  decimal(10, 2) COMMENT '预估佣金支出',
    estimated_service_fee decimal(10, 2) COMMENT '预估服务费支出',
    estimated_commission_rate double COMMENT '预估佣金率',
    estimated_service_fee_rate double COMMENT '预估服务费率',
    created_by            varchar(100) NOT NULL COMMENT '插入人',
    created_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by            varchar(100) COMMENT '更新人',
    updated_at            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-推广数据';

CREATE TABLE tm_business_overview
(
    id                 bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id            varchar(100) COMMENT '店铺id',
    shop_name          varchar(100) COMMENT '店铺名称',
    biz_day            date COMMENT '日期',
    pay_amount         decimal(10, 2) COMMENT '支付金额',
    avg_suborder_price decimal(10, 2) COMMENT '子订单均价',
    avg_customer_price decimal(10, 2) COMMENT '客单价',
    ipv_uv             bigint COMMENT 'IPVUV',
    pay_suborder_cnt   bigint COMMENT '支付子订单数',
    pay_product_cnt    bigint COMMENT '支付商品件数',
    pay_conversion_rate double COMMENT '支付转化率',
    trans_user_num     bigint COMMENT '成交用户数',
    created_by         varchar(100) NOT NULL COMMENT '插入人',
    created_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by         varchar(100) COMMENT '更新人',
    updated_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-经营概览';

CREATE TABLE tm_product
(
    id                              bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                         varchar(100) COMMENT '店铺id',
    shop_name                       varchar(100) COMMENT '店铺名称',
    biz_day                         date COMMENT '统计日期',
    product_image                   varchar(100) COMMENT '商品图片',
    product_name                    varchar(100) COMMENT '商品名称',
    product_id                      varchar(100) COMMENT '商品ID',
    sku_id                          bigint COMMENT 'SKUID',
    barcode                         varchar(100) COMMENT '条形码',
    goods_id                        varchar(100) COMMENT '货品ID',
    region                          varchar(100) COMMENT '区域',
    warehouse                       varchar(100) COMMENT '仓库',
    four_cate                       varchar(100) COMMENT '四级类目',
    brand                           varchar(100) COMMENT '品牌',
    product_status                  varchar(100) COMMENT '商品状态',
    stock_cnt                       bigint COMMENT '库存件数',
    stock_cnt_mom double COMMENT '库存件数环比',
    good_stock_cnt                  bigint COMMENT '良品库存件数',
    good_stock_cnt_mom double COMMENT '良品库存件数环比',
    good_saleable_stock_cnt         bigint COMMENT '良品可售库存件数',
    good_saleable_stock_cnt_mom double COMMENT '良品可售库存件数环比',
    defective_locked_stock_cnt      bigint COMMENT '残品锁定库存件数',
    defective_locked_stock_cnt_mom double COMMENT '残品锁定库存件数环比',
    exp_warn_good_stock_cnt         bigint COMMENT '效期预警良品库存件数',
    exp_warn_good_stock_cnt_mom double COMMENT '效期预警良品库存件数环比',
    exp_warn_good_stock_ratio double COMMENT '效期预警良品库存件数占比',
    exp_warn_good_stock_ratio_mom double COMMENT '效期预警良品库存件数占比环比',
    exp_defective_stock_ratio double COMMENT '效期残品库存件数占比',
    exp_defective_stock_ratio_mom double COMMENT '效期残品库存件数占比环比',
    defective_stock_cnt             bigint COMMENT '残品库存件数',
    defective_stock_cnt_mom double COMMENT '残品库存件数环比',
    exp_defective_stock_cnt         bigint COMMENT '效期残品库存件数',
    exp_defective_stock_cnt_mom double COMMENT '效期残品库存件数环比',
    exp_managed_stock_cnt           bigint COMMENT '效期管理库存件数',
    exp_managed_stock_cnt_mom double COMMENT '效期管理库存件数环比',
    avg_daily_sales_28d             bigint COMMENT '28天日均销售件数',
    avg_daily_sales_28d_mom double COMMENT '28天日均销售件数环比',
    turnover_days double COMMENT '周转天数',
    turnover_days_mom double COMMENT '周转天数环比',
    pay_amount                      decimal(10, 2) COMMENT '支付金额',
    pay_amount_mom double COMMENT '支付金额环比',
    pay_product_cnt                 bigint COMMENT '支付商品件数',
    pay_product_cnt_mom double COMMENT '支付商品件数环比',
    pay_suborder_cnt                bigint COMMENT '支付子订单数',
    pay_suborder_cnt_mom double COMMENT '支付子订单数环比',
    pay_user_num                    bigint COMMENT '支付用户数',
    pay_user_num_mom double COMMENT '支付用户数环比',
    pay_amount_exclude_refund_cnt   decimal(10, 2) COMMENT '支付金额(剔退款)',
    pay_amount_exclude_refund_cnt_mom double COMMENT '支付金额(剔退款)环比',
    pay_suborder_exclude_refund_cnt bigint COMMENT '支付子订单数(剔退款)',
    pay_suborder_exclude_refund_cnt_mom double COMMENT '支付子订单数(剔退款)环比',
    refund_amount                   decimal(10, 2) COMMENT '发起退款金额',
    refund_amount_mom double COMMENT '发起退款金额环比',
    refund_suborder_cnt             bigint COMMENT '发起退款子订单数',
    refund_suborder_cnt_mom double COMMENT '发起退款子订单数环比',
    refund_product_cnt              bigint COMMENT '发起退款商品件数',
    refund_product_cnt_mom double COMMENT '发起退款商品件数环比',
    refund_success_amount           decimal(10, 2) COMMENT '退款成功金额',
    refund_success_amount_mom double COMMENT '退款成功金额环比',
    refund_success_product_cnt      bigint COMMENT '退款成功商品件数',
    refund_success_product_cnt_mom double COMMENT '退款成功商品件数环比',
    refund_success_suborder_cnt     bigint COMMENT '退款成功子订单数',
    refund_success_suborder_cnt_mom double COMMENT '退款成功子订单数环比',
    created_by                      varchar(100) NOT NULL COMMENT '插入人',
    created_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by                      varchar(100) COMMENT '更新人',
    updated_at                      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-商品信息';

CREATE TABLE tm_living_sale
(
    id                      bigint AUTO_INCREMENT COMMENT '主键ID，自增',
    shop_id                 varchar(100) COMMENT '店铺id',
    shop_name               varchar(100) COMMENT '店铺名称',
    biz_day                 date COMMENT '统计日期',
    product_id              varchar(100) COMMENT '商品ID',
    product_name            varchar(100) COMMENT '商品名称',
    expert_id               varchar(100) COMMENT '达人ID',
    expert_name             varchar(100) COMMENT '达人名称',
    broadcast_date          date COMMENT '开播日期',
    guided_pay_suborder_cnt bigint COMMENT '引导支付子订单数',
    guided_pay_product_cnt  bigint COMMENT '引导支付商品件数',
    guided_pay_amount       decimal(10, 2) COMMENT '引导支付金额',
    pay_user_cnt            bigint COMMENT '支付用户数',
    guided_ipv_uv           bigint COMMENT '引导IPVUV',
    refund_suborder_cnt     bigint COMMENT '退款子订单数',
    guided_pay_conversion_rate double COMMENT '引导支付转化率',
    avg_order_price         decimal(10, 2) COMMENT '笔单价',
    avg_customer_price      decimal(10, 2) COMMENT '客单价',
    refund_rate double COMMENT '退款率',
    created_by              varchar(100) NOT NULL COMMENT '插入人',
    created_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    updated_by              varchar(100) COMMENT '更新人',
    updated_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT ='天猫-销售直播';



select '海豚智投-短视频-财务报表',
       'htzt_finance',
       COLUMN_NAME,
       DATA_TYPE,
       COLUMN_COMMENT,
       CHARACTER_MAXIMUM_LENGTH
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'htzt_finance';

