# ************************************修改表生命周期************************************
ALTER TABLE ods.bud_fin_import_items partitions 30;
ALTER TABLE ods.fill_01_financial_daily_product_cost partitions 30;
ALTER TABLE ods.fill_01_warehouse_logistics_cost_ratios partitions 30;
ALTER TABLE ods.fill_10_cold_chain_product_info partitions 30;
ALTER TABLE ods.fill_abnormal_order_numbers partitions 30;
# ALTER TABLE ods.fill_account_calc_rate partitions 30;
# ALTER TABLE ods.fill_account_cate partitions 30;
ALTER TABLE ods.fill_budget_items partitions 30;
ALTER TABLE ods.fill_chanduola_jd_self_operated_products partitions 30;
ALTER TABLE ods.fill_clearance_sku_list partitions 30;
ALTER TABLE ods.fill_cost_adjustment_template partitions 30;
# ALTER TABLE ods.fill_cost_center_ref partitions 30;
ALTER TABLE ods.fill_daily_report_adjustments partitions 30;
# ALTER TABLE ods.fill_dealer partitions 30;
ALTER TABLE ods.fill_discount_rate_tob_shops partitions 30;
# ALTER TABLE ods.fill_distributor partitions 30;
ALTER TABLE ods.fill_douyin_video_account_orders partitions 30;
# ALTER TABLE ods.fill_dy_bussiness_cate partitions 30;
# ALTER TABLE ods.fill_dy_promotion_fee_rate partitions 30;
# ALTER TABLE ods.fill_expense_center_mapping partitions 30;
ALTER TABLE ods.fill_infant_short_video_product_ids partitions 30;
# ALTER TABLE ods.fill_jd_products partitions 30;
# ALTER TABLE ods.fill_kids_king_erp_data partitions 30;
ALTER TABLE ods.fill_kuaishou_official_flagship_store_short_video_product_links partitions 30;
ALTER TABLE ods.fill_kuaishou_rice_noodles_stream_product_links partitions 30;
ALTER TABLE ods.fill_kuaishou_self_broadcast_stream_product_links partitions 30;
ALTER TABLE ods.fill_ledger_supplement_data partitions 30;
ALTER TABLE ods.fill_leyou_product_codes partitions 30;
ALTER TABLE ods.fill_mao_chao_products partitions 30;
ALTER TABLE ods.fill_nsv_budget partitions 30;
ALTER TABLE ods.fill_platform_fee_ratios partitions 30;
ALTER TABLE ods.fill_price_control_tasting_list partitions 30;
ALTER TABLE ods.fill_private_domain_video_store_order_info partitions 30;
ALTER TABLE ods.fill_product_cate partitions 30;
ALTER TABLE ods.fill_product_export_non_food_gifts partitions 30;
ALTER TABLE ods.fill_sales_management_channel_correlation_form partitions 30;
ALTER TABLE ods.fill_sales_management_channel_relations partitions 30;
ALTER TABLE ods.fill_sales_management_shop_code_business_category partitions 30;
ALTER TABLE ods.fill_sales_management_shop_dp_channel_relations partitions 30;
# ALTER TABLE ods.fill_send_shop_cost partitions 30;
# ALTER TABLE ods.fill_shop_cate partitions 30;
# ALTER TABLE ods.fill_shop_channel_cate partitions 30;
ALTER TABLE ods.fill_short_video_luban_promotion_product_id partitions 30;
# ALTER TABLE ods.fill_sku_cate partitions 30;
ALTER TABLE ods.fill_temp_data_non_food_cost partitions 30;
ALTER TABLE ods.fill_temp_data_tasting_cost partitions 30;
ALTER TABLE ods.fill_tianmao_drop_shipping_supply_price partitions 30;
ALTER TABLE ods.fill_tianmao_infant_supply_prices partitions 30;
ALTER TABLE ods.fill_tianmao_wholesale_supply_price partitions 30;
ALTER TABLE ods.fill_ze_yuan_distributors_gift_policies partitions 30;
ALTER TABLE ods.jky_allocate partitions 30;
ALTER TABLE ods.jky_allocate_detail_views partitions 30;
ALTER TABLE ods.jky_allocate_detail_views_batchlist partitions 30;
ALTER TABLE ods.jky_allocate_detail_views_seriallist partitions 30;
ALTER TABLE ods.jky_ass_business_refundlist partitions 30;
ALTER TABLE ods.jky_ass_business_refundlist_refundgoodsitems partitions 30;
ALTER TABLE ods.jky_business_log partitions 30;
ALTER TABLE ods.jky_customer_list partitions 30;
ALTER TABLE ods.jky_customer_list_receivablesaccountarr partitions 30;
ALTER TABLE ods.jky_customer_list_source partitions 30;
ALTER TABLE ods.jky_erp_storage_goodsdocout_v2_logisticlist partitions 30;
ALTER TABLE ods.jky_goods_package partitions 30;
ALTER TABLE ods.jky_goods_package_detail partitions 30;
ALTER TABLE ods.jky_goods_source partitions 30;
ALTER TABLE ods.jky_goods_stock_quantity partitions 30;
ALTER TABLE ods.jky_goods_stock_quantity_batch partitions 30;
ALTER TABLE ods.jky_in_storage partitions 30;
ALTER TABLE ods.jky_in_storage_goodsdocdetail partitions 30;
ALTER TABLE ods.jky_oms_business_order partitions 30;
ALTER TABLE ods.jky_oms_business_order_detai partitions 30;
ALTER TABLE ods.jky_oms_open_trade_settle partitions 30;
ALTER TABLE ods.jky_out_storagev2_logistic partitions 30;
ALTER TABLE ods.jky_pricelist partitions 30;
ALTER TABLE ods.jky_purch_order partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdelivery partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdto partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodscolumnexts partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdelivery partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdiscount partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail_packagedetail partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsserial partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_otherpaymentfees partitions 30;
ALTER TABLE ods.jky_qm_trades_fullinfo_paylist partitions 30;
ALTER TABLE ods.jky_return_change partitions 30;
ALTER TABLE ods.jky_return_change_goods_attachmentinfo partitions 30;
ALTER TABLE ods.jky_return_change_goods_detail partitions 30;
ALTER TABLE ods.jky_return_change_goods_detail_batch partitions 30;
ALTER TABLE ods.jky_return_change_goods_orderassemblygoodsdto partitions 30;
ALTER TABLE ods.jky_sales_channel partitions 30;
ALTER TABLE ods.jky_stock_out partitions 30;
ALTER TABLE ods.jky_storage_goodsinfo partitions 30;
ALTER TABLE ods.jky_storage_goodsinfo_filelist partitions 30;
ALTER TABLE ods.jky_storage_goodsinfo_goodsinfodescript partitions 30;
ALTER TABLE ods.jky_storage_goodsinfo_goodsunit partitions 30;
ALTER TABLE ods.jky_storage_goodsinfo_imgurllist partitions 30;
ALTER TABLE ods.jky_vend partitions 30;
ALTER TABLE ods.jky_warehouse_info partitions 30;
ALTER TABLE ods.jky_warehouse_info_saleslist partitions 30;
# ALTER TABLE ods.ods_dy_shop_sub_rating_metrics partitions 30;
# ALTER TABLE ods.ods_yy_dialogue_records partitions 30;
# ALTER TABLE ods.shop_share partitions 30;
ALTER TABLE ods.zzy_etl_task partitions 30;

BUILD TABLE ods.bud_fin_import_items;
BUILD TABLE ods.fill_01_financial_daily_product_cost;
BUILD TABLE ods.fill_01_warehouse_logistics_cost_ratios;
BUILD TABLE ods.fill_10_cold_chain_product_info;
BUILD TABLE ods.fill_abnormal_order_numbers;
BUILD TABLE ods.fill_account_calc_rate;
BUILD TABLE ods.fill_account_cate;
BUILD TABLE ods.fill_budget_items;
BUILD TABLE ods.fill_chanduola_jd_self_operated_products;
BUILD TABLE ods.fill_clearance_sku_list;
BUILD TABLE ods.fill_cost_adjustment_template;
BUILD TABLE ods.fill_cost_center_ref;
BUILD TABLE ods.fill_daily_report_adjustments;
BUILD TABLE ods.fill_dealer;
BUILD TABLE ods.fill_discount_rate_tob_shops;
BUILD TABLE ods.fill_distributor;
BUILD TABLE ods.fill_douyin_video_account_orders;
BUILD TABLE ods.fill_dy_bussiness_cate;
BUILD TABLE ods.fill_dy_promotion_fee_rate;
BUILD TABLE ods.fill_expense_center_mapping;
BUILD TABLE ods.fill_infant_short_video_product_ids;
BUILD TABLE ods.fill_jd_products;
BUILD TABLE ods.fill_kids_king_erp_data;
BUILD TABLE ods.fill_kuaishou_official_flagship_store_short_video_product_links;
BUILD TABLE ods.fill_kuaishou_rice_noodles_stream_product_links;
BUILD TABLE ods.fill_kuaishou_self_broadcast_stream_product_links;
BUILD TABLE ods.fill_ledger_supplement_data;
BUILD TABLE ods.fill_leyou_product_codes;
BUILD TABLE ods.fill_mao_chao_products;
BUILD TABLE ods.fill_nsv_budget;
BUILD TABLE ods.fill_platform_fee_ratios;
BUILD TABLE ods.fill_price_control_tasting_list;
BUILD TABLE ods.fill_private_domain_video_store_order_info;
BUILD TABLE ods.fill_product_cate;
BUILD TABLE ods.fill_product_export_non_food_gifts;
BUILD TABLE ods.fill_sales_management_channel_correlation_form;
BUILD TABLE ods.fill_sales_management_channel_relations;
BUILD TABLE ods.fill_sales_management_shop_code_business_category;
BUILD TABLE ods.fill_sales_management_shop_dp_channel_relations;
BUILD TABLE ods.fill_send_shop_cost;
BUILD TABLE ods.fill_shop_cate;
BUILD TABLE ods.fill_shop_channel_cate;
BUILD TABLE ods.fill_short_video_luban_promotion_product_id;
BUILD TABLE ods.fill_sku_cate;
BUILD TABLE ods.fill_temp_data_non_food_cost;
BUILD TABLE ods.fill_temp_data_tasting_cost;
BUILD TABLE ods.fill_tianmao_drop_shipping_supply_price;
BUILD TABLE ods.fill_tianmao_infant_supply_prices;
BUILD TABLE ods.fill_tianmao_wholesale_supply_price;
BUILD TABLE ods.fill_ze_yuan_distributors_gift_policies;
BUILD TABLE ods.jky_allocate;
BUILD TABLE ods.jky_allocate_detail_views;
BUILD TABLE ods.jky_allocate_detail_views_batchlist;
BUILD TABLE ods.jky_allocate_detail_views_seriallist;
BUILD TABLE ods.jky_ass_business_refundlist;
BUILD TABLE ods.jky_ass_business_refundlist_refundgoodsitems;
BUILD TABLE ods.jky_business_log;
BUILD TABLE ods.jky_customer_list;
BUILD TABLE ods.jky_customer_list_receivablesaccountarr;
BUILD TABLE ods.jky_customer_list_source;
BUILD TABLE ods.jky_erp_storage_goodsdocout_v2_logisticlist;
BUILD TABLE ods.jky_goods_package;
BUILD TABLE ods.jky_goods_package_detail;
BUILD TABLE ods.jky_goods_source;
BUILD TABLE ods.jky_goods_stock_quantity;
BUILD TABLE ods.jky_goods_stock_quantity_batch;
BUILD TABLE ods.jky_in_storage;
BUILD TABLE ods.jky_in_storage_goodsdocdetail;
BUILD TABLE ods.jky_oms_business_order;
BUILD TABLE ods.jky_oms_business_order_detai;
BUILD TABLE ods.jky_oms_open_trade_settle;
BUILD TABLE ods.jky_out_storagev2_logistic;
BUILD TABLE ods.jky_pricelist;
BUILD TABLE ods.jky_purch_order;
BUILD TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdelivery;
BUILD TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdto;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodscolumnexts;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdelivery;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdiscount;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail_packagedetail;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsserial;
BUILD TABLE ods.jky_qm_trades_fullinfo_otherpaymentfees;
BUILD TABLE ods.jky_qm_trades_fullinfo_paylist;
BUILD TABLE ods.jky_return_change;
BUILD TABLE ods.jky_return_change_goods_attachmentinfo;
BUILD TABLE ods.jky_return_change_goods_detail;
BUILD TABLE ods.jky_return_change_goods_detail_batch;
BUILD TABLE ods.jky_return_change_goods_orderassemblygoodsdto;
BUILD TABLE ods.jky_sales_channel;
BUILD TABLE ods.jky_stock_out;
BUILD TABLE ods.jky_storage_goodsinfo;
BUILD TABLE ods.jky_storage_goodsinfo_filelist;
BUILD TABLE ods.jky_storage_goodsinfo_goodsinfodescript;
BUILD TABLE ods.jky_storage_goodsinfo_goodsunit;
BUILD TABLE ods.jky_storage_goodsinfo_imgurllist;
BUILD TABLE ods.jky_vend;
BUILD TABLE ods.jky_warehouse_info;
BUILD TABLE ods.jky_warehouse_info_saleslist;
BUILD TABLE ods.ods_dy_shop_sub_rating_metrics;
BUILD TABLE ods.ods_yy_dialogue_records;
BUILD TABLE ods.shop_share;
BUILD TABLE ods.zzy_etl_task;

# ************************************修改热数据分区数************************************

ALTER TABLE ods.bud_fin_import_items STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_01_financial_daily_product_cost STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_01_warehouse_logistics_cost_ratios STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_10_cold_chain_product_info STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_abnormal_order_numbers STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_account_calc_rate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_account_cate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_budget_items STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_chanduola_jd_self_operated_products STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_clearance_sku_list STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_cost_adjustment_template STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_cost_center_ref STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_daily_report_adjustments STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_dealer STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_discount_rate_tob_shops STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_distributor STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_douyin_video_account_orders STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_dy_bussiness_cate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_dy_promotion_fee_rate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_expense_center_mapping STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_infant_short_video_product_ids STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_jd_products STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_kids_king_erp_data STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_kuaishou_official_flagship_store_short_video_product_links STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_kuaishou_rice_noodles_stream_product_links STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_kuaishou_self_broadcast_stream_product_links STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_ledger_supplement_data STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_leyou_product_codes STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_mao_chao_products STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_nsv_budget STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_platform_fee_ratios STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_price_control_tasting_list STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_private_domain_video_store_order_info STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_product_cate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_product_export_non_food_gifts STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_sales_management_channel_correlation_form STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_sales_management_channel_relations STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_sales_management_shop_code_business_category STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_sales_management_shop_dp_channel_relations STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_send_shop_cost STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_shop_cate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_shop_channel_cate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_short_video_luban_promotion_product_id STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_sku_cate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_temp_data_non_food_cost STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_temp_data_tasting_cost STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_tianmao_drop_shipping_supply_price STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_tianmao_infant_supply_prices STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_tianmao_wholesale_supply_price STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.fill_ze_yuan_distributors_gift_policies STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_allocate STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_allocate_detail_views STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_allocate_detail_views_batchlist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_allocate_detail_views_seriallist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_ass_business_refundlist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_ass_business_refundlist_refundgoodsitems STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_business_log STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_customer_list STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_customer_list_receivablesaccountarr STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_customer_list_source STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_erp_storage_goodsdocout_v2_logisticlist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_goods_package STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_goods_package_detail STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_goods_source STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_goods_stock_quantity STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_goods_stock_quantity_batch STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_in_storage STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_in_storage_goodsdocdetail STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_oms_business_order STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_oms_business_order_detai STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_oms_open_trade_settle STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_out_storagev2_logistic STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_pricelist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_purch_order STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdelivery STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdto STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodscolumnexts STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdelivery STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdiscount STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsdetail_packagedetail STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_goodsserial STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_otherpaymentfees STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_qm_trades_fullinfo_paylist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_return_change STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_return_change_goods_attachmentinfo STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_return_change_goods_detail STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_return_change_goods_detail_batch STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_return_change_goods_orderassemblygoodsdto STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_sales_channel STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_stock_out STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_storage_goodsinfo STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_storage_goodsinfo_filelist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_storage_goodsinfo_goodsinfodescript STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_storage_goodsinfo_goodsunit STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_storage_goodsinfo_imgurllist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_vend STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_warehouse_info STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.jky_warehouse_info_saleslist STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.ods_dy_shop_sub_rating_metrics STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.ods_yy_dialogue_records STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.shop_share STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
ALTER TABLE ods.zzy_etl_task STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;

BUILD TABLE ods.bud_fin_import_items;
BUILD TABLE ods.fill_01_financial_daily_product_cost;
BUILD TABLE ods.fill_01_warehouse_logistics_cost_ratios;
BUILD TABLE ods.fill_10_cold_chain_product_info;
BUILD TABLE ods.fill_abnormal_order_numbers;
BUILD TABLE ods.fill_account_calc_rate;
BUILD TABLE ods.fill_account_cate;
BUILD TABLE ods.fill_budget_items;
BUILD TABLE ods.fill_chanduola_jd_self_operated_products;
BUILD TABLE ods.fill_clearance_sku_list;
BUILD TABLE ods.fill_cost_adjustment_template;
BUILD TABLE ods.fill_cost_center_ref;
BUILD TABLE ods.fill_daily_report_adjustments;
BUILD TABLE ods.fill_dealer;
BUILD TABLE ods.fill_discount_rate_tob_shops;
BUILD TABLE ods.fill_distributor;
BUILD TABLE ods.fill_douyin_video_account_orders;
BUILD TABLE ods.fill_dy_bussiness_cate;
BUILD TABLE ods.fill_dy_promotion_fee_rate;
BUILD TABLE ods.fill_expense_center_mapping;
BUILD TABLE ods.fill_infant_short_video_product_ids;
BUILD TABLE ods.fill_jd_products;
BUILD TABLE ods.fill_kids_king_erp_data;
BUILD TABLE ods.fill_kuaishou_official_flagship_store_short_video_product_links;
BUILD TABLE ods.fill_kuaishou_rice_noodles_stream_product_links;
BUILD TABLE ods.fill_kuaishou_self_broadcast_stream_product_links;
BUILD TABLE ods.fill_ledger_supplement_data;
BUILD TABLE ods.fill_leyou_product_codes;
BUILD TABLE ods.fill_mao_chao_products;
BUILD TABLE ods.fill_nsv_budget;
BUILD TABLE ods.fill_platform_fee_ratios;
BUILD TABLE ods.fill_price_control_tasting_list;
BUILD TABLE ods.fill_private_domain_video_store_order_info;
BUILD TABLE ods.fill_product_cate;
BUILD TABLE ods.fill_product_export_non_food_gifts;
BUILD TABLE ods.fill_sales_management_channel_correlation_form;
BUILD TABLE ods.fill_sales_management_channel_relations;
BUILD TABLE ods.fill_sales_management_shop_code_business_category;
BUILD TABLE ods.fill_sales_management_shop_dp_channel_relations;
BUILD TABLE ods.fill_send_shop_cost;
BUILD TABLE ods.fill_shop_cate;
BUILD TABLE ods.fill_shop_channel_cate;
BUILD TABLE ods.fill_short_video_luban_promotion_product_id;
BUILD TABLE ods.fill_sku_cate;
BUILD TABLE ods.fill_temp_data_non_food_cost;
BUILD TABLE ods.fill_temp_data_tasting_cost;
BUILD TABLE ods.fill_tianmao_drop_shipping_supply_price;
BUILD TABLE ods.fill_tianmao_infant_supply_prices;
BUILD TABLE ods.fill_tianmao_wholesale_supply_price;
BUILD TABLE ods.fill_ze_yuan_distributors_gift_policies;
BUILD TABLE ods.jky_allocate;
BUILD TABLE ods.jky_allocate_detail_views;
BUILD TABLE ods.jky_allocate_detail_views_batchlist;
BUILD TABLE ods.jky_allocate_detail_views_seriallist;
BUILD TABLE ods.jky_ass_business_refundlist;
BUILD TABLE ods.jky_ass_business_refundlist_refundgoodsitems;
BUILD TABLE ods.jky_business_log;
BUILD TABLE ods.jky_customer_list;
BUILD TABLE ods.jky_customer_list_receivablesaccountarr;
BUILD TABLE ods.jky_customer_list_source;
BUILD TABLE ods.jky_erp_storage_goodsdocout_v2_logisticlist;
BUILD TABLE ods.jky_goods_package;
BUILD TABLE ods.jky_goods_package_detail;
BUILD TABLE ods.jky_goods_source;
BUILD TABLE ods.jky_goods_stock_quantity;
BUILD TABLE ods.jky_goods_stock_quantity_batch;
BUILD TABLE ods.jky_in_storage;
BUILD TABLE ods.jky_in_storage_goodsdocdetail;
BUILD TABLE ods.jky_oms_business_order;
BUILD TABLE ods.jky_oms_business_order_detai;
BUILD TABLE ods.jky_oms_open_trade_settle;
BUILD TABLE ods.jky_out_storagev2_logistic;
BUILD TABLE ods.jky_pricelist;
BUILD TABLE ods.jky_purch_order;
BUILD TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdelivery;
BUILD TABLE ods.jky_qm_trades_fullinfo_assembly_goodsdto;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodscolumnexts;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdelivery;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail_goodsdiscount;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsdetail_packagedetail;
BUILD TABLE ods.jky_qm_trades_fullinfo_goodsserial;
BUILD TABLE ods.jky_qm_trades_fullinfo_otherpaymentfees;
BUILD TABLE ods.jky_qm_trades_fullinfo_paylist;
BUILD TABLE ods.jky_return_change;
BUILD TABLE ods.jky_return_change_goods_attachmentinfo;
BUILD TABLE ods.jky_return_change_goods_detail;
BUILD TABLE ods.jky_return_change_goods_detail_batch;
BUILD TABLE ods.jky_return_change_goods_orderassemblygoodsdto;
BUILD TABLE ods.jky_sales_channel;
BUILD TABLE ods.jky_stock_out;
BUILD TABLE ods.jky_storage_goodsinfo;
BUILD TABLE ods.jky_storage_goodsinfo_filelist;
BUILD TABLE ods.jky_storage_goodsinfo_goodsinfodescript;
BUILD TABLE ods.jky_storage_goodsinfo_goodsunit;
BUILD TABLE ods.jky_storage_goodsinfo_imgurllist;
BUILD TABLE ods.jky_vend;
BUILD TABLE ods.jky_warehouse_info;
BUILD TABLE ods.jky_warehouse_info_saleslist;
BUILD TABLE ods.ods_dy_shop_sub_rating_metrics;
BUILD TABLE ods.ods_yy_dialogue_records;
BUILD TABLE ods.shop_share;
BUILD TABLE ods.zzy_etl_task;

# step1
ALTER TABLE ods.jky_qm_trades_fullinfo partitions 365;
ALTER TABLE ods.jky_qm_trades_fullinfo STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
# step2
BUILD TABLE ods.jky_qm_trades_fullinfo;
# 查看进度
SELECT table_name, schema_name, status FROM INFORMATION_SCHEMA.KEPLER_META_BUILD_TASK ORDER BY create_time DESC LIMIT 10;
# 查看表ddl修改
show create table ods.jky_qm_trades_fullinfo;



select * from INFORMATION_SCHEMA.PARTITIONS where TABLE_SCHEMA = 'dwd';



# step1
ALTER TABLE ods.jky_erp_storage_goodsdocout_v2_goodsdocdetail partitions 30;
ALTER TABLE ods.jky_erp_storage_goodsdocout_v2_goodsdocdetail STORAGE_POLICY='MIXED' HOT_PARTITION_COUNT=7;
# step2
BUILD TABLE ods.jky_erp_storage_goodsdocout_v2_goodsdocdetail;
# 查看进度
SELECT table_name, schema_name, status
FROM INFORMATION_SCHEMA.KEPLER_META_BUILD_TASK
ORDER BY create_time DESC
LIMIT 10;
# 查看表ddl修改
show create table ods.jky_qm_trades_fullinfo_goodsdetail;




