--  *********************************** 台账 ***********************************
-- 交易域-各渠道交易统计
CREATE TABLE ads.trd_order_by_channel
(
    biz_day         date COMMENT '日期',
    level_1_channel varchar(100) COMMENT '一级渠道',
    level_2_channel varchar(100) COMMENT '二级渠道',
    level_3_channel varchar(100) COMMENT '三级渠道',
    费用中心,
    rspgmv          decimal(16, 2) COMMENT 'rspgmv',
    gmv             decimal(16, 2) COMMENT '成交金额',
    rfd_amt         decimal(16, 2) COMMENT '退款金额',
    gsv            decimal(16, 2) COMMENT '营业收入',
    nsv            decimal(16, 2) COMMENT '净销售额',
    赠品费用
    PRIMARY KEY (biz_day, level_1_channel, level_2_channel, level_3_channel,费用中心, dt)
)PARTITION BY VALUE(dt) COMMENT '交易域-各渠道下单统计';

-- 交易域-各费用中心交易统计
ads.fin_费用中心   
日期:DATE,
费用中心编码:STRING,
费用中心名称:STRING,
一级中心/部门:STRING,
二级部门:STRING,
费用中心:STRING,
一级部门:STRING,
一级渠道:STRING,
二级渠道:STRING,
三级渠道:STRING,
来源:STRING,
二级分类:STRING,
三级分类:STRING,
GMV:DOUBLE,
NSV:DOUBLE,
NSV预算-RSP占比:DOUBLE,
RSPGMV:DOUBLE,
尝鲜装RSP:DOUBLE,
尝鲜装搭赠:DOUBLE,
尝鲜装拉新:DOUBLE,
2B分销客户返点:DOUBLE,
2B渠道毛保:DOUBLE,
非食赠品采购成本:DOUBLE,
非食赠品-入库:DOUBLE,

-- -- 财务域-各渠道交易统计
CREATE TABLE ads.fin_order_by_费用中心  总的
(
    biz_day         date COMMENT '日期',
    level_1_channel varchar(100) COMMENT '一级渠道',
    level_2_channel varchar(100) COMMENT '二级渠道',
    level_3_channel varchar(100) COMMENT '三级渠道',
    费用中心,
    二级分类，
    三级分类，
    预算科目名称，
    amt             decimal(16, 2) COMMENT '金额',
    PRIMARY KEY (biz_day, level_1_channel, level_2_channel, level_3_channel,费用中心, dt)
)PARTITION BY VALUE(dt) COMMENT '交易域-各渠道下单统计';

-- 财务域-各费用中心交易统计 rpa_ddl
ads.fin_推广费相关
日期:DATE,
费用中心编码:STRING,
费用中心名称:STRING,
一级中心/部门:STRING,
二级部门:STRING,
费用中心:STRING,
一级部门:STRING,
一级渠道:STRING,
二级渠道:STRING,
三级渠道:STRING,
来源:STRING,
二级分类:STRING,
三级分类:STRING,
OTD推广费用:DOUBLE,
磁力金牛PC:DOUBLE,
磁力金牛移动:DOUBLE,
促销员激励:DOUBLE,
达人短视频服务费:DOUBLE,
达人短视频线下返佣:DOUBLE,
达人样品费:DOUBLE,
达人直播服务费:DOUBLE,
达人直播线下返佣:DOUBLE,
大促及爆品推广资源采买:DOUBLE,
代言、商务合作、推广、广告:DOUBLE,
抖音:DOUBLE,
抖音千川:DOUBLE,
抖音随心推:DOUBLE,
短视频达人佣金:DOUBLE,
多多客佣金:DOUBLE,
CID、UD信息流投放:DOUBLE,
京挑客佣金:DOUBLE,
快车:DOUBLE,
推广设计费:DOUBLE,
万相台:DOUBLE,
引力魔方:DOUBLE,
小红书推广费:DOUBLE,
唯享客佣金:DOUBLE,
直播达人佣金:DOUBLE,
直通车:DOUBLE,
智能投放:DOUBLE,

-- 财务域-各费用中心交易统计 手工填报
ads.fin_填报相关
日期:DATE,
费用中心编码:STRING,
费用中心名称:STRING,
一级中心/部门:STRING,
二级部门:STRING,
费用中心:STRING,
一级部门:STRING,
一级渠道:STRING,
二级渠道:STRING,
三级渠道:STRING,
来源:STRING,
二级分类:STRING,
三级分类:STRING,
AI电话费用:DOUBLE,
办公设备维修费:DOUBLE,
办公用品费:DOUBLE,
保洁费:DOUBLE,
保证金:DOUBLE,
标准化体系认证费（研发和实验室相关）:DOUBLE,
餐费补贴:DOUBLE,
仓配原因类赔付:DOUBLE,
产品推广服务费:DOUBLE,
产品委外调研费用:DOUBLE,
场地租赁费:DOUBLE,
场地租赁费、日常费用:DOUBLE,
场景推广:DOUBLE,
场租:DOUBLE,
车辆保险/年审费:DOUBLE,
车辆保养/维修费:DOUBLE,
道具采购费:DOUBLE,
电费:DOUBLE,
电商平台服务费:DOUBLE,
电商违约赔付费用:DOUBLE,
店内广告费:DOUBLE,
店铺扣点:DOUBLE,
公关维护及业务招待费（不含专项认证费）:DOUBLE,
公路水路交通:DOUBLE,
公益费:DOUBLE,
购物触点:DOUBLE,
国内渠道代运营服务费:DOUBLE,
过路过桥/停车费:DOUBLE,
海投:DOUBLE,
合同条款-毛保:DOUBLE,
合同条款-其他费:DOUBLE,
会议会务费（含内、外部）:DOUBLE,
基本工资:DOUBLE,
基准成本:DOUBLE,
加班餐费:DOUBLE,
加班交通费:DOUBLE,
节日福利费:DOUBLE,
经销商返利:DOUBLE,
经营亏损、健康影响类赔付:DOUBLE,
竞品采购费:DOUBLE,
客户出货返利:DOUBLE,
客户关系维护:DOUBLE,
客户进货返利:DOUBLE,
客情维护:DOUBLE,
控价维权:DOUBLE,
快递费:DOUBLE,
买家秀维护:DOUBLE,
内部产品领用:DOUBLE,
品牌设计费:DOUBLE,
品牌展示费:DOUBLE,
品牌专区:DOUBLE,
品销宝:DOUBLE,
平台服务充值:DOUBLE,
评价费用:DOUBLE,
其他办公费:DOUBLE,
其他原因类赔付:DOUBLE,
其他咨询费:DOUBLE,
渠道成本:DOUBLE,
渠道费用:DOUBLE,
渠道媒介投放:DOUBLE,
渠道系统服务使用费:DOUBLE,
全站推广:DOUBLE,
人力外包费用:DOUBLE,
商品成本:DOUBLE,
商务合作费:DOUBLE,
市内交通:DOUBLE,
售后赔付（质量）:DOUBLE,
水费:DOUBLE,
税金:DOUBLE,
私车公用补贴:DOUBLE,
搜索推广:DOUBLE,
淘宝客佣金:DOUBLE,
提成:DOUBLE,
体检费:DOUBLE,
铁路航空交通:DOUBLE,
图片拍摄费:DOUBLE,
团建费:DOUBLE,
退差价:DOUBLE,
退货物流费用:DOUBLE,
退款金额:DOUBLE,
外部参展费:DOUBLE,
外部培训费:DOUBLE,
网络服务费:DOUBLE,
网络媒体普发投放:DOUBLE,
微信豆:DOUBLE,
文件影印费:DOUBLE,
物料制作费:DOUBLE,
线下物流费用:DOUBLE,
消费者价格促销:DOUBLE,
协会会费:DOUBLE,
信息服务采购:DOUBLE,
信息化项目建设费:DOUBLE,
行政车辆油费:DOUBLE,
行政低耗品:DOUBLE,
行政快递费:DOUBLE,
研发原材料费及备件耗材费用:DOUBLE,
养老保险:DOUBLE,
业务招待费:DOUBLE,
易耗道具采购费用:DOUBLE,
因公外出交通费:DOUBLE,
营业收入:DOUBLE,
优秀奖励（含优秀团队/个人）:DOUBLE,
员工慰问费:DOUBLE,
运费险:DOUBLE,
运营原因类赔付:DOUBLE,
招聘费用（含常规平台服务费、场地及资料费，不含差旅）:DOUBLE,
主货架陈列费:DOUBLE,
主推项目:DOUBLE,
住宿费:DOUBLE,
字体/图库等版权采购费:DOUBLE,
综艺/剧植:DOUBLE,